### PR TITLE
quick fix for kaldi online decoder crash

### PR DESCRIPTION
**Pull request by fanskyer**
From my experiment, in very rare cases, kaldi online decoder will crash due to last_seen_input_frames were not previously set. I made this quick fix and it can deal with this issue and decoder no longer crashed.

### CODE REVIEW

**Comment by danpovey** [comment]
Hm, thanks for finding the problem, but I don't think this is quite the right fix... can you please let me know what the crash was exactly, with maybe a stack trace?

**Comment by fanskyer** [comment]
Here is one crash log, attached below, em, this quick fix is not fixing the fundamental issue 


ERROR (CopyRowsFromVec():kaldi-matrix.cc:867) Wrong sized arguments

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&,
char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::MatrixBase<float>::CopyRowsFromVec(kaldi::VectorBase<float> const&)
kaldi::nnet2::NnetOnlineComputer::Flush(kaldi::CuMatrix<float>*)
kaldi::SingleUtteranceNnet2DecoderThreaded::RunNnetEvaluationInternal()
kaldi::SingleUtteranceNnet2DecoderThreaded::RunNnetEvaluation(void*)

**Comment by danpovey** [comment]
Can you please apply the patch from my PR #1000 and see if it fixes the problem?

**Comment by fanskyer** [comment]
sure, will test it, thanks



-----Original Message-----

**Pull request closed without merging**
