### PR TITLE
Lightweight version of steps/shift_feats.sh

### PR DESCRIPTION
**Pull request by hhadian**

### CODE REVIEW

**Comment by danpovey** [comment]
Looks OK.  I'll merge it since it's just the shortcut branch.  I think it would be good if you could write an example script that uses this-- some script involved in discriminative training of your frame-subsampled systems, maybe.

**Comment by danpovey** [comment]
Actually, I notice it's WIP.  Please remove WIP if you think it's ready to merge.

**Comment by hhadian** [comment]
It is ready. I wanted to test and check it again but I forgot to remove WIP. 
It is tested and ready to be merged.
I will prepare a discriminative training script that uses this, and I will test it on my LFR branch.

**Comment by danpovey** [comment]
Actually, before I merge, can you add a note in a comment and in the usage message of steps/shift_feats.sh to say that it's deprecated and utils/data/shift_feats.sh should be used?

**Comment by hhadian** [comment]
It is done

**Comment by danpovey** [comment]
Thanks!  Merging.

**Pull request merged**
