### PR TITLE
[src] Move cuda gpu from nnetbin to nnet3bin. 

### PR DESCRIPTION
**Pull request by danpovey**

### CODE REVIEW

**Comment by xiaohui-zhang** [comment]
actually I meant nnet2bin/cuda-compiled.cc, which is widely used in nnet3 training scripts... cuda-gpu-available is not widely used.

**Comment by naxingyu** [comment]
This has been done in kaldi10

**Comment by xiaohui-zhang** [comment]
oh cool thx!

**Comment by xiaohui-zhang** [comment]
hopefully kaldi10'll be merged to master soon?

**Comment by danpovey** [comment]
Kaldi10 won't be merged for quite a while, but I did move that binary.

**Comment by xiaohui-zhang** [comment]
thank you boss!

**Pull request merged**
