### PR TITLE
Use get_python_inc and print function in install scripts

### PR DESCRIPTION
**Pull request by leomao**
Use the function form of `print` to support both python 2 and 3.
Use get_python_inc from sysconfig, this function is simpler.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.  However, I think for sequitur we have to be a bit more careful-- you actually cannot use sequitur if python resolves to python3, I believe.  It might be possible to somehow rejig it to invoke python2 directly, but that would be complicated and @jtrmal would have to help.  For that one, could you just make it so the installation script, if it detects that python is really python3, just dies with a suitable error message.

**Comment by danpovey** [comment]
@jtrmal, any comment?

**Comment by jtrmal** [comment]
Actually, looking at the code, I think there is the statement "from
__future__ import print_function" missing in the oneliners.
Y.

**Comment by danpovey** [comment]
I think it works in this case as there's just one arg to the print
function, which python2.7 would treat as an expression with parentheses
around it.

**Pull request merged**
