### PR TITLE
Change tmpdir root

### PR DESCRIPTION
**Pull request by vesis84**
- previous version was causing error, when other user was running
  the script from my location without having the write pemisson
  to create the 'tmpdir'
- if the tmpdir is relative to '$data' all is fine

### CODE REVIEW

**Comment by jtrmal** [comment]
Also, when I look at the list of commits, I'm not sure why the merge is a part of it.
y.

**Comment by vesis84** [comment]
@Dan: the problem occurs in BUT cluster, the 'mktemp -d' creates tmpdir rellative to $PWD, and I made sure the TMPDIR was not set.

@Yenda: I did sync the 'vesis84/change_tmpdir_root' from 'kaldi-asr/mater' after adding the patch to the local copy. The merge-back into 'kaldi-asr/master' is is a no-op whichi will add one more record into the history. (I can prepare another branch without the log if necessary).

The situation is like this: I want to share a segmentation script with Martin (not part of kaldi), while he does not need the write permission to the location of the script.

The script takes a wav, wraps it up in 'data-dir', runs feature extraction, runs forward-pass with NN.
The script starts by 'cd' to its location, and all the outputs are stored into a 'tmpdir'.

During feature extraction by 'steps/make_fbank_pitch.sh' it calls 'utils/validate_data_dir.sh', which is creating a 'tmpdir' relative to the scripts location, which is not what I want and have no other way to avoid...

Any suggestions?

**Comment by danpovey** [comment]
I think I must have misinterpreted the man page of mktemp.
Karel, please use /tmp as the temporary directory, so -d /tmp/kaldi.XXX.
That was the intention all along, but it was not what it was doing.
Many other parts of Kaldi use /tmp, so we can assume that it exists.
Dan

**Comment by vesis84** [comment]
I think there was a problem on 'Darwin' something like '/tmp' does not exist there... (not totally sure)

**Comment by danpovey** [comment]
That wasn't it, it was a separate issue.  Darwin was the reason we needed
to use the template in the first place; there, the template (kaldi.XXX) is
not optional.
Dan

**Comment by vesis84** [comment]
Ok, good! I'll do the change, will look also at the other locations of 'mktemp' in the scripts.

**Pull request closed without merging**
