### PR TITLE
Change tmpdir root to : /tmp/kaldi.XXXX

### PR DESCRIPTION
**Pull request by vesis84**
- not sure how to remove '6c3bc3c', which comes from sync of my vesis84/master with kaldi-asr/master

### CODE REVIEW

**Comment by danpovey** [comment]
Karel, let's try to get this right and improve our knowledge of git.  This pull-request isn't urgent.
I suggest you check out the upstream/master cleanly, and then apply a patch generated by a diff between your branches, to the new branch you create.

**Comment by jtrmal** [comment]
You could also try (provided upstream is the official kaldi repo)
git checkout upstream/master -b tmp_fix
git cherry-pick b988cc4
git commit
git push -u origin tmp_fix

(I assume you have no local modification before the checkout -- if yes,
then you can use git stash ti "hide" them)
Also, I didn;t try, so it might need a little bit fine tuning, but in
general this should work
y.

**Comment by vesis84** [comment]
I was wondering if there was a way to do it without the 'patch' file.
If I had my own fork with 100 commits, and I'd like to put those into the official repo. 
What seems logical to do is what I did: 
1) synchronize my fork from official repo 
2) create a pull request

Like this the histories both in the official repo and my repo stay compatible. 
Creating a patch does not seem to be the right thing to do.

**Comment by jtrmal** [comment]
Karel did you notice my post about the cherry-pick? These two messages were exchanged shortly after each other, so I'm not sure if you are responding to my message or Dan's.
But personally, I feel the picking the exact commit is the way to go.
I'm still confused, why the merge of the upsteam/master will show again in the commit.

**Comment by vesis84** [comment]
Yes, I try to do it your way. I must have screwed up my master by merging it twice: once through web interface and once from a command line.

**Comment by vesis84** [comment]
Now I see where the problem was. I have to synchronize my fork 'vesis84/kaldi' from 'kaldi-asr/kaldi' by 'pull->push' via 'upstream' remote, and avoid using pull request!

**Pull request closed without merging**
