### PR TITLE
minor bug fix in XconfigAffineLayer when initializing param-stddev

### PR DESCRIPTION
**Pull request by freewym**

### CODE REVIEW

**Comment by danpovey** [comment]
Hm.  That was definitely a bug.  But before I merge this, can you please test one of the TDNN+LSTM setups to see whether the performance is affected?  It's possible that this somehow improves results by making it train faster at the beginning.  [It would be catastrophic if we didn't have the renormalize layers.]

**Comment by freewym** [comment]
param-stddev in tdnn/lstm layer are correctly set I think, by not specifying it in xconfig, the c++ code would set it as 1/sqrt(input_dim). XconfigAffineLayer is not used in our current tdnn or lstm recipes. @vijayaditya please correct me if I was wrong.

**Comment by danpovey** [comment]
Yes... I just wanted you to run the LSTM+TDNN setup because it does contain
regular 'basic' layers which would be affected by this bug, and it's our
current recommended/best setup.

**Comment by freewym** [comment]
In tdnn+lstm setups we use XconfigBasicLayer, which is independent of XconfigAffineLayer. The bug was only in XconfigAffineLayer.

**Comment by danpovey** [comment]
Oh.  Are we using XconfigAffineLayer in any recipes?

**Comment by freewym** [comment]
I don't think so.

**Comment by danpovey** [comment]
OK, merging then.

**Comment by vijayaditya** [comment]
We are not using XconfigAffineLayer in any committed recipe (testing it on
newer architectures). It had been committed to the master for the sake of
completeness in the layer library.

--Vijay

**Pull request merged**
