### PR TITLE
 [egs,scripts] Fix bug in make_voxceleb1.pl

### PR DESCRIPTION
**Pull request by weichcai**
Fix train/test data split bug in make_voxceleb1.pl

### CODE REVIEW

**Comment by danpovey** [comment]
@david-ryan-snyder  or @leibny, please check.

**Comment by david-ryan-snyder** [comment]
@weichcai, what you said make sense, thanks for catching it.

The results will need to be updated. Did you happen to rerun either of the recipes (e.g., the v1 recipe or the v2 recipe)?

**Comment by david-ryan-snyder** [comment]
Also adding @entn-at for his info, since he's been working with this recipe.

**Comment by weichcai** [comment]
Not yet. I have only run a small experiments just use Voxceleb1 (rather than Voxceleb1 + Voxceleb2 in Kaldi)  as my training set. In my case, after running my own fixed script, it didn't change too much, only a little bit worse.

**Comment by david-ryan-snyder** [comment]
OK, thanks.

@danpovey, could you merge this?

I'll make a new PR to update the results.

**Pull request merged**
