### PR TITLE
simple Interpolated kneser ney LM for testing purpose

### PR DESCRIPTION
**Pull request by wantee**

### CODE REVIEW

**Comment by wantee** [comment]
Although the Check() function in the class itself could be passed, there seems still be problems, the rnnlm-example-test will crash afterwards. I will check that later.

**Comment by danpovey** [comment]
Thanks a lot!
It could be that there is a bug in rnnlm-example-test or other code that it
calls.
Or it could be some kind of failure to sum to one.

**Comment by wantee** [comment]
The crash is quite strange. When I run Check() before WriteToARPA(), it failed during nnet training: 

> LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:94) Reading \data\ section.
LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:149) Reading \1-grams: section.
LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:149) Reading \2-grams: section.
LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:149) Reading \3-grams: section.
LOG ([5.2.152-d56c2]:~RnnlmExampleCreator():rnnlm-example.cc:343) Combined 165 into 1 minibatches (0 chunks left over)
LOG ([5.2.152-d56c2]:~RnnlmExampleCreator():rnnlm-example.cc:347) Overall there were 5.06061 words per chunk; 165 chunks per minibatch.
LOG ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:116) Weight=883, objf-num=-6688.09, objf-den=-63.5558, objf=-6751.65, objf-den-exact is -60.3224
LOG ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:161) Testing the derivatives w.r.t. the nnet output [testing ProcessOutput()].
LOG ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:176) Embedding sum is 2171.85, nnet-output sum is -31458.1, smat sum is 883
LOG ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:176) Embedding sum is 2171.85, nnet-output sum is -31458.1, smat sum is 883
LOG ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:176) Embedding sum is 2171.85, nnet-output sum is -31458.1, smat sum is 883
LOG ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:187) Objf change is  [ 0.00208172 0.0101816 -0.000119688 ]
 (predicted) vs.  [ 0 0.00976562 0.00146484 ]
 (observed), when changing nnet output.
WARNING ([5.2.152-d56c2]:TestRnnlmOutput():rnnlm-example-test.cc:191) Nnet-output-deriv test failed.
ASSERTION_FAILED ([5.2.152-d56c2]:InitDefault():natural-gradient-online.cc:86) : '(num_minibatches_history_ == 0.0 || num_minibatches_history_ > 1.0) && num_minibatches_history_ < 1.0e+06' 

However, comment out the Check() function, it crash at sampler.cc:

> LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:94) Reading \data\ section.
LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:149) Reading \1-grams: section.
LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:149) Reading \2-grams: section.
LOG ([5.2.152-d56c2]:Read():arpa-file-parser.cc:149) Reading \3-grams: section.
ASSERTION_FAILED ([5.2.152-d56c2]:CheckDistribution():sampler.cc:105) : 'iter->second > 0.0 && iter->first < (iter+1)->first' 

But I'm pretty sure that all iterator used in the Check() function are const which will not change anything in the LM, and I checked  there is no difference between the output ARPAs. Also I ran with valgrind and it didn't produce any error too.

**Comment by danpovey** [comment]
I found the problem and fixed it but haven't pushed the change yet.  It was
a problem in my code where something that should have been sorted was not
sorted.

**Pull request merged**
