### PR TITLE
Nnet3 biglm decoder

### PR DESCRIPTION
**Pull request by nshmyrev**
Unified gmm-nnet3 decoder for experiments with biglm decoder.

### CODE REVIEW

**Comment by kkm000** [comment]
@nshmyrev, I'm sorry about sitting this long on your PR. I'm squeezing smaller things in my schedule, but this one seems to need a lot of focused uninterrupted work. Hoping to get it done this weekend.

**Comment by nshmyrev** [comment]
No problem, it is pretty useless in the end.

**Comment by danpovey** [comment]
@nshmyrev could you say something about the use-case of this decoder, or the problem you were trying to solve?
The issue with the biglm decoder was always that it's unexplainably slow.

**Comment by nshmyrev** [comment]
Nevermind, it is just an experiment

**Pull request closed without merging**
