### PR TITLE
Remove redundant for loop in ProcessNonemitting while push state into queue_

### PR DESCRIPTION
**Pull request by mrlittlepig**
The for loop can be removed, new state can be push in queue_ when call FindOrAddToken func

### CODE REVIEW

**Comment by danpovey** [comment]
I think this is probably not right; it looks to me like this would result in the wrong types of tokens (emitting vs. non-emitting) being processed in the wrong place.

**Comment by mrlittlepig** [comment]
Look this state in the for loop, in which Elem is added at any FindOrAddState, and tokens has also separated after emitting processing, and all added token state is been used in non-emitting processing
```
for (const Elem *e = toks_.GetList(); e != NULL;  e = e->tail) {
    StateId state = e->key;
    if (fst_->NumInputEpsilons(state) != 0)
      queue_.push_back(state);
  }
```

**Comment by mrlittlepig** [comment]
@danpovey emitting process current frame, non-emitting process next frame, so I think there is nothing wrong logically

**Comment by danpovey** [comment]
I don't understand what you are saying.  I am closing this for now, but if you manage to persuade this guy
Zhehuai Chen <chenzhehuai@foxmail.com>
that your PR is correct, I am willing to reconsider.

**Comment by mrlittlepig** [comment]
OK，Thank you

**Pull request closed without merging**
