### PR TITLE
Children speech ASR recipe for cmu_kids and cslu_kids

### PR DESCRIPTION
**Pull request by Fei00Wu**
Hi Dan.  Sorry it took me so long to fix this repo.  I added the result to local/chain/tuning/run_tdnn_1a.sh, and renamed everything with capital letters.  I also re-ran the whole recipe to make sure it works, and everything went OK.
I started this new pull request because I realized I had the cmu_dicts in some commitments of the old branch, and I guess I shouldn't push that into the kaldi master. Let me know if there is any other thing that I should fix. Thanks.

### CODE REVIEW

**Comment by danpovey** [comment]
@leibny any chance you could look through this?  Or have you already?

**Comment by leibny** [comment]
Sure, I can take a final look.

**Comment by leibny** [comment]
I have reviewed this PR. I think is ready to be merged.

**Comment by danpovey** [comment]
Thanks!!!

**Pull request merged**
