### PR TITLE
Adding --file-skip option.  This is useful for debugging.

### PR DESCRIPTION
**Pull request by luitjens**
For example when you want to run a single file in a dataset you can
combine --file-skip=X --file-limit=Y to select the exact file for
processing without having to modify the underlying dataset.

Also reformatted some areas to match style guidelines

### CODE REVIEW

**Comment by danpovey** [comment]
I don't think I want to merge this as you could easily do it by modifying the scp files.  For instance, instead of `--file-skip=10` you could replace `scp:wav.scp` with `'scp:tail -n +10 wav.scp|'`

**Comment by luitjens** [comment]
What if the input data is in a .ark and not a .scp?

**Comment by danpovey** [comment]
It's unusual to have .wav files in an archive; do you ?
Normally they would come from an scp file in at least part of the pipeline.
Also i don't really want to merge things that are primarily for your debugging.

**Comment by luitjens** [comment]
ok,  i'll revert the changes on our side and see if I can find a way to do it in the job scripts in the future.

**Pull request closed without merging**
