### PR TITLE
cleanup-gale-mandarin-scoring

### PR DESCRIPTION
**Pull request by naxingyu**
addressing #1268

### CODE REVIEW

**Comment by danpovey** [comment]
@jtrmal, can you please check this?

**Comment by jtrmal** [comment]
Those are mostly removals which are OK -- I would, however, suggest  to replace the score.sh by the link to steps/scoring/score_kaldi.sh or creating a new simple scoring script (for scoring both WER and CER) as described  inside the file  steps/scoring/score_kaldi.sh

**Comment by naxingyu** [comment]
You are right. It’s more clear. I’ve link it to score_kaldi_cer.sh

**Comment by danpovey** [comment]
@jtrmal, please merge this if you think it's OK.

**Comment by naxingyu** [comment]
Is this PR being reviewed?

**Comment by jtrmal** [comment]
I'll review it today.   I didn't notice you've updated it.
Y.

**Comment by naxingyu** [comment]
@jtrmal I'm testing this change on hkust. It should be ready to merge if the results don't get affected. I'll keep you posted.

**Comment by naxingyu** [comment]
@jtrmal score_kaldi_cer.sh does not produce same result as the local score.sh. So I keep using the local score in hkust. What do you think about this one?

**Comment by jtrmal** [comment]
Did you check what is the difference?  You can supply a custom tokenizer.
By default,  the score_cer script does not split (by character) nor filter
the non-speech events (which I believe is the correct behavior)
Y.

**Comment by naxingyu** [comment]
Yes. That is the difference. In the local scoring script, I split the words into characters. I think that makes sense because it is the character error that is being computed, not word error.

Xingyu

> 在 2016年12月28日，16:19，jtrmal <notifications@github.com> 写道：
> 
> Did you check what is the difference? You can supply a custom tokenizer.
> By default, the score_cer script does not split (by character) nor filter
> the non-speech events (which I believe is the correct behavior)
> Y.
>

**Comment by jtrmal** [comment]
Can you show us the difference in tokenization?
I'm not sure if we are talking about the same thing.  What I was saying is
that for example non-speech unit "<NOISE>" won't be split into characters.
Y.

**Comment by naxingyu** [comment]
I see. In the local script, non-speech units are filtered. That should be the difference.

Xingyu

> 在 2016年12月28日，16:41，jtrmal <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> Can you show us the difference in tokenization?
> I'm not sure if we are talking about the same thing. What I was saying is
> that for example non-speech unit "<NOISE>" won't be split into characters.
> Y.
> 
>

**Comment by jtrmal** [comment]
you can remove them by supplying the wer_filter scripts -- I think even the
score_kaldi_cer.sh supports using them
y.

**Comment by naxingyu** [comment]
Filter scripts are added. Results are the same as before now. Ready.

X.

> 在 2016年12月28日，17:30，jtrmal <notifications@github.com> 写道：
> 
> you can remove them by supplying the wer_filter scripts -- I think even the
> score_kaldi_cer.sh supports using them
> y.
> 
> On Wed, Dec 28, 2016 at 10:24 AM, Xingyu Na <notifications@github.com>
> wrote:
> 
> > I see. In the local script, non-speech units are filtered. That should be
> > the difference.
> >
> > Xingyu
> >
> > > 在 2016年12月28日，16:41，jtrmal <notifications@github.com <mailto:
> > notifications@github.com>> 写道：
> > >
> > > Can you show us the difference in tokenization?
> > > I'm not sure if we are talking about the same thing. What I was saying is
> > > that for example non-speech unit "<NOISE>" won't be split into
> > characters.
> > > Y.
> > >
> > >
> > > On Dec 28, 2016 9:37 AM, "Xingyu Na" <notifications@github.com <mailto:

**Comment by jtrmal** [comment]
THanks, merging. y.

**Pull request merged**
