### PR TITLE
[src] Hopefully make it possible to use empty FST in grammar-fst

### PR DESCRIPTION
**Pull request by danpovey**

### CODE REVIEW

**Comment by jty016** [comment]
Hmm ... still I got the same message. Looking into more

**Comment by danpovey** [comment]
Oh, wait.  I made a mistake RE how I asked you to prepare the empty FST.
Just do `fstcompile` from an empty file.

I was checking for emptiness with NumStates() == 0; the example I showed
you isn't empty in that sense.

**Comment by jty016** [comment]
changed empty FST generation script like you said and it is working perfectly now :)
`echo "" | fstcompile > empty.fst`

**Comment by jty016** [comment]
Just friendly reminder. I tested my pre-designed grammar FST by assigning empty FSTs on the all entries. With the full graph the CER was 8.5%  and with empty FSTs I got 12.8%.

**Pull request merged**
