### PR TITLE
A couple of fixes in chain model training: fix a bug in compilation (…

### PR DESCRIPTION
**Pull request by danpovey**
…leads to crash in rare circumstances); discard partial minibatches when merging egs, which was always the intention.

This commit also improves documentation for some internal code.

The only change that really requires testing and could potentially affect results is that we discard partial minibatches; this is done for speed (to avoid unnecessary recompilation).

### CODE REVIEW

**Comment by danpovey** [comment]
@GaofengCheng, do you have time to help me test this PR?  E.g. run one of your chain-model experiments with and without this PR?  It shouldn't really make any difference (other than making training a little faster), but I want to verify this before I merge it.

**Comment by GaofengCheng** [comment]
@danpovey sure, two days delay will be tolerable?

**Comment by danpovey** [comment]
yes, no problem.
@vijayaditya, this was the bug you found... it was a problem in my code,
not yours.

**Comment by vijayaditya** [comment]
OK will test it in a few hours.

Vijay

**Comment by danpovey** [comment]
You might want to first just compile nnet3-chain-train but not
nnet3-merge-egs.  The real bug only shows up when the minibatch only has 1
example in it (due to end effects), and that case no longer happens if you
update nnet3-merge-egs, as I stopped it creating partial minibatches for
now (I may re-enable partial minibatch after I finish working on "shortcut"
compilation, which will make the compilation phase much faster..

However, I did test your case myself, after compiling it myself.

Dan

**Comment by danpovey** [comment]
@GaofengCheng, have you had a chance to test this yet?

**Comment by GaofengCheng** [comment]
@danpovey being testing...just have resources

**Comment by GaofengCheng** [comment]
@danpovey using pull #1261 results:
```
%WER 39.9 | 14852 94511 | 63.7 19.5 16.9 3.6 39.9 65.0 | 0.590 | exp/sdm1/chain_cleaned/tdnn1b_sp_bi_ihmali/decode_dev/ascore_9/dev_hires_o4.ctm.filt.sys
%WER 43.9 | 13891 89977 | 59.5 21.5 19.0 3.4 43.9 66.4 | 0.561 | exp/sdm1/chain_cleaned/tdnn1b_sp_bi_ihmali/decode_eval/ascore_9/eval_hires_o4.ctm.filt.sys
```
using kaldi/master
```
%WER 39.8 | 14702 94489 | 63.8 19.1 17.1 3.6 39.8 65.9 | 0.593 | exp/sdm1/chain_cleaned/tdnnib_normal_sp_bi_ihmali/decode_dev/ascore_9/dev_hires_o4.ctm.filt.sys
%WER 44.0 | 14124 89984 | 59.4 21.3 19.3 3.4 44.0 65.2 | 0.558 | exp/sdm1/chain_cleaned/tdnnib_normal_sp_bi_ihmali/decode_eval/ascore_9/eval_hires_o4.ctm.filt.sys
```

**Comment by danpovey** [comment]
OK thanks, merging this PR.

**Pull request merged**
