### PR TITLE
Changes to Pegah's transfer learning PR

### PR DESCRIPTION
**Pull request by danpovey**
@vimalmanohar, I have not tested this, would you mind re-testing like you did last time?

### CODE REVIEW

**Comment by danpovey** [comment]
Merging.  Thanks, @pegahgh and @vimalmanohar.

**Comment by danpovey** [comment]
Hm, actually I am concerned that if I squash and merge, the authorship info will be wrong.  @pegahgh, perhaps you could merge my changes into your original PR and I can merge that?  Maybe github will get it right then.

**Comment by HyacinthJingjing** [comment]
@pegahgh Hi, recently I am reading this paper, Investigation of Transfer Learning For ASR Using LF-MMI Trained Neural Networks. I would like to consult you about some recipes mentioned in this paper,  especially on joint multi-task learning. Looking forward to your reply.

**Comment by pegahgh** [comment]
Hi, sure, you can contact me via email pegahgh@gmail.com.

**Pull request closed without merging**
