### PR TITLE
update logging to allow threshold controls

### PR DESCRIPTION
**Pull request by btiplitz**
KALDI uses KALDI_LOG when the output message is too verbose.  I've updated several places to use KALDI_VLOG... as to allows the reduction of logging messages

### CODE REVIEW

**Comment by jtrmal** [comment]
sory, the PR is empty -- see the "Files changed" card.

**Comment by btiplitz** [comment]
I just noticed that.  I'll check

**Comment by btiplitz** [comment]
Sorry I'm new to this tool.  I missed a step so changes should now be present

**Comment by danpovey** [comment]
Sorry, I don't want to merge this, those logging messages are useful enough that I'd rather have them visible by default.
If you have an application where they are a hassle, you can just keep those changes in  your repo and merge changes from master into it.

**Pull request closed without merging**
