### PR TITLE
nnet2: applied changeds in the previous commit a92cb69 (addressing Na…

### PR DESCRIPTION
**Pull request by xiaohui-zhang**
…N issues) to nnet2

### CODE REVIEW

**Comment by danpovey** [comment]
Samuel, I think the test failed because of an unrelated issue which I've since fixed in master.
If you change this commit it will re-try the test.
Can you please take this opportunity to merge the changes from the most recent commit, d240cf7, into nnet2?  I just made this.  It's just a small reorganization of some self-diagnostic code.

**Comment by xiaohui-zhang** [comment]
sure!

On Sat, Jan 2, 2016 at 6:07 AM, Daniel Povey <notifications@github.com>
wrote:

> Samuel, I think the test failed because of an unrelated issue which I've
> since fixed in master.
> If you change this commit it will re-try the test.
> Can you please take this opportunity to merge the changes from the most
> recent commit, d240cf7
> <https://github.com/kaldi-asr/kaldi/commit/d240cf78a0c158b9fc022e9e47e4b29b427d5f63>,
> into nnet2? I just made this. It's just a small reorganization of some
> self-diagnostic code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/428#issuecomment-168340800>.
>



-- 
Xiao-hui

**Comment by xiaohui-zhang** [comment]
ready

**Comment by danpovey** [comment]
Thanks!  Merging.

**Pull request merged**
