### PR TITLE
add RNNLM data preparation script for PTB

### PR DESCRIPTION
**Pull request by keli78**

### CODE REVIEW

**Comment by danpovey** [comment]
There needs to be a bit more context, e.g. a README and a run.sh explaining
how to download the data and invoke the data-prep script.

Make it so that if, say Jian Wang wanted to run it and he hadn't used PTB
before, he could very easily do it.

**Comment by keli78** [comment]
@danpovey just added the files you mentioned.

**Comment by jtrmal** [comment]
is "ptb" commonly recognized abbreviation? I see it for the first time,
actually :)
y.

**Comment by danpovey** [comment]
It's probably common enough in the NLP community.   Ke, be sure to mention
that this example is only for language modeling.  By default these 'egs'
are all for speech processing.

**Comment by keli78** [comment]
Ok, I mentioned it in the README.txt

**Comment by danpovey** [comment]
Merged.  Note to Yenda: this is just to the RNNLM branch, I'll review later, if and when we merge the RNNLM branch to master, whether it's necessary or desirable to include this example.

**Pull request merged**
