### PR TITLE
small fix to #1654

### PR DESCRIPTION
**Pull request by GaofengCheng**
1. adding command line options for the scripts
2. replacing renorm in tdnn-lstm with batchnorm, and update results

### CODE REVIEW

**Comment by danpovey** [comment]
can you resolve the conflicts please?
I'll merge to-morrow.

**Comment by danpovey** [comment]
@GaofengCheng, this still has conflicts.

**Comment by danpovey** [comment]
Maybe if you rebase against master they would disappear.  It might be because I did a squash-merge.

**Comment by GaofengCheng** [comment]
@danpovey I'm trying

**Comment by GaofengCheng** [comment]
@danpovey conflicts should be resolved

**Pull request merged**
