### PR TITLE
changed option name self-repair-scale to self-repair-scale-nonlinearit…

### PR DESCRIPTION
**Pull request by freewym**
…y for all tdnn recipes

### CODE REVIEW

**Comment by danpovey** [comment]
Vijay, merge if it looks OK.

**Comment by vijayaditya** [comment]
You made changes in the options provided tosteps/nnet3/make_jesus_configs.py , but no changes were made to that config generator. Please make these modifications.

**Comment by freewym** [comment]
OK. Fixed.

**Comment by vijayaditya** [comment]
Could you please squash the two commits.

**Comment by freewym** [comment]
Done

**Pull request merged**
