### PR TITLE
Remove sinusoid detection code and old SGMM code/scripts

### PR DESCRIPTION
**Pull request by LvHang**
@danpovey 
As your guidance, I modify something about #1315  
1) I remove the sinusoid-detection{-test}.{h,cc}  in src/feat and detect-sinusoids.cc in src/featbin and the sgmm/sgmmbin directories. At the same time, I fixed the makefile in the src/, src/feat/ and src/featbin. I try to make and "make clean; make". All goes smoothly.
2) I remove the scripts which call sgmm binaries. After generate the candidates with command "find egs -name '*sgmm*' -not -name '*sgmm2*' -print", I check each file and remove the files which call old sgmm.
3) I check whether the deleted files are called by other top scripts one by one and modify them.
Please Check it. Thanks

Best Wishes,
Hang

### CODE REVIEW

**Comment by danpovey** [comment]
Build error, check the dependencies in the Makefile:
g++-4.9: error: ../sgmm//libkaldi-sgmm.so: No such file or directory

**Comment by LvHang** [comment]
@danpovey 
Hi Dan,

I fix the bug--delete the ../sgmm//libkaldi-sgmm.so in the Makefile of decoder/.
After the update and git push. I download the newest codes from my remote repository and compile them. All passed.
Please check it. Thanks.

Best wishes,
Hang

**Comment by danpovey** [comment]
Have you grepped in all the run.sh files for 'sgmm' to see if there are commented-out invocations to the SGMM scripts that you need to delete?

**Comment by LvHang** [comment]
@danpovey 
Hi Dan,

I run the command--" find ./ -name '*run.sh*' -print | xargs grep -n 'sgmm' > info" and check the output file line by line. Now I think all in the run.sh isn't about sgmm.
In addition, I run the command--" grep -r 'sgmm' ./* " in both src/ and egs/ directories, and check all lines. I try my best to modify all of them. I hope I have fixed all about old sgmm.
Please check it. Thanks a lot.

Best wishes,
Hang

**Pull request merged**
