### PR TITLE
cuedrnnlm lattice rescoring scripts

### PR DESCRIPTION
**Pull request by rickychanhoyin**

### CODE REVIEW

**Comment by danpovey** [comment]
OK, thanks... there are a few things I'll want to see before thinking about merging this.
What kind of performance does this give and how does it compare with other RNNLM toolkits?
What is the rescroing speed?
What alternatives are there for using CUED-RNNLM, e.g. alternatives that would involve integrating with less code?
And of course it would need an example script for training and testing some script for some setup.  But that can wait till the other issues are clearer.

**Comment by rickychanhoyin** [comment]
Ah. It gave several % to 20-30% WER reduction across several different corpora over the best 4g lm I used. The Tomas Mikolov http://rnnlm.org doesn't support GPU training (right ??).

**Comment by danpovey** [comment]
OK, well it's good that the results are good.

Things that are needed, then:
  - example scripts for specific setups, including how to train it.
  - think about how to significantly reduce the amount of code that needs
to be included.
  - I'd like to know what the rescoring speed is like.

@hainan-xv, can you at least point ricky to your setup in some branch, so
he can explain to me how his stuff compares to yours?
Dan

**Comment by rickychanhoyin** [comment]
The functions printPPLInfo , calppl , calnbest in cued-rnnlm-lib.cc can be removed (and also macro.h which is a dummy file, and cued-main.cc if we only use it as lattice rescoring library). 

I would happen to see if someone can reduce the rescoring speed (if code can be optimized)

**Comment by hainan-xv** [comment]
My setup is here: https://github.com/hainan-xv/kaldi/commits/cuedrnnlm

On Sun, Jul 3, 2016 at 1:35 AM, Daniel Povey <notifications@github.com>
wrote:

> OK, well it's good that the results are good.
>
> Things that are needed, then:
> - example scripts for specific setups, including how to train it.
> - think about how to significantly reduce the amount of code that needs
> to be included.
> - I'd like to know what the rescoring speed is like.
>
> @hainan-xv, can you at least point ricky to your setup in some branch, so
> he can explain to me how his stuff compares to yours?
> Dan
>
>
> On Sat, Jul 2, 2016 at 10:30 PM, rickychanhoyin <notifications@github.com>
> wrote:
>
> > Ah. It gave several % to 20-30% WER reduction across several different
> > corpora over the best 4g lm I used. The Tomas Mikolov http://rnnlm.org
> > doesn't support GPU training (right ??).
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/kaldi-asr/kaldi/pull/879#issuecomment-230136548>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ADJVu73w4FWhXzb7ZkZ8Rk_FicAHZAl9ks5qR0kQgaJpZM4JDzc1
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/879#issuecomment-230136670>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMCDqtQiLQeNhaiV1JU4cXv0ZWr300uks5qR0o5gaJpZM4JDzc1>
> .
>



-- 
- Hainan

**Pull request closed without merging**
