### PR TITLE
WaveData::Read unspecified streams; unsupport 8 and 32 bit formats

### PR DESCRIPTION
**Pull request by kkm000**
This continues and supersedes #338 by @Minhua722.

Still missing tests, will add some over the weekend.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.
Please make this PR against the kaldi_52 branch; it will help test it more before making it official.

**Comment by kkm000** [comment]
@danpovey, do you want to cherry-pick the commits after they are merged into master into a separate branch and a PR? The structure of the branch kaldi_52 is quite complex and non-obvious, and it is divergent in respect to master.

**Comment by kkm000** [comment]
@danpovey Or do you mean just to rebase my changes onto kaldi_52 and make the PR against kaldi_52 *only*?

**Comment by kkm000** [comment]
Ah, and FWIW, #1547 is yet unmerged, so accepting this PR into master first will bring it into that open PR as well.

**Comment by kkm000** [comment]
Rebased to kaldi_52

**Comment by danpovey** [comment]
Thanks!  So this is ready to merge?

**Comment by kkm000** [comment]
Yes, please. Test only cover basic *positive* cases (expected wave data format, no malformed files etc.), but at the very least I verified that the new functionality worked.

**Comment by danpovey** [comment]
I have reverted this PR from the command line since the 'revert' button from github didn't work.

**Pull request merged**
