### PR TITLE
Add date/time info to travis script.

### PR DESCRIPTION
**Pull request by dogancan**
This is only for debugging travis. No need to merge it yet.

### CODE REVIEW

**Comment by danpovey** [comment]
Should this be merged now?

**Comment by dogancan** [comment]
No. This was for getting a fair baseline with the current master. Relevant changes from this PR are already in #1249. We can close this one.

**Comment by danpovey** [comment]
I've decided to first merge the C++11 changes into the 'shortcut' branch so that we can test them both together; otherwise we'll never find the time to properly test the C++11 upgrade.  Could you please prepare a version of the PR  that's against the shortcut branch?  There may be conflicts to resolve.  I just updated the shortcut branch after merging with master.

**Comment by dogancan** [comment]
Makes sense. What should we do about the new threading upgrade PR #1350 which will also need extensive testing? That PR is a superset of the C++11 upgrade PR #1249 for the moment since it depends on those changes.

**Comment by danpovey** [comment]
I haven't decided whether to make that part of the same version upgrade as
'shortcut' or to wait until afterward.  I'd rather test the C++11 issues
first.

**Comment by dogancan** [comment]
Ok done.

**Comment by danpovey** [comment]
thanks; will merge and test after automated checks finish.

**Pull request closed without merging**
