### PR TITLE
update fisher_swbd tdnn+smbr recipe

### PR DESCRIPTION
**Pull request by naxingyu**
Only updating the script. Result will be added after the chain smbr experiments done.

### CODE REVIEW

**Comment by danpovey** [comment]
OK thanks but I think I'll leave the PR up there until you add the results.. would rather not commit the script without its results.

**Comment by naxingyu** [comment]
OK. Results are added now.

在 2016/4/28 13:22, Daniel Povey 写道:

**Comment by danpovey** [comment]
Would you mind making this PR relative to 'master'?  I recently merged 'chain' to 'master' and I'm not convinced that we need the branch 'chain' any more.

**Comment by naxingyu** [comment]
Oh, I didn't see an 'official' statement of merging chain... OK, I'll 
re-make this PR.

在 2016/4/28 23:40, Daniel Povey 写道:

**Comment by danpovey** [comment]
It's still relative to 'chain'.   Not sure if you have to kill this PR and make a new one, or you can change it.

**Comment by naxingyu** [comment]
Leave a comment

**Comment by naxingyu** [comment]
Sorry for delay. I've created another PR.

在 2016/4/30 1:50, Daniel Povey 写道:

**Pull request closed without merging**
