### PR TITLE
[src] Log per-utt metrics in compute-wer --verbose=2

### PR DESCRIPTION
**Pull request by kkm000**
At verbose level 2, log per-utterance length, distance,
insertions, deletions and substitutions in a format that
is easy to parse out from the logs.

### CODE REVIEW

**Comment by kkm000** [comment]
Just to explain the intent, this helps me find the outliers that do much better or much worse in a decoding set w.r.t. reference counts, to gain some hints what kind of acoustics the model likes or dislikes the most, thus what kind of data to throw into the training pool.

**Comment by danpovey** [comment]
@jtrmal can you please comment on this?  Not sure if there is already another mechanism for this.  Not that that would preclude merging it necessarily.

**Comment by jtrmal** [comment]
There is definitely a way how to do it without it -- it's done in the
native scoring scripts (kaldi-score-wer.sh),  (I think the script is called
per_utt_details.pl)
y.

**Comment by kkm000** [comment]
Oh, did not know that, thanks much Yenda! Dan, I'll drop this PR myself is Yenda's suggestion cuts it for me, or comment if it does not for any reason.

**Comment by danpovey** [comment]
Thanks!  Closing for now.

**Pull request closed without merging**
