### PR TITLE
Add data preparation script for CIFAR

### PR DESCRIPTION
**Pull request by hhadian**

### CODE REVIEW

**Comment by danpovey** [comment]
Can you please start a run.sh and add a cmd.sh?

**Comment by hhadian** [comment]
Added.

**Comment by danpovey** [comment]
please fix permission on run.sh (chmod +x run.sh; git add run.sh)

**Comment by danpovey** [comment]
I got an error when running the python script (perhaps you are locally mapping python to python3?  Don't do that!
I think some of those 'description=xxx' should be 'help=xxx'
```

a04:v1: copy-feats --compress=true ark:- ark,scp:data/cifar10_train/data/images.ark,data/cifar10_train/images.scp
Traceback (most recent call last):
  File "local/process_data.py", line 25, in <module>
    description='path to downloaded cifar data (binary version)')
  File "/usr/lib/python2.7/argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'description'
LOG (copy-feats[5.1.95-fe177]:main():copy-feats.cc:143) Copied 0 feature matrices.
./run.sh: line 13: image/validate_data_dir.sh: No such file or directory
./run.sh: line 13: image/validate_data_dir.sh: No such file or directory
./run.sh: line 13: image/validate_data_dir.sh: No such file or directory
./run.sh: line 13: image/validate_data_dir.sh: No such file or directory

```

**Comment by hhadian** [comment]
I'm sorry I added those usage messages at the last minute before pushing without testing. It is fixed now.

**Comment by hhadian** [comment]
Fixed permission too. Also validate_data_dir needed permission fix, do you want me to do that too?
I have not mapped python3 to python.

**Comment by danpovey** [comment]
I'm afraid your branch has now diverged from the kaldi_52 branch.  You will probably find it easier to just start from the current kaldi_52 branch and make any remaining fixes (that I didn't make myself) manually.

**Comment by danpovey** [comment]
... and maybe close this PR and start a new PR, I merged the main points of this PR manually along with my changes.

**Comment by hhadian** [comment]
OK will do.

**Pull request closed without merging**
