### PR TITLE
Initial Web Commit

### PR DESCRIPTION
**Pull request by revdeluxe**
These Are the Initial Commits for the Website Improvement. @danpovey 
the design are 'not' final. assume to see it finish by Thursday(June 9, 2022)

> The Following Contents are just Placeholder for the Big One!.

Plans
1. Download Button When Click should Show a Pre-Compiled Packages in the <iframe> tag.
2. Same goes to Contacts.
3. Modern CSS for Pleasing Design
4. Source will make a new tab that will send the user to the github page.
5. Color Scheme No.1 (Primary: Black, Secondary:White, Accent: Orange)

Any Color Suggestions Do it now while this one is not final.

Assumes these to be posted and materialized by Thursday(June 9, 2022)
there are going to be 3 Variants for this web.

Richard

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks!
How would I see a preview of this?

**Comment by revdeluxe** [comment]
> Thanks! How would I see a preview of this?

Just Open the index.html
the buttons doesn't work yet.

**Comment by danpovey** [comment]
Sorry, I'm not sure what you mean by open here.  
Also i am not sure about this text:
```
Kaldi is Available to all major platforms such as Windows <br>
          Linux, And MacOS. it's written in C so you don't have to worry <br>
          for the performance issues.
```
... Kaldi is hard to make work on Windows, and I don't want to give people the impression it's like some kind of user software that you can just install and start using.

**Comment by revdeluxe** [comment]
> Sorry, I'm not sure what you mean by open here. Also i am not sure about this text:
> 
> ```
> Kaldi is Available to all major platforms such as Windows <br>
>           Linux, And MacOS. it's written in C so you don't have to worry <br>
>           for the performance issues.
> ```
> 
> ... Kaldi is hard to make work on Windows, and I don't want to give people the impression it's like some kind of user software that you can just install and start using.

Figures, Good thing I let you check on this. well i'll be queuing that for revision.

**Comment by danpovey** [comment]
The Kaldi project is not being very actively updated.  I was thinking that I could perhaps involve you in other projects eventually.
I suggest to not be too ambitious about changing the Kaldi webpage.
Note: there is some auto-generation involved in the Kaldi webpage, we run doxygen and ssh it to the web server machine, see src/doc/README.  I have not updated the webpage in a long time.

**Comment by revdeluxe** [comment]
> The Kaldi project is not being very actively updated. I was thinking that I could perhaps involve you in other projects eventually. I suggest to not be too ambitious about changing the Kaldi webpage. Note: there is some auto-generation involved in the Kaldi webpage, we run doxygen and ssh it to the web server machine, see src/doc/README. I have not updated the webpage in a long time.

I see. thanks for the reminder. I'll proceed designing the webpages. then when that's done i'll research a much more practical way to automate these. whatever these you want to automate.

If possible i would like to use `rust` as the parsing mechanism for the webpage. and eventually kaldi itself.

**Comment by danpovey** [comment]
This is a legacy project that has many moving parts.  I think it's wiser to make few changes; that will reduce the burden of testing.  I'm not planning to change the way the webpage uploading is done because I am very busy and have little time to test it.  Same with any big changes to the website.

If you have cool things you want to try, it would be better to do those in a different project.

**Comment by revdeluxe** [comment]
> This is a legacy project that has many moving parts. I think it's wiser to make few changes; that will reduce the burden of testing. I'm not planning to change the way the webpage uploading is done because I am very busy and have little time to test it. Same with any big changes to the website.
> 
> If you have cool things you want to try, it would be better to do those in a different project.

Those are experimental, anyways. i wont be adding them to here. plus everyone is busy. it would be wise manage our time properly.

When the time comes why not.

A ideal problem needs a realistic solution. likewise.

**Comment by kkm000** [comment]
I guess this is not going forward? I agree with Dan, it would be wasted effort.

I am closing this PR for now. If you believe that's in error, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Pull request closed without merging**
