### PR TITLE
Added Travis CI integration scripts

### PR DESCRIPTION
**Pull request by kkm000**
Added Travis CI integration scripts.
Modified makefiles so that failed tests keep their log files around, so that the CI can capture them.

See https://travis-ci.org/workflow-demo-org/kaldi/ (and https://travis-ci.org/kaldi-asr/kaldi/ after merge and first push). New PRs should automatically show a small information icon as to whether the Travis build is in progress, or has failed or succeeded.

### CODE REVIEW

**Comment by kkm000** [comment]
Ha! Already running a test!

**Comment by kkm000** [comment]
Don't merge. The failure seems genuine bug log is missing.

**Comment by kkm000** [comment]
travis-ci/travis-ci/#3754 prevents core files creation, and therefore gdb backtraces. Otherwise this works as designed. The failure in nnet-component-test is genuine, I am reproducing it locally. This is the first bug caught with the CI.

This PR is good to go by me. Please review.

**Comment by danpovey** [comment]
What does "command" in the makefile do?  `which command` on clsp returns nothing.
I'd rather not have the Makefile rely on something obscure to work, if we can  avoid id.
Dan

**Comment by jtrmal** [comment]
IIRC,  command  can be used in similar way to which.  Command should be
more correct,  as which is often hijacked by package managers.  I think
it's bash builtin.
Y.

**Comment by jtrmal** [comment]
I forgot to say I didn't look at that makefile /script so I don't know the
context exactly.
Y.

**Comment by danpovey** [comment]
BTW, I should mention that I decided now might be as good a time as any to
merge nnet3 back to master.  I can create a separate branch for ongoing
work such as CTC.  I am working on the merging right now.  Let me know if
there are any objections.

Dan

**Comment by kkm000** [comment]
`command -v` is the POSIX standard built-in, and is perhaps the most portable way to see if a command is available, as an executable in the path, or (unlike `which`) as a built-in. 
```
sh-4.3$ command -v gdb; echo $?
/usr/bin/gdb
0
sh-4.3$ command -v gdbzzz; echo $?
1
sh-4.3$ command -v echo; echo $?
echo
0
```

You should have used `command -v command` instead of `which command` to see that `command` is indeed available as a command :-)

Another common use of `command` is unaliasing. This is common e. g. in bash completion scripts, as they run in the interactive shell.
```
kkm@yupana:~$ alias ls='echo aliased away'
kkm@yupana:~$ ls -l *.txt
aliased away -l winregrate.txt
kkm@yupana:~$ command ls -l *.txt
-rw-rw-r-- 1 kkm kkm 48876 May 13 21:22 winregrate.txt
```

**Comment by danpovey** [comment]
OK thanks.
I'll merge this after I finish the nnet3 merge, though [assuming no-one
objects to that].  It's becoming a headache to have two diverging
development branches, and the nnet3 stuff itself is pretty stable now.
Dan


On Wed, Aug 19, 2015 at 3:26 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
Sure, no problem. I'll rebase if this one is reported unmergeable.

**Comment by danpovey** [comment]
Merged after checking nothing was broken.

**Pull request merged**
