### PR TITLE
Adding nnet2 function NnetComputationChunked

### PR DESCRIPTION
**Pull request by david-ryan-snyder**
Adding nnet2 function NnetComputationChunked and updating associated unit test and binary. This version of NnetComputation divides the feature matrix into smaller chunks, and performs the posterior computation chunk by chunk. This makes the computation suitable for the GPU when the feature matrices are large.

### CODE REVIEW

**Comment by naxingyu** [comment]
Cool. We should have this in nnet3 too because the progress jobs are 
running reeeally slow on CPUs in lstm setups.

**Comment by danpovey** [comment]
Actually this wouldn't help the nnet3 show-progress.  If speed is a problem
you can just make it run on GPU (i.e. change the queue options that it's
submitted with, and add --use-gpu=yes to the command line).  We don't do
this in order to not slow down the training.
Dan

**Comment by naxingyu** [comment]
I tried --use-gpu=yes option but it results in out-of-memory crash.

**Comment by danpovey** [comment]
It works fine for me.  Maybe your GPUs don't have much memory?
Dan

**Comment by naxingyu** [comment]
I'm using Tesla K20m in exclusive mode... it's not a cutting-edge 
version but should be enough.

**Comment by danpovey** [comment]
Same here.    What is the command line?
Dan

**Comment by danpovey** [comment]
You might as well show the output too.
Dan

**Comment by david-ryan-snyder** [comment]
Thanks for the merge. Should we also do something like this for the nnet3 equivalent?

**Comment by danpovey** [comment]
The nnet3 computation (IIRC) is already done in chunks.
Dan


On Thu, Sep 17, 2015 at 5:27 PM, david-ryan-snyder <notifications@github.com

**Pull request merged**
