### PR TITLE
Test

### PR DESCRIPTION
**Pull request by keli78**
Remove unnecessary null pointers in functions: DeleteTestFst, Fbank, and LangModelFst.

### CODE REVIEW

**Comment by danpovey** [comment]
You need to clean up the commit history a bit.  Vimal or Vijay should be able to help, but others may be good at git too.  I recommend to either rebase, or apply a patch to a freshly created branch.

**Comment by keli78** [comment]
I cleaned up the commit history.

**Comment by danpovey** [comment]
OK, thanks, will merge.

**Comment by danpovey** [comment]
BTW, you could look through kaldi for similar unnecessary checks prior to
deletes.

The following shell script will identify candidates for this:

for x in */*.{h,cc}; do perl -e '$ret = 1; while(<>) { if
(($last_line=~m/if/ || m/if/) && m/delete/) { print "$last_line $_"; $ret =
0; } $last_line = $_; } exit $ret; ' $x && echo $x; done

Get someone to explain to you the script if anyone is around.

Dan

**Pull request merged**
