### PR TITLE
Move CheckAndFix to config struct

### PR DESCRIPTION
**Pull request by hugovbraun**
Related to #3734

### CODE REVIEW

**Comment by hugovbraun** [comment]
First commit is just clang-format formatting to C++ coding style. The changes are in the second commit

**Comment by danpovey** [comment]
Hm, I'm OK with the main change but I don't like the clang formatting thing.  It already had a fairly consistent coding style (but different from what clang is doing), and if we were to consistently apply the clang thing everywhere it would pollute the git history and make it hard to track down meaningful changes.

**Comment by hugovbraun** [comment]
Ok, I'll revert this on this PR and the other one

**Comment by hugovbraun** [comment]
Revert done

**Comment by hugovbraun** [comment]
Testing ok

**Pull request merged**
