### PR TITLE
Added (B)LSTM scripts for ami/s5b and tedlium/s5_r2

### PR DESCRIPTION
**Pull request by freewym**
They all have been tested in my several experiments. I think it may be convenient for future experiments to merge these.

### CODE REVIEW

**Comment by vijayaditya** [comment]
Any updates to the results ?

**Comment by freewym** [comment]
I have the results. But None of them are based on the latest recipes, Some are with BackPropTruncationComponent but not deriv_time fix, some are with deriv_time fix but not BackPropTruncationComponent, although it may not make too much difference.

**Comment by vijayaditya** [comment]
Just add whatever results you have. Add a comment saying that reproducing them might not be possible due to the reasons you stated.

**Comment by GaofengCheng** [comment]
My results on AMI SDM1 using chain blstm:
`# local/chain/run_blstm_6i.sh --mic sdm1 --use-ihm-ali true`
```
%WER 39.9 | 14731 94514 | 65.0 21.8 13.3 4.8 39.9 65.6 | 0.629 | dev_hires_o4.ctm.filt.sys
%WER 43.3 | 13377 89980 | 60.5 21.7 17.8 3.8 43.3 68.3 | 0.567 | eval_hires_o4.ctm.filt.sys
```
below is chain TDNN results I got:
`# local/chain/run_tdnn.sh --mic sdm1 --use-ihm-ali true `
```
%WER 40.6 | 14131 94507 | 62.9 19.3 17.7 3.6 40.6 68.5 | 0.595 | dev_hires_o4.ctm.filt.sys
%WER 44.5 | 13081 89986 | 58.9 21.2 19.9 3.4 44.5 70.4 | 0.565 | eval_hires_o4.ctm.filt.sys
```
here is chain TDNN from AMI RESULTS_SDM:

```
# local/chain/run_tdnn.sh --mic sdm1 --use-ihm-ali true --stage 12 &
# cleanup + chain TDNN model, cleaned data and alignments from ihm data.
# for d in exp/sdm1/chain_cleaned/tdnn_sp_bi_ihmali/decode_*; do grep Sum $d/*sc*/*ys | utils/best_wer.sh; done
%WER 40.7 | 14321 94501 | 63.0 19.6 17.4 3.7 40.7 67.7 | 0.592 | exp/sdm1/chain_cleaned/tdnn_sp_bi_ihmali/decode_dev/ascore_9/dev_hires_o4.ctm.filt.sys
%WER 44.8 | 14293 89976 | 58.6 21.3 20.1 3.3 44.8 64.2 | 0.559 | exp/sdm1/chain_cleaned/tdnn_sp_bi_ihmali/decode_eval/ascore_9/eval_hires_o4.ctm.filt.sys
```
I used 3-layer 1024-128-128(ClipGradientComponent),and @freewym  got the results on 3-layer 512-128-128. It seems I have to try wang's config.

**Comment by GaofengCheng** [comment]
I just runs for 4 epoch for chain blstm, and @freewym  runs for 10 epochs........

**Comment by freewym** [comment]
chain model usually needs less epochs than xent model. You could decide if you need more epochs based on train/valid plots

**Pull request merged**
