### PR TITLE
Kaldi to work whether python is python2 or python3.

### PR DESCRIPTION
**Pull request by hajime9652**
#3918

### CODE REVIEW

**Comment by danpovey** [comment]
This is still  not right.  I told you what was needed: your ORIGINAL PATCH plus change `python` at line 113 (IIRC) to `python3`.  I don't have time to explain why that is what's needed, but it is.

**Comment by hajime9652** [comment]
Can you please make sure that everything is correct?

**Comment by danpovey** [comment]
good now, thanks!

**Comment by hajime9652** [comment]
Thank you for your support as ever.

**Pull request merged**
