### PR TITLE
GigaSpeech recipe

### PR DESCRIPTION
**Pull request by chenguoguo**
The scripts are not in a great state, but they were what we used for the paper.  @wangyongqing0731 created the first draft and I made some modifications. It's likely that you'll want us to make some changes. Let us know, and we'll improve accordingly.

### CODE REVIEW

**Review by danpovey — COMMENTED** [review]
I notice README.txt is an empty file.
Sorry I don't have time for detailed review of this right now, but I'm OK to merge with not much review.

**Comment by jtrmal** [comment]
I promised Guoguo to have a look at it next week, after my vacation. I'm ok
wth merging now, fixing later.
y.

**Comment by danpovey** [comment]
OK let's merge now.  I doubt there are major issues.

**Comment by chenguoguo** [comment]
Thanks! I'll address Yenda's comments when he add them. Will also add the README.txt file.

**Pull request merged**
