### PR TITLE
[WIP] Semi-supervised training using chain models

### PR DESCRIPTION
**Pull request by vimalmanohar**

### CODE REVIEW

**Comment by danpovey** [comment]
Vimal, I assume you are putting this up here for reference, and not as an
actual pull request to be merged?  Because as with all your pull requests,
it seems to contain a lot of stuff which shouldn't be merged.  E.g. a bunch
of tuning experiements; confidence calibration stuff which I thought we
agreed not to include in the final recipe.

**Comment by vimalmanohar** [comment]
Yes. This is for @hhadian to see the changes. I will move this to my repository.

**Comment by danpovey** [comment]
OK to leave it here-- I was just checking.  When you do make the real
thing, I want it to be *clean*!

**Comment by vimalmanohar** [comment]
Moved to https://github.com/vimalmanohar/kaldi/pull/13. There is already one more PR for this.

**Pull request closed without merging**
