### PR TITLE
[WIP] Ivector for image recognition 

### PR DESCRIPTION
**Pull request by aarora8**
Adding option for using ivector in fully connected layer after cnn.
modifications in xconfig file to also consider ivector
fix in extract patches code
[wip] adding code to append ivector after each pixel.
@hhadian

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.  @hhadian, I'll look at this if you tell me it's a candidate for merge-- I'm not sure if this is giving improvements on our best recipes?  I'm sure there are plenty of issues that would need to be fixed but I'll rely on you to do a first pass through it.

**Comment by hhadian** [comment]
Sure I'll do a first review. This is not for merge yet. This is mostly for review and to make sure @aarora8 is doing the experiments right.
Ashish, I can see a few unrelated commits. Maybe you could rebase against kaldi/master to get rid of them.
Also, did you try recipe 1e with ivectors again after you fixed "extract-patches"?

**Comment by aarora8** [comment]
ok, I will rebase with kaldi/master. I did the experiments with reciepe 1e and 1a, recognition accuracy is as follows: 

For 1a:
With pervious Ivector: train/valid[39,59,final]=(0.955,0.9996,1.0000/0.70,0.69,0.69)
with new extract patches code train/valid[39,59,final]=(0.975,0.9998,1.0000/0.72,0.71,0.71)

For 1e:
With pervious Ivector:train/valid[39,59,final]=(0.977,0.9992,0.9994/0.817,0.834,0.836)
with new extract patches code train/valid[39,59,final]=(0.9906,0.9996,0.9994/0.825,0.832,0.833)

**Comment by danpovey** [comment]
You are not giving enough details.  1a/1e of which type of network
(cnn/resnet) for which dataset?    Giving the script name would make it
cleaer.
Anyway it looks like on the better system it is not really working.

**Comment by aarora8** [comment]
I am sorry, experiments were done for the reciepe run_cnn_1a.sh and run_cnn_1e.sh with cifar dataset.

**Comment by david-ryan-snyder** [comment]
@aarora8, @hhadian, did you guys find that this doesn't help? If so, maybe this PR should be closed or marked as "stopped development."

**Pull request closed without merging**
