### PR TITLE
add read/write cache opt to train_rnn.py and fix cache read bug

### PR DESCRIPTION
**Pull request by lifeiteng**
size_t type caused `ReadBasicType: did not get expected integer type` error

### CODE REVIEW

**Comment by danpovey** [comment]
makes sense, but can you please rebase your changes against master?  I don't like committing merges like this.  If you don't know how, I can ask someone else to do it.

**Comment by danpovey** [comment]
.. or if you don't know how to rebase, just create a patch against master and apply it, abandoning your history, so I can have a single squashed commit.

**Comment by lifeiteng** [comment]
done

**Comment by danpovey** [comment]
Thanks!  Merging.

**Pull request merged**
