### PR TITLE
fixes #849

### LINKED ISSUE #849: Unexpected character } encountered while error
With latest update and nnet training the following error is dumped in the logs

```
LOG (nnet3-am-copy:main():nnet3-am-copy.cc:118) Copied neural net from exp/chain/131.mdl to raw format as -
ERROR (nnet3-chain-train:ReadIndexVectorElementBinary():nnet-common.cc:110) Unexpected character } encountered while reading Index vect

[ Stack-Trace: ]
nnet3-chain-train() [0xc2f024]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
nnet3-chain-train() [0x8af81f]
kaldi::nnet3::ReadIndexVector(std::istream&, bool, std::vector<kaldi::nnet3::Index, std::allocator<kaldi::nnet3::Index> >*)
kaldi::nnet3::IoSpecification::Read(std::istream&, bool)
kaldi::nnet3::ComputationRequest::Read(std::istream&, bool)
kaldi::nnet3::CachingOptimizingCompiler::ReadCache(std::istream&, bool)
kaldi::nnet3::NnetChainTrainer::NnetChainTrainer(kaldi::nnet3::NnetChainTrainingOptions const&, fst::VectorFst<fst::ArcTpl<fst::Tropica
main
__libc_start_main
nnet3-chain-train() [0x8479d9]
WARNING (nnet3-chain-train:NnetChainTrainer():nnet-chain-training.cc:55) Could not open cached computation. Probably this is the first
```

### PR DESCRIPTION
**Pull request by xiaohui-zhang**

### CODE REVIEW

**Comment by danpovey** [comment]
So is the computation-cache not readable by Kaldi if written in non-binary mode?  Is this by design?  If so should it be stated somewhere?

**Comment by xiaohui-zhang** [comment]
hmm no. It's still readable. I set it to true to save space. Should I
change it to false?

On Mon, Jun 20, 2016 at 4:57 PM, Daniel Povey <notifications@github.com>
wrote:

> So is the computation-cache not readable by Kaldi if written in non-binary
> mode? Is this by design? If so should it be stated somewhere?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/855#issuecomment-227267219>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANiEEb3-c4eTsFQj4XjWyxnfYdB-yTRVks5qNv7BgaJpZM4I6HBI>
> .
>



-- 
Xiao-hui

**Comment by danpovey** [comment]
Setting it to true is good.  But I don't understand why this would fix the
error in question, unless the text-form computation cache was unreadable.
Dan

**Comment by danpovey** [comment]
Merged- it looks like an uninitialized bool in C++ may sometimes behave as true and sometimes as false, depending whether you access it as if (b) or if (!b).

**Pull request merged**
