### PR TITLE
steps/cleanup : Added a new version of the combine_short_segments script

### PR DESCRIPTION
**Pull request by vijayaditya**

### CODE REVIEW

**Comment by danpovey** [comment]
Don't you need this in chain?  Should I merge from master to chain after this?

**Comment by danpovey** [comment]
And wouldn't you need to also change all invocations of this script, since the suffix changed?

**Comment by vijayaditya** [comment]
I didn't think this was ever used. Let me check.

**Comment by danpovey** [comment]
OK, you can merge it yourself after you've checked, just bear in mind that
it may be necessary to merge changes from master to chain if you need it in
chain.

**Comment by vijayaditya** [comment]
Modified one invocation of the script. Merging for now as this is not used much and it is necessary for running AMI experiments immediately.

**Pull request merged**
