### PR TITLE
updating librispeech recipe

### PR DESCRIPTION
**Pull request by jonlnichols**
with fixes from https://groups.google.com/forum/embed/?place=forum/kaldi-help&showsearch=true&showpopout=true&parenturl=http%3A%2F%2Fkaldi-asr.org%2Fforums.html#!topic/kaldi-help/002wjyUFk9A

### CODE REVIEW

**Comment by danpovey** [comment]
This looks good, but could you please put the WER results?  In this recipe they are in the RESULTS file, serach for exp/chain_cleaned/tdnn_sp.
I may ask you to tune it a bit if they are worse-- the configuration is not identical to the original one, although it's close.

**Comment by jonlnichols** [comment]
i can post it if you want, but i had an additional change in the model i
had made which likely made the WER a bit worse for my model. i had
converted it to 8k sample rates, while the base recipe uses 16k

**Comment by danpovey** [comment]
@LvHang, would you mind running the script in this PR and getting the results?

**Comment by LvHang** [comment]
Sure, I will do it.

**Comment by LvHang** [comment]
Hi Dan,
This is the results of the new recipe:
```
%WER 3.84 [ 2091 / 54402, 261 ins, 198 del, 1632 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_clean_fglarge/wer_11_0.5
%WER 4.00 [ 2176 / 54402, 258 ins, 220 del, 1698 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_clean_tglarge/wer_11_0.5
%WER 5.16 [ 2807 / 54402, 290 ins, 318 del, 2199 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_clean_tgmed/wer_10_0.5
%WER 5.80 [ 3154 / 54402, 346 ins, 319 del, 2489 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_clean_tgsmall/wer_10_0.0
%WER 10.15 [ 5169 / 50948, 658 ins, 570 del, 3941 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_other_fglarge/wer_13_0.0
%WER 10.78 [ 5493 / 50948, 712 ins, 617 del, 4164 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_other_tglarge/wer_12_0.0
%WER 13.09 [ 6668 / 50948, 714 ins, 884 del, 5070 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_other_tgmed/wer_12_0.0
%WER 14.61 [ 7442 / 50948, 695 ins, 1074 del, 5673 sub ] exp/chain_cleaned/tdnn_sp/decode_dev_other_tgsmall/wer_12_0.0
%WER 4.38 [ 2303 / 52576, 324 ins, 210 del, 1769 sub ] exp/chain_cleaned/tdnn_sp/decode_test_clean_fglarge/wer_11_0.5
%WER 4.58 [ 2408 / 52576, 327 ins, 246 del, 1835 sub ] exp/chain_cleaned/tdnn_sp/decode_test_clean_tglarge/wer_11_0.5
%WER 5.54 [ 2915 / 52576, 395 ins, 270 del, 2250 sub ] exp/chain_cleaned/tdnn_sp/decode_test_clean_tgmed/wer_10_0.0
%WER 6.15 [ 3231 / 52576, 373 ins, 365 del, 2493 sub ] exp/chain_cleaned/tdnn_sp/decode_test_clean_tgsmall/wer_11_0.0
%WER 10.64 [ 5569 / 52343, 737 ins, 568 del, 4264 sub ] exp/chain_cleaned/tdnn_sp/decode_test_other_fglarge/wer_12_0.0
%WER 11.13 [ 5825 / 52343, 740 ins, 635 del, 4450 sub ] exp/chain_cleaned/tdnn_sp/decode_test_other_tglarge/wer_13_0.0
%WER 13.45 [ 7039 / 52343, 709 ins, 976 del, 5354 sub ] exp/chain_cleaned/tdnn_sp/decode_test_other_tgmed/wer_13_0.0
%WER 14.92 [ 7808 / 52343, 727 ins, 1113 del, 5968 sub ] exp/chain_cleaned/tdnn_sp/decode_test_other_tgsmall/wer_12_0.0
```

Bests,
Hang

**Comment by danpovey** [comment]
so how does that compare with what's currently in the RESULTS file?  And
are you going to update the RESULTS file in the PR?

**Comment by LvHang** [comment]
Hi Dan,

|                      |   dev_clean     |   dev_other    |   test_celan    | test_other |
|---------------|----------------|----------------|----------------|------------|
|old_fglarge	|3.87	|10.22	|4.17	|10.62|
|new_fglarge	|3.84	|10.15	|4.38	|10.64|
|old_tglarge	|3.97	|10.79	|4.36	|10.96|
|new_tglarge	|4	|10.78	|4.58	|11.13|
|old_tgmed	|4.95	|13.01	|5.33	|13.24|
|new_tgmed	|5.16	|13.09	|5.54	|13.45|
|old_tgsmall	|5.57	|14.36	|5.93	|14.53|
|new_tgsmall	|5.8	|14.61	|6.15	|14.92|

The rows with "old" prefix means the results in "RESULT" file. And the rows with "new" prefix means the new results.
It seems that the new results are a little bit worse than the old ones. But I think it might be randomness.
What are you thinking about it?

I think this PR belongs to "jonlnichols". Can I also update it?

Hang

**Comment by danpovey** [comment]
To update it you'd have to clone his branch and make your own PR.
Can you try running a version which has one fewer of the lines like:
`relu-batchnorm-layer name=tdnn2 dim=512 input=Append(-1,0,1)`

**Comment by LvHang** [comment]
Ok, I will run the new test.

I think jonlnichols use the new recipe instead of the old version directly. So maybe I will delete the old results in "RESULT" file and add the new ones. Or we can keep the old recipe in tuning directory and just add the new results in "RESULT" file. Which one do you prefer?
Hang

**Comment by danpovey** [comment]
Moving to a tuning-directory type of setup would be a good thing.  In that
case the TDNN results should probably be removed from the results file and
a note should be put there that asks the user to look in the appropriate
directory.

**Comment by LvHang** [comment]
Hi Dan,
The following is newest results.
"1a" means the original recipe. "1b" means jonlnichols's recipe with xconfigs. "1c" and "1b" are very similar, but "1c" is one line fewer than "1b" [`relu-batchnorm-layer name=tdnn2 dim=512 input=Append(-1,0,1)`]

|System	                   |1a        |1b	   |1c      |
|-----------------------|--------|--------|------|
|dev_clean(fglarge)	|3.87	|3.84	|3.89|
|dev_clean(tglarge)	|3.97	|4	|4.09|
|dev_clean(tgmed)	|4.95	|5.16	|5.17|
|dev_clean(tgsmall)	|5.57	|5.8	|5.81|
|dev_other(fglarge)	|10.22	|10.15	|10.24|
|dev_other(tglarge)	|10.79	|10.78	|10.87|
|dev_other(tgmed)	|13.01	|13.09	|13.23|
|dev_other(tgsmall)	|14.36	|14.61	|14.63|
|test_celan(fglarge)	|4.17	|4.38	|4.41|
|test_celan(tglarge)	|4.36	|4.58	|4.54|
|test_celan(tgmed)	|5.33	|5.54	|5.56|
|test_celan(tgsmall)	|5.93	|6.15	|6.21|
|test_other(fglarge)	|10.62	|10.64	|10.62|
|test_other(tglarge)	|10.96	|11.13	|11.2|
|test_other(tgmed)	|13.24	|13.45	|13.64|
|test_other(tgsmall)	|14.53	|14.92	|15|

From the results, I think "1c" is a little bit worse than "1b". The gap between them is less than 1%.
Hang

**Comment by danpovey** [comment]
Try this instead:

```
fixed-affine-layer name=lda input=Append(-1,0,1,ReplaceIndex(ivector, t,
0)) affine-transform-file=$dir/configs/lda.mat
relu-batchnorm-layer name=tdnn1 dim=512 input=Append(-1,0,1,2)
relu-batchnorm-layer name=tdnn2 dim=512 input=Append(-3,0,3)
relu-batchnorm-layer name=tdnn3 dim=512 input=Append(-3,0,3)
relu-batchnorm-layer name=tdnn4 dim=512 input=Append(-3,0,3)
relu-batchnorm-layer name=tdnn5 dim=512 input=Append(-6,-3,0)
```
.. and later on in the config, replace tdnn6 with tdnn5.

**Comment by LvHang** [comment]
Ok, get it.

**Comment by danpovey** [comment]
Addressed in #1727

**Pull request closed without merging**
