### PR TITLE
gitignore: add openfst 1.4.1

### PR DESCRIPTION
**Pull request by amitbeka**
Signed-off-by: Amit Beka <amit.beka@gmail.com>

### CODE REVIEW

**Comment by jtrmal** [comment]
Github repository is read-only. You should direct the patches directly to me (jtrmal@gmail.com), or to kaldi-developers@sourceforge.net

**Comment by kkm000** [comment]
@jtrmal: I do not know if it will prove extra work for you, but a PR is looking good, you can apply it in a single command. Just add the .diff extension to any commit or PR URL, and GitHub generates a diff from it. Try https://github.com/kaldi-asr/kaldi/pull/1.diff for this very request. :-)

In fact, I just did a couple minutes ago, from a clean sandbox' root

```sh
wget -qO- http://github.com/kaldi-asr/kaldi/commit/bba05342fa937371a8892eacd162941b83eac42a.diff | patch -p1
```

**Comment by jtrmal** [comment]
Interesting, but confusing -- I though I have already applied this patch a while ago. Let me check.
y.

**Comment by kkm000** [comment]
@jtrmal, I was talking about the process in general, not this particular patch. Sorry I have been unclear. What I meant was you can get the patch right off GitHub instead of directing the user to send it to you, and that is perhaps even easier.

**Comment by jtrmal** [comment]
Oh, I understand now. Thanks for making me realize this -- I saw the links
but it didn't occur to me to try it. Really fancy :)

**Comment by amitbeka** [comment]
As an infrequent contributor to projects I find the github model easy to work with, and I think it will enable more small patches like this to be pushed, if github will be used.

**Comment by kkm000** [comment]
@amitbeka I am totally with you. Hope kaldi transitions soon : )

On the other hand, the guys are extremely--and I mean extremely extremely busy with the core speech recognition problems, and if you asked me about the priorities, I would rate the github transition somewhat lower.

**Comment by jtrmal** [comment]
Well, @amitbeka, feel free to use the git even now -- there is nothing
wrong with that. And if you are planning to submit the pull requests, the
svn "in the background" does not really affect you in any way :)
I myself am doing portion of the devleopment in github, just to get to
familiarize with it.
y.

**Comment by amitbeka** [comment]
Thanks!

**Pull request closed without merging**
