### PR TITLE
Fix building nnet3bin.

### LINKED ISSUE #4748: Meet an error when making /src
I am a starter for kaldi and was installing kaldi on my virtual machine with ubuntu-20.04.2.0 system and met an error when making the /src. The report is 

image

(没有那个文件或目录 = no such file or dictionary, 错误 = error)

It seems like I am lack of a file called libkaldi-online2.so, but I searched it and cannot find it anywhere in my virtual machine. I followed the instructions written in INSTALL documents, everything went fine until this error was raised. What should I do to deal with this? Thanks for everyone who helps me.

### PR DESCRIPTION
**Pull request by csukuangfj**
Fixes #4748

Also fixes part of #4743 (https://github.com/kaldi-asr/kaldi/issues/4743#issuecomment-1133823013)

### CODE REVIEW

**Comment by jtrmal** [comment]
Thanks! I have no idea why it worked for me without the dependency.

**Comment by csukuangfj** [comment]
> Thanks! I have no idea why it worked for me without the dependency.

Do you run `make clean`?

**Comment by jtrmal** [comment]
yeah, I did. Also with cuda on linux and without cuda on mac :/

**Comment by csukuangfj** [comment]
Ok, it's odd, even the CI did not complain.

**Pull request merged**
