### PR TITLE
cuedrnnlm N-best rescoring script 

### PR DESCRIPTION
**Pull request by rickychanhoyin**
N-best rescoring script along with the scripts in #879

### CODE REVIEW

**Comment by danpovey** [comment]
Ricky, I'm a little confused by you producing all these separate pull requests.  This isn't really how it's done.  You create one branch for the feature (in this case, the CUED RNNLM rescoring), and you make a single pull request.

Also, what I mean by "example scripts" is not the scripts in steps/ (although those are necessary too).  I mean scripts for specific setups, with bits in local/ and calls (or commented calls) in run.sh, that show how to use it for specific example scripts.

**Comment by rickychanhoyin** [comment]
ic...... I didn't familiar with this

**Comment by danpovey** [comment]
@rickychanhoyin, these pull requests are going to be up here for a while because Hainan has to do quite a bit of work on this.  I'm not very happy with having 5 different pull requests for the same feature, as they clutter up the 'issues' page.  Is it possible for you to provide one pull request that contains all the files associated with the feature, and delete the rest?

**Comment by danpovey** [comment]
@hainan-xv, since Ricky is not responding on this, do you think you could create a branch of your own where you collect together the various files that Ricky has in his pull requests, then create your own pull request marked WIP, and we can delete his pull requests?

**Comment by hainan-xv** [comment]
Oh actually I have been working on debugging my own RNNLM implementation in
the past days.

Do you want me to stop debugging mine and work on his implementation
instead?

On Wed, Jul 13, 2016 at 4:34 PM, Daniel Povey <notifications@github.com>
wrote:

> @hainan-xv <https://github.com/hainan-xv>, since Ricky is not responding
> on this, do you think you could create a branch of your own where you
> collect together the various files that Ricky has in his pull requests,
> then create your own pull request marked WIP, and we can delete his pull
> requests?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/880#issuecomment-232478307>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMCDtWajYKLgZX08-o5PlaQdb25K_A3ks5qVUvhgaJpZM4JDz9k>
> .
>



-- 
- Hainan

**Comment by danpovey** [comment]
No, I just want you to clean up his pull requests by merging them into a
single PR based in your own repo, so we can delete those duplicate pull
requests.
And obviously you'll eventually have to compare your implementation with
his for speed, accuracy, etc., and see if there are any compatibility
issues with newer versions of the CUED-RNNLM tool.
Dan

**Comment by hainan-xv** [comment]
Okay got it. I will work on this.

On Wednesday, July 13, 2016, Daniel Povey <notifications@github.com> wrote:

> No, I just want you to clean up his pull requests by merging them into a
> single PR based in your own repo, so we can delete those duplicate pull
> requests.
> And obviously you'll eventually have to compare your implementation with
> his for speed, accuracy, etc., and see if there are any compatibility
> issues with newer versions of the CUED-RNNLM tool.
> Dan
>
>
> On Wed, Jul 13, 2016 at 1:38 PM, hainan-xv <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Oh actually I have been working on debugging my own RNNLM implementation
> in
> > the past days.
> >
> > Do you want me to stop debugging mine and work on his implementation
> > instead?
> >
> > On Wed, Jul 13, 2016 at 4:34 PM, Daniel Povey <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > @hainan-xv <https://github.com/hainan-xv>, since Ricky is not
> responding
> > > on this, do you think you could create a branch of your own where you
> > > collect together the various files that Ricky has in his pull requests,
> > > then create your own pull request marked WIP, and we can delete his
> pull
> > > requests?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/kaldi-asr/kaldi/pull/880#issuecomment-232478307>,
> > or mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AFMCDtWajYKLgZX08-o5PlaQdb25K_A3ks5qVUvhgaJpZM4JDz9k
> > >
> > > .
> > >
> >
> >
> >
> > --
> > - Hainan
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/kaldi-asr/kaldi/pull/880#issuecomment-232479262>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ADJVu0d0h-yc4GNcZ8y4yf_KLpJLQs0Aks5qVUywgaJpZM4JDz9k
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/880#issuecomment-232480091>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMCDql7PSVRi0AIkAusMlGmiFpvXmhGks5qVU1-gaJpZM4JDz9k>
> .
>


-- 
Sent from Gmail Mobile

**Pull request closed without merging**
