### PR TITLE
update Maxout GPU-CPU and test code

### PR DESCRIPTION
**Pull request by naxingyu**
Squashed the the previous pull request.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks a lot.  @chenguoguo, could you please just double-check that this compiles for you and corresponds to what you previously OK'ed?

**Comment by chenguoguo** [comment]
Is there a quick way to apply the change to my local repository (I'm not quite familiar with git)? I went through the code again and it looks fine to me. But I wanted to test it on my local repository before approving on it.

Guoguo

**Comment by vdp** [comment]
I'm not a GitHub expert either, but I think you can do as follows.

Sync your local copy of the  "master" branch:

    git checkout master
    git pull origin master
    (assuming you have the official kaldi repo as 'origin')

Create a temporary test branch, as a copy of master:

    git checkout -b test-maxout

Fetch the pull request branch(or whatever they call it), and check it out into a local branch called "maxout":
   
    git fetch origin pull/30/head:maxout
    (in this case 30 is the PR's ID)
    
Merge Xingyu's changes into the test branch:

    git merge maxout

Optionally clean up after you are done testing

    git checkout master
    git branch -D maxout
    git branch -D test-maxout

**Comment by danpovey** [comment]
There seem to be instructions here
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by chenguoguo** [comment]
I tested the code and I think it's good to commit.

**Pull request merged**
