### PR TITLE
remove (dash) from default  uterance suffix from augment_data_dir.py

### PR DESCRIPTION
**Pull request by rezame**
remove − (dash) from default utterance suffix. in this code if set --utt-suffix " " add a dash - to end of utt.
(must change SRE16 run.sh based of this.)

### CODE REVIEW

**Comment by danpovey** [comment]
@phanisankar-nidadavolu and @david-ryan-snyder  please check this.

**Comment by danpovey** [comment]
@phanisankar-nidadavolu can you comment on this?

**Comment by david-ryan-snyder** [comment]
I think it's pretty standard to use "-" as the delimiter in Kaldi. And changing this would require updating 3 speaker recognition recipes.

I don't think this change is needed in the main branch.

**Comment by danpovey** [comment]
OK, closing.  Thanks for the PR though.

**Pull request closed without merging**
