### PR TITLE
chain_smbr_fix: Fixed modify learning rates binary

### PR DESCRIPTION
**Pull request by vimalmanohar**

### CODE REVIEW

**Comment by danpovey** [comment]
@vimalmanohar, have we determined that we don't need the modify-learning-rates code for nnet3 discriminative training, and so we can delete that code, and corresponding parts of the scripts, entirely?

**Comment by vimalmanohar** [comment]
It made no difference in switchboard. But it was not checked in other setups.

**Comment by danpovey** [comment]
Could you please check on some other setup?  That should be enough to
decide that we can just remove this code.  I'd like to be able to get rid
of this issue.

**Comment by danpovey** [comment]
@vimalmanohar, did you check this on another setup?

**Comment by vimalmanohar** [comment]
Sorry, I haven't done this yet. I'll run the experiment soon.

On Wed, May 18, 2016, 18:34 Daniel Povey <notifications@github.com> wrote:

> @vimalmanohar <https://github.com/vimalmanohar>, did you check this on
> another setup?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/662#issuecomment-220178279>
>
-- 
Vimal Manohar
PhD Student
Electrical & Computer Engineering
Johns Hopkins University

**Comment by danpovey** [comment]
@vimalmanohar, did you run that experiment?

**Comment by vimalmanohar** [comment]
Yes, it makes no difference in Tedlium as well for chain models.

**Comment by danpovey** [comment]
OK-- can you please remove that binary from the repo and the Makefile, and
make sure it's not referred to in any script (python or shell)?
If the command-line args to scripts are there and are used in any example
scripts, you may have to keep them for now, but state that they are
deprecated in the message.
Dan

**Comment by vimalmanohar** [comment]
Created new PR #822

**Pull request closed without merging**
