### PR TITLE
fix bug in kws_search.sh for writing results 

### PR DESCRIPTION
**Pull request by thoshith-s**
results file are in gzip format. Unzip is required before doing operations on those files.

### CODE REVIEW

**Comment by danpovey** [comment]
Merged but you should probably be using the more recent babel recipes (e.g. s5d).

**Comment by jtrmal** [comment]
I agree -- please use s5d
y.

**Comment by thoshith-s** [comment]
@jtrmal Thanks sure will do. But these bugs are common among all the babel recipes which I've mentioned in pr #3951.

**Comment by jtrmal** [comment]
That might be true, even though I think some of them might be fixed. But it
would be better to fix the latest version of the scripts anyway.
y.

**Comment by thoshith-s** [comment]
I've even updated latest version including s5d, which also includes the above bugs.

**Comment by jtrmal** [comment]
Oh, great, I'll try to find time this week.
Y.

**Pull request merged**
