### PR TITLE
[WIP] Add support for unconstrained-egs for chain training + example recipes

### PR DESCRIPTION
**Pull request by hhadian**
This adds a few scripts (with results) which use unconstrained-egs (in PR #2341).

### CODE REVIEW

**Comment by danpovey** [comment]
Cool.
I'll merge this soon.

**Comment by danpovey** [comment]
Looks like the test code doesn't compile-- my branch has the same issue.  Can you please address that?

**Comment by francisr** [comment]
I haven't followed closely the whole thing, but it seemed to me that the time constraint was found to be useful when LF-MMI was first made, why is it better without it now?

**Comment by hhadian** [comment]
The time constraints are still used but indirectly, i.e. we can still change left/right tolerance but they are less likely to make a difference, I guess. The supervision FSTs are converted to unconstrained FSTs (i.e. e2e-style) only after time constraints are applied and after they are split up into chunks.

**Comment by danpovey** [comment]
If you can quickly add any tests, e.g. that the I/O works, then do it.  Just don't make it a blocker.

**Pull request merged**
