### PR TITLE
WIP: Refactor the path.sh structure

### PR DESCRIPTION
**Pull request by jtrmal**
I modified only a handful of the recipes for review of the proposed concept

### CODE REVIEW

**Comment by jtrmal** [comment]
@danpovey  shall I proceed with modifiing the rest of the path.sh files, or is here anything that should be changed?
I'm considering to test the presence of the file $KALDI_ROOT/src/path.sh prior sourcing, for example

**Comment by danpovey** [comment]
Looks OK to me but make sure it works e.g. that you can run the commands.
Merge yourself.

**Comment by danpovey** [comment]
Yes, go ahead- looks good.
You could try '|| exit 1' while sourcing it- that would work as a test.
Dan

**Comment by jtrmal** [comment]
OK, thanks. I tried running rm recipe and it went past a few mono
iterations. After finishing the changes, I'll run the full recipe.
y.

**Comment by danpovey** [comment]
Probably what you've done is enough testing- we'll get reports if something
fails
Dan

**Pull request merged**
