### PR TITLE
update Maxout GPU implementation

### PR DESCRIPTION
**Pull request by naxingyu**
I add the Maxout implementation on both GPU and CPU, and updated the Maxout component in nnet2.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks,
Guoguo, can you please do code review on this patch?
Dan

**Comment by danpovey** [comment]
I'll do this tomorrow (Internet connection is very weak for me right now).

Guoguo
--

**Comment by jtrmal** [comment]
I  have a small suggestion -- it would be good if there was a test contributed as well.
I.e. calculating the MaxOut several times for different dimensions and compare against the CPU implementation, possibly including some timing info.
y.

**Comment by naxingyu** [comment]
You are right. I'll finish the test code today.

**Comment by chenguoguo** [comment]
Hi Xingyu,

I went through the patch (sorry for keeping you waiting, I was a bit busy with other stuff the past few days...), the code looks plausible. Since you've added the CPU version of those functions, it might be a good idea to add test code for that as well. I also have some small style wise suggestions below:

Here:
cuda_calc_max_deriv(dimGrid, dimBlock, this->data_, src1.Data(), src2.Data(), Dim(), src2.Stride(), group_size);

Let's use cuda_calc_group_max_deriv instead of cuda_calc_max_deriv (and also
change other related function names)?

Some general suggestions:

1. limit lines <= 80 characters, for example here (both code and documentation):
   void MatrixBase<Real>::GroupMaxDeriv(const MatrixBase<Real> &input,
                                         const MatrixBase<Real> &output) {
    KALDI_ASSERT(input.NumCols() == this->NumCols() && input.NumRows() == this->NumRows());

2. use consistent variable names, for example, I noticed you used intput_val,
   output_val and maxv, perhaps better to use max_val instead.

3. use proper indentation, for example, here the two "const" should be aligned:
   void MatrixBase<Real>::GroupMaxDeriv(const MatrixBase<Real> &input,
                                          const MatrixBase<Real> &output) {
     KALDI_ASSERT(input.NumCols() == this->NumCols() && input.NumRows() == this->NumRows());

Guoguo

**Comment by naxingyu** [comment]
Thanks Guoguo. I checked the style issues. BTW, is there test code for the cpu porm function that I could refer to?

**Comment by chenguoguo** [comment]
There's probably no test code for Pnorm... You can try to write your own. After that, I think it's good to submit, unless there are more suggestions from Dan.

Guoguo

**Comment by naxingyu** [comment]
In the test code for GPU Maxout, there is already comparison between CPU version and GPU version, using AssertEqual. Should I write another test code in martrix/matrix-lib-test.cc?

**Comment by chenguoguo** [comment]
OK looks good to me then, we are probably not using that test anyway...

Guoguo
--

**Comment by danpovey** [comment]
Guoguo, let us know when all the issues have been addressed and you think
it's OK to commit.

**Comment by chenguoguo** [comment]
It's good to commit.

Guoguo

**Comment by danpovey** [comment]
Before I merge, I'd like to as Xingyu to squash it into one commit (with a single informative commit message) because there are now too many commit messages.
Xingyu, you should be able to do this using
 git rebase -i HEAD~5

**Comment by naxingyu** [comment]
Dan, I squashed the commits into 1 with a single commit message. Is it a correct move? I never used rebase to clean git tree before...

**Comment by danpovey** [comment]
I don't think that is quite right.
Anyway, I guess you have deleted that branch now because I see the pull
request disappeared.
Kirill, I'm inviting you to the organization because maybe you can sort
this out.
Dan

**Comment by naxingyu** [comment]
I pull the branch before pushing the squashed commits.... Maybe that's a bad move.

**Comment by danpovey** [comment]
Kirill will have to tell us what to do.   I'll wait till he's online.

**Comment by vdp** [comment]
I've found this guide: http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by naxingyu** [comment]
Thanks Vassil. I didn't force push the squashed commit. Instead, I pulled the branch... That might have messed up the git tree...

**Comment by vdp** [comment]
By the way GitHub apparently has [a special repository](https://github.com/octocat/Spoon-Knife), that people can use to practice pull requests (including this squashing stuff).

**Comment by danpovey** [comment]
Xingyu, why don't you try following those instructions, and creating a new
branch for your pull request?
I think in the end you are going to have to do the fix yourself, so the
author information is correct.
Dan

**Comment by danpovey** [comment]
I have been trying to figure out how to fix this and I think I have an idea.

Suppose you have "upstream" set to point to kaldi-asr/kaldi.git, and
"origin" set to your personal clone of kaldi.git on github.

git fetch upstream # make sure we have the latest.

#  copy upstream/master to new branch name, and check it out.
git checkout -b naxingyu-maxout-gpu-merged upstream/master

git diff upstream/master naxingyu-maxout-gpu | git apply --whitespace=fix
# you'll see warnings about whitespace.

# Now check that it compiles, etc.

# now push to new branch name
git push origin naxingyu-maxout-gpu-merged

# now generate a clean pull request from github.

**Comment by naxingyu** [comment]
I open a new pull request and close this one.

**Pull request closed without merging**
