### PR TITLE
generate version.h (fixes some of the travis builds failures)

### PR DESCRIPTION
**Pull request by jtrmal**
should address issue found in #1716

### CODE REVIEW

**Comment by jtrmal** [comment]
all right, removed and squashed.

**Comment by kkm000** [comment]
Thanks, and sorry about unintended consequences!

**Comment by danpovey** [comment]
We could consider moving to a paid option on travis, which it seems are
available now.


On Thu, Aug 17, 2017 at 1:08 PM, Kirill Katsnelson <notifications@github.com

**Comment by danpovey** [comment]
sorry posted too soon.
Here
https://travis-ci.com/plans
are plans, the "small teams" one is $129 per month.  Since we paid $4k this
month for the Google cloud hosting of openslr and kaldi-asr.org (although
we're negotiating to get this down), I guess this would just a rounding
error.

**Comment by jtrmal** [comment]
I have no idea why the travis failed now.

**Comment by danpovey** [comment]
ready to merge?

**Comment by danpovey** [comment]
merge yourself if ready.

**Pull request merged**
