### PR TITLE
timit: fixing awk compatibility issue, replacing 'gensub' by 'gsub'...

### PR DESCRIPTION
**Pull request by vesis84**
Resolving this gawk/awk issue: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kaldi-help/Sw3TMkxCyds/qtCeSf1oAAAJ

(awk does not have 'gensub'...)

### CODE REVIEW

**Comment by danpovey** [comment]
There seem to be a few other places where gensub is referred to- would you mind fixing those too?
```
find . -name '*.sh' -exec grep gensub {} \; -print
    awk -v dir=$dir -v n=$n '{ utt=$1; utt_noslash=gensub("/","_","g",utt);
        awk -v dir=$dir -v n=$n -v k=$k '{ utt=$1; utt_noslash=gensub("/","_","g",utt);
./wsj/s5/steps/nnet/make_denlats.sh
# gawk musb be installed to perform awk -v FS="/" '{ print gensub(".gz","","",$NF)" gunzip -c "$0" |"; }' in 
./chime2/s5/run.sh
# gawk must be installed to perform awk -v FS="/" '{ print gensub(".gz","","",$NF)" gunzip -c "$0" |"; }' in
./chime3/s5/local/run_dnn.sh
# gawk must be installed to perform awk -v FS="/" '{ print gensub(".gz","","",$NF)" gunzip -c "$0" |"; }' in
./chime4/s5_1ch/local/run_dnn.sh
   { wav=$1; spk=gensub(/_.*/,"",1,wav); $1=""; ref=$0;
./timit/s5/local/timit_data_prep.sh

```

**Comment by danpovey** [comment]
@YiwenShaoStephen, perhaps you could take care of replacing all the gensub's with gsub?

**Comment by YiwenShaoStephen** [comment]
No problem. Are these lines you printed above the all I need to replace?

**Comment by danpovey** [comment]
Yes

**Comment by danpovey** [comment]
finished this in separate PR.  thanks though.

**Pull request closed without merging**
