### PR TITLE
Added PerDimWeightedAverage component for chain models in SWBD, works…

### PR DESCRIPTION
**Pull request by vijayaditya**
… as good as jesus (tdnn_4f) model

### CODE REVIEW

**Comment by vijayaditya** [comment]
I have created a new config generator for TDNNs similar to those available for LSTM. This will not affect any existing TDDNN/Jesus scripts.

**Comment by danpovey** [comment]
Why do you need a separate train_tdnn.sh script for this?  Can't you use the same pattern as for the jesus-configs, to create the configs?

**Comment by danpovey** [comment]
It's the duplication of code that I'm not crazy about, and the name of the
script train_tdnn_b.sh.  Why couldn't you just slightly extend the existing
train_tdnn.sh script?
BTW, did the low-pass filtering help?
Dan

**Comment by vijayaditya** [comment]
the only thing different in the new train_tdnn.sh script is the make_configs.py which is being called. This new steps/nnet3/tdnn/make_configs.py script makes use of components defined in steps/nnet3/components.py

**Comment by vijayaditya** [comment]
Low-pass filtering didn't help but I would like to keep it as it was just overtraining a lot and I hope it will improve after l2 regularization. Will start this experiment tomorrow.

**Comment by danpovey** [comment]
OK.
Better to just make changes to train_tdnn.sh than to duplicate the script.
Dan

**Comment by vijayaditya** [comment]
OK, will do.

**Comment by vijayaditya** [comment]
just realized I am using a tracking branch for pushing this commit. so I will close this and recreate a pull request.

**Pull request closed without merging**
