### PR TITLE
fix bug when do blstm nnet-forward

### PR DESCRIPTION
**Pull request by yunlinchen**
@danpovey

### CODE REVIEW

**Comment by danpovey** [comment]
OK, I'm going to merge this because we haven't heard from Karel for quite a long time.
If he objects to it, we can revert it later.

**Comment by yunlinchen** [comment]
@danpovey.  okay,  because when I do nnet-forward for blstm model, always core for floating point exception. I check it, found that num_streams=0 as denominator when do division

**Comment by danpovey** [comment]
OK.  Right now no-one is properly maintaining the nnet1 blstm code.  The nnet3 code is under much more active development.

**Comment by yunlinchen** [comment]
@danpovey okay, thank you for your warm apply.

**Comment by lifeiteng** [comment]
Actually , this is not a bug, you can set stream before call nnet-forward to avoid exception.

**Comment by vesis84** [comment]
Hi, recently I was working with CTC-BLSTM from EESEN. Now I am refactoring the BLSTM code, the update will be out in few days...

**Comment by yunlinchen** [comment]
@lifeiteng yes, but in this single binary:nnet-forward, no argument to set this.

**Comment by yunlinchen** [comment]
@vesis84 okay, thx, blstm in nnet1?

**Comment by vesis84** [comment]
The code should not depend on setting the stream-number externally. The default should be 1, if not specified otherwise. There will be a new interface: MultistreamComponent derived from UpdatableComponent handling this systematically...

**Comment by vesis84** [comment]
yes, nnet1 blstm

**Comment by yunlinchen** [comment]
@vesis84 okay, for  I read lstm stream code,  it set 1 when numstream=0, when you push your code, i will try it

**Pull request merged**
