### PR TITLE
[WIP] Add HIMIA (openslr-85) recipe speaker verification

### PR DESCRIPTION
**Pull request by underdogliu**
Hi all,

So here is a recipe of speaker verification experiments for HIMIA (openslr-85) data set. Here, different from original paper, we used x-vector recipe here. We enquired speech data from `multi_cn` that has speaker information (in fact all of them do have). AISHELL2 can be included as well but we made it optional since not everybody owns it.

Note: for scripts cited from `multi_cn`, because we do not have to use textual information here I made slight changes on them. Besides, I remember @naxingyu was planning to make some changes on them so I will keep those on track and changes can be made later (before or after merging).

Note2: The name of such egs is `hi_mia_sv` but feel free to suggest better names. I named it because there is already a similar PR from @nwpuaslp on KWS using same data.

README file is under active writing and hope to be finished soon. Meanwhile people can review script I have written or run experiments to see if there is any unexpected bug there. I will keep things tracked and fixed.

Thanks

### CODE REVIEW

**Comment by danpovey** [comment]
Great!  I hope the others you mentioned can help with review?

**Comment by naxingyu** [comment]
I'll have a look.

**Comment by underdogliu** [comment]
Hey just asking any update so far from @naxingyu @danpovey and @nwpuaslp ?

**Comment by danpovey** [comment]
Sorry if those guys haven't got back to you.. if you think it's ready to mere I can merge it, but please remove .DS_Store.

**Comment by danpovey** [comment]
Sorry if those guys haven't got back to you.. if you think it's ready to mere I can merge it, but please remove .DS_Store.

**Comment by underdogliu** [comment]
@danpovey Yeah that's fine thanks for reply. I think it will be ready at this stage after some minor cleaning. I plan to investigate something meanwhile or after but when it looks ready I will notify you.

One thing that needs to be confirmed is that the script can work with AISHELL2, which is what I cannot check for now since I don't own such data. I will re-run the whole pipeline to make sure everything looks ok but if possible do you know anybody who can run script with AISHELL2 in place? I only know @dophist and @naxingyu who seems a bit busy at this stage.

**Comment by danpovey** [comment]
@jimbozhang how much effort would it be to do what he is asking at Xiaomi?
Not asking anyone at JHU because the server that held datasets crashed recently.

**Comment by jimbozhang** [comment]
I asked Xin Wang @wangxin22, the engineer in charge of Xiaomi's voice-print recognition.

With the default settings of this recipe, it should take about 35 hours on Xiaomi's servers, approximately.

**Comment by danpovey** [comment]
Would you mind testing it out?  I'm hoping it won't take much human time.

**Comment by wangxin22** [comment]
Fine, I will try to validate it with AISHELL2.

**Comment by underdogliu** [comment]
> Fine, I will try to validate it with AISHELL2.

@wangxin22 Thanks! So we'll keep in touch on this.

**Comment by underdogliu** [comment]
@wangxin22 @danpovey Hi both! So while I think you guys are busy with something else, just asking any progress on this one? 🧐

**Comment by kkm000** [comment]
Looks like they are. Do you perchance have something numerical to put in the RESULTS file, in the same top directory as README, with error rates and such? So that whoever starts from it can be sure they have a correct setup. Please have a look at similar files in other recipes for examples. Not all have them, but it's better when they do! :)

**Comment by kkm000** [comment]
Oh, and if you believe it does not apply, just explain why, I'll merge it then.

**Comment by underdogliu** [comment]
@kkm000 I do have. They are contained in `local/run_text_independent.sh`. I put them there following SITW recipe. I am waiting basically for results with AISHELL-2 involved for training speaker embedding extractor. 

But let's wait a bit more then, at least from Dan's side, in case my implementation for including AISHELL-2 is wrong and somebody may thus complain later.

**Comment by kkm000** [comment]
Ok, let's wait a bit. I'm not equipped to run it here, unfortunately.

**Comment by wangxin22** [comment]
@underdogliu, sorry for delay,  I have found some tiny bugs when training with AISHELL2, fixed  in https://github.com/underdogliu/kaldi/pull/1

**Comment by underdogliu** [comment]
@danpovey @kkm000 @naxingyu So as results with AISHELL2 has been updated, I think we are ready to merge this PR. Thanks again @wangxin22 for helping me running AISHELL2 experiments.

There will be some ideas for updates under planning, but I will implement them in foreseeable future when I have time.

**Comment by naxingyu** [comment]
Sorry I forgot about this. We were discussing about naming convention. Current v1 and w1 in hi_mia should be w1 and w2. I'll talk to the contributors of these recipes and make changes accordingly. Then you can name yours as v1 in hi_mia.

**Comment by naxingyu** [comment]
@underdogliu  Doubled confirmed. Could you rename your recipe as hi_mia/v2 and update the readme file?

**Comment by naxingyu** [comment]
@underdogliu Plz ignore the previous comments. hi_mia is under restructure. I'll ping you when it's ready to include your recipe.

**Comment by underdogliu** [comment]
@naxingyu Any more update on this PR?

**Comment by danpovey** [comment]
@naxingyu accepted an offer from Xiaomi; was at Microsoft before.  (He's
joining the speech team, not my team directly, but still we'll be working
together to some extent).
He may be between jobs right now though, dunno if he had his first day.
Hopefully if he's not doing things like this right now he can check this
once he is settled in here.

**Comment by naxingyu** [comment]
I'll make a PR changing himia structure. Will let you know ASAP.

**Comment by danpovey** [comment]
Thanks!

**Comment by underdogliu** [comment]
@naxingyu yep take your time and congradulations on the new job!

**Comment by underdogliu** [comment]
@naxingyu @danpovey Hi both! So any updates so far since I got a stale bot notification?

**Comment by danpovey** [comment]
OK, since @naxingyu probably doesn't have time to do what he planned, I can merge it.    You wanna remove the [WIP]?

**Comment by underdogliu** [comment]
@danpovey let me ask him first. If he can't have time recently we can merge it first for sure.

**Comment by naxingyu** [comment]
Hi @underdogliu plz do the following:
1. Remove hi_mia/v1
2. Move hi_mia_sv/v1 to hi_mia/v1

Thanks!

**Comment by underdogliu** [comment]
@danpovey Changes made according to @naxingyu. I think it is ready to merge. For any more problems we can fix them later.

**Pull request merged**
