### PR TITLE
const-correctness: make ComposeContext take a const reference

### PR DESCRIPTION
**Pull request by maxhawkins**

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks!  Merging.

**Comment by nshmyrev** [comment]
This change caused build failure:

```
In file included from fstcomposecontext.cc:24:0:
../fstext/context-fst.h:507:13: warning: inline function ‘void fst::ComposeContext(std::vector<int>&, int, int, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >*, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >*, std::vector<std::vector<int> >*)’ used but never defined [enabled by default]
 inline void ComposeContext(vector<int32> &disambig_syms,
             ^
/tmp/ccy0ZgGw.o: In function `main':
/home/ubuntu/kaldi/src/fstbin/fstcomposecontext.cc:138: undefined reference to `fst::ComposeContext(std::vector<int, std::allocator<int> >&, int, int, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >*, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >*, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >*)'
collect2: error: ld returned 1 exit status
make[1]: *** [fstcomposecontext] Error 1
make[1]: Leaving directory `/home/ubuntu/kaldi/src/fstbin'
make: *** [fstbin] Error 2
```

gcc 4.8.4 on Ubuntu

I had to revert it.

**Comment by danpovey** [comment]
Oops.  I should have waited for the automatic build to finish.
I just pushed a fix for this- changing the declaration of the function also
(that pull request just changed the definition).
Dan

**Comment by maxhawkins** [comment]
Sorry to break the build—I'll run the tests next time.

**Comment by danpovey** [comment]
No problem- I blame myself as you couldn't have been expected to know.

**Pull request merged**
