### PR TITLE
chain/get_egs.h : minor changes to ensure that valid/train subsets ha…

### PR DESCRIPTION
**Pull request by vijayaditya**
…ve utts with length at least frames_per_eg

### CODE REVIEW

**Comment by danpovey** [comment]
As before- this is quite inefficient.  Better to use  utils/data/get_frame_shift.sh and utils/data/get_utt2dur.sh, which in most cases will get the durations from the segments file (and if not, at any rate the durations will be cached and reused).
Dan

**Comment by vijayaditya** [comment]
(both the PRs are exactly the same. I was unable to decide whether to merge to master or chain branches which led to this confusion.)

OK, I will use utils/data/get_utt2dur.sh

**Comment by vijayaditya** [comment]
@danpovey done

**Comment by danpovey** [comment]
Seems OK, but have you tested it?  We could just wait till you need to run something else and then merge it.

**Comment by vijayaditya** [comment]
I tested it.

**Pull request merged**
