### PR TITLE
add doc for kaldi pybind.

### PR DESCRIPTION
**Pull request by csukuangfj**
As mentioned in <https://github.com/danpovey/kaldi/pull/87#issuecomment-567308099>
and <https://groups.google.com/forum/#!topic/kaldi10-design/BYSkonhkiwc>, we are starting to add documentation for kaldi pybind.

The following is a screenshot showing what the generated documentation looks like.

You can access it from <https://kaldi-pybind.imfast.io/index.html>

Screen Shot 2020-03-01 at 23 52 44

----

For developers, you can follow <https://github.com/mobvoi/kaldi/blob/fangjun-doc/src/pybind/doc/developers.md> to generate documentation locally.

The following is a screenshot from my local computer:

Screen Shot 2020-03-01 at 23 56 23

---
@danpovey @jtrmal 
please have a reivew.

The generated HTML files can be hosted at <https://kaldi-asr.org/doc/>
in a subdirectory, say `pybind`.

### CODE REVIEW

**Comment by danpovey** [comment]
This looks good to me.  Of course, the different style vs. doxygen is not ideal, but we have to face the fact that doxygen is getting less popular.   Any other comments before I merge?

**Comment by csukuangfj** [comment]
`Doxygen` is suitable for generating documentation for C++ code.

Nowadays, I think `Sphinx` is very popular for generating documentation for Python code.

I find that this project <https://exhale.readthedocs.io/en/latest/> can parse Doxygen style
comments into the sphinx domain. Maybe we can convert the current C++ documentation.

Sphinx also supports markdown files.

-----

I think we have to upload the generated HTML files to the kaldi doc server.
Is it possible to make this process automatically once a pullrequest is merged?

**Comment by danpovey** [comment]
We can figure out a workflow to generate and upload the docs.  It would be
great if someone could work on a docker build that we can enable via
travis.  This would have to be done for the existing docs first; then,
perhaps, the same in a separate directory for the pybind11 branch.  @jtrmal
to you feel like working on this?

**Comment by jtrmal** [comment]
yeah i will look at the tomorrow

**Comment by danpovey** [comment]
Merging this too...

**Comment by galv** [comment]
A lot of problems with exhale were worked out for the sake of pytorch's C++ interface. It should *just work*, as the say.

**Pull request merged**
