### PR TITLE
[src] Remove configure support for threaded math

### LINKED ISSUE #3192: Remove all threaded BLAS options from configure
Decided here: https://github.com/kaldi-asr/kaldi/issues/3078#issuecomment-478305746

I'll still recognize the switches, but print an error that they are no longer supported.

Also (from https://github.com/kaldi-asr/kaldi/pull/3216#discussion_r273627823 and following)

```
$ ./configure  --mathlib=ATLAS
 . . . . .
Using ATLAS as the linear algebra library.
Could not find libatlas.a in any of the generic-Linux places, but we'll try other stuff...
** Failed to configure ATLAS libraries ***
**  ERROR   **
** Configure cannot proceed automatically.
**  If you know that you have ATLAS installed somewhere on your machine, you
** may be able to proceed by replacing [somewhere] in kaldi.mk with a directory.
**  If you have sudo (root) access you could install the ATLAS package on your
** machine, e.g. 'sudo apt-get install libatlas-dev libatlas-base-dev' or
** 'sudo yum install atlas.x86_64' or 'sudo zypper install libatlas3-devel',
** or on cygwin, install atlas from the installer GUI; and then run ./configure
** again.
**
**  Otherwise (or if you prefer OpenBLAS for speed), you could go the OpenBLAS
** route: cd to ../tools, type 'extras/install_openblas.sh', cd back to here,
** and type './configure  --openblas-root=../tools/OpenBLAS/install'
```
Perhaps encourage the use of MKL for speed. Maybe mention OpenBLAS, but the "for speed" recommendation is no longer correct, certainly not for the Intel CPU.

Also, refer to install_mkl if MKL is missing from `./configure` with no args.

### PR DESCRIPTION
**Pull request by kkm000**
Closes #3192

### CODE REVIEW

**Comment by kkm000** [comment]
@jtrmal, if you have a few minutes, could you PTAL? I checked MKL, but I do not have Atlas handy, although changes there are minimal.

**Comment by jtrmal** [comment]
LGTM, please merge

**Comment by kkm000** [comment]
@jtrmal Thanks!

**Comment by psmit** [comment]
Unfortunately, this PR broke static MKL compilation. Originally link lines for static MKL contained `-l/opt/intel/mkl/lib/intel64/libmkl_core.a` and this has been changed to `-lmkl`. For static compilation, the search path is not set, so this fails.

Possible fixes are:
1. Also set the search path (-L) for static compilation (like for non-static https://github.com/kaldi-asr/kaldi/blob/master/src/configure#L283). Not sure if that would solve the problem.
2. Restore the old link line by changing https://github.com/kaldi-asr/kaldi/blob/master/src/configure#L295 from:
```
linkline+=" -l$file"
```

to

```
if ! $static; then
 linkline+=" -l$file"
else
  linkline+="-l$libfile"
fi
```

I'm not sure what is the best option, but I'm happy to provide a PR if needed.

**Comment by danpovey** [comment]
Would be great if you could provide a PR, Peter!  Sorry dont have an
opinion about which is best, you can decide.

**Comment by kkm000** [comment]
@psmit, I've seen your PR, thanks. I am wondering what benefits you are getting form linking to MKL statically, and what are the binary sizes? If you have an approximate idea by how much this increases the binary sizes? They are about 20GB on Linux x64 with gcc and dynamic MKL.

I think—better said, thought—that we should to switch to their "single runtime library" linking, or otherwise there are conflicts when calling Kaldi libraries from Python. But that is not available in static. Understanding your use case would be very helpful for us.

**Comment by daanzu** [comment]
@kkm000 I haven't tested this PR or @psmit's yet, but I statically link MKL to simplify distribution. My project only needs to distribute (from Kaldi) one shared library (which is used by Python via cffi) and a few CLI programs, and doing so is far simpler when linking MKL & OpenFST statically. I would hate to lose that ability.

**Comment by psmit** [comment]
Thanks for merging and the extensive comment. 

Regarding MKL, I'm pretty sure all the architectures are in the binary, but that is more a guess than that I checked (or read that manual).

Many of the techniques mentioned, like multi-stage docker files, are indeed what we are using. It took us a lot of time to get our image sizes down, and for us, this was back then with the static MKL.

In the near future, I'm looking to bench things more on our side, if this happens I'll share the results and observations also here.

**Pull request merged**
