### PR TITLE
Add option to skip nnet3 decode diagnostics

### PR DESCRIPTION
**Pull request by guoguo12**

### CODE REVIEW

**Comment by danpovey** [comment]
Why is this helpful?  Are the diagnostics slow?

**Comment by guoguo12** [comment]
Sorry, I should have given some kind of rationale.

Basically, I've created a Docker container that contains the minimal Kaldi installation required to decode nnet3. This container doesn't have Python installed, and the diagnostics won't work without Python. There are a few ways around this, but I think the cleanest is to make the diagnostics skippable, since the diagnostics aren't crucial to decoding.

**Comment by danpovey** [comment]
OK, merging since it seems harmless.

**Comment by guoguo12** [comment]
Thanks!

**Pull request merged**
