### PR TITLE
updates for avoiding missed speech

### PR DESCRIPTION
**Pull request by ngoel17**
GuoGuo,
  I Made changes as per your code review and made this pull request. I hope this works out to be a neat process.
Nagendra

### CODE REVIEW

**Comment by jtrmal** [comment]
Guoguo, please look into it.
y.

**Comment by jtrmal** [comment]
Does this work, @chenguoguo ?

**Comment by chenguoguo** [comment]
I took a look, it's good to commit.

Guoguo
--

**Comment by jtrmal** [comment]
OK, merging. Thanks @ngoel17  and @chenguoguo

**Pull request merged**
