### PR TITLE
Added dumping/non-dumping option and a pointer to copy decoded output on it to kaldi decoder.

### PR DESCRIPTION
**Pull request by MohamadIsmail**
added dumping option for decoded features and a pointer passed by user to copy information on it when you use class "DecodeUtteranceLatticeFaster".
before that, the user was forced to pass a valid path to a dump file to receive output on it. now you have an option to pass to its constructor either:
- "compact lattice writer"/"lattice writer" as NULL, dumping option as false and an instantiated pointer to receive output on it.
- or "compact lattice writer"/"lattice writer" as an absolute path to a dump file you want to create, dumping option as true and NULL pointer.

### CODE REVIEW

**Comment by danpovey** [comment]
thanks for the PR, but we don't merge things like this unless they are needed for something we are checking in; this extra code would not be called anywhere so it's unnecessary for the current project.

**Comment by lordadamson** [comment]
Hi Dan,
Thanks for the reply. We use the decoder wrapper in our project and we do not wish to use file IO.
We're currently running a modified version of kaldi that has @MohamadIsmail patch.
I'm sure there are other projects that would need to avoid disk IO.
Is there an alternative that we're not aware of?
Thanks in advance.

**Comment by danpovey** [comment]
That wrapper function is just a convenience function created in order to
avoid duplication of the same code in multiple different command-line
decoder binaries.  It's not really a core utility.  You can adapt the code
as you see fit for your purposes.

**Comment by lordadamson** [comment]
Ah! I understand now. Thank a lot for the explanation.

On Aug 25, 2017 2:47 AM, Daniel Povey <notifications@github.com> wrote:
That wrapper function is just a convenience function created in order to
avoid duplication of the same code in multiple different command-line
decoder binaries. It's not really a core utility. You can adapt the code
as you see fit for your purposes.

**Pull request closed without merging**
