### PR TITLE
Added variable delay lstms.

### PR DESCRIPTION
**Pull request by vijayaditya**
This commit is not ready for merge. It has been created to provide a forum for discussion.

With this commit the LSTM(s) can have a delay other than -1 in recurrence i.e.,
<pre><code>
d : lstm-delay
//      i(t) = S(Wix * x(t) + Wir * r(t-d) + Wic * c(t-d) + bi)
//      f(t) = S(Wfx * x(t) + Wfr * r(t-d) + Wfc * c(t-d) + bf)
//      c(t) = {f(t) .* c(t-d)} + {i(t) .* g(Wcx * x(t) + Wcr * r(t-d) + bc)}
//      o(t) = S(Wox * x(t) + Wor * r(t-d) + Woc * c(t) + bo)
//      m(t) = o(t) .* h(c(t))
//      r(t) = Wrm * m(t)
//      p(t) = Wpm * m(t)
//      y(t) = Wyr * r(t) + Wyp * p(t) + by
</code></pre>

In a stacked LSTM each lstm layer can have a different delay.

### CODE REVIEW

**Comment by vijayaditya** [comment]
|                    Model             |     Dev     | Eval |
|------------------------------------|-------------|--------|
|      variable-delay LSTM    | 	43.8	    | 47.3  |
|                       LSTM           |    44.2    |47.6  |

variablelstm

**Comment by danpovey** [comment]
Cool!
Is it faster to train?
Dan

**Comment by vijayaditya** [comment]
LSTM : Total training time is 21:34:06
Variable-delay LSTM Total training time is 18:43:35

**Comment by vijayaditya** [comment]
I made variable delay LSTM the default LSTM recipe for AMI.

**Comment by vijayaditya** [comment]
I forgot to mention that this is ready for merge

**Pull request merged**
