### PR TITLE
backport of chime5 script from s5b

### PR DESCRIPTION
**Pull request by jtrmal**
I have updated the s5 recipe as the s5b has an awful lot of dependencies, installs whole python conda environment plus uses offline nara_wpe who needs tens of gigabytes of ram to complete. The s5 is much more practical and runnable easily -- only because it uses obsolete configuration, there were some convergence issues. Using the proper way how to specify TDNN-F system has fixed that. As an added benefit, the absolute WER has improved by almost 10 % abs -- so it seems the nara_wpe is not that crucial -- seems to add maybe two or three percent abs?

### CODE REVIEW

**Comment by danpovey** [comment]
OK.  You don't want to make it 1b and move the soft link, like the normal pattern?  I'm not sure if you have results for the old setup?  (They weren't at the top of the script like normal)

**Comment by jtrmal** [comment]
I can figure it out -- I don't have the file but I can pull it from the
history.
I felt like you'd prefer this way, as the previous recipe was not
functioning well (if at all) -- but I don't have anything against going
back to 1a and adding 1b
y.

**Comment by jtrmal** [comment]
ok, done + rebased/squashed

**Comment by danpovey** [comment]
OK thanks.  Will merge.

**Comment by jtrmal** [comment]
eh, seems like I accidentally deleted the backported version... will look if I can pull it out from somwhere :/
Please revert, if possible.

**Comment by danpovey** [comment]
let me just wait till you fix it... I dont want  too many commits to clutter the history, and this shouldn't affect anyone.

**Pull request merged**
