### PR TITLE
Look in right location for new style subdirectories

### PR DESCRIPTION
**Pull request by aevernon**

### CODE REVIEW

**Comment by danpovey** [comment]
Note: this is a resubmission of PR #1209.  
Before I merge, can you please 'wc' the data/train/wav.scp?  I want to double check that everything looks OK.  I got this:
   21496   193464  3804792 /home/dpovey/kaldi-pure/egs/fisher_english/s5/data/train/wav.scp
steps/decode_sgmm2_rescore.sh

**Comment by aevernon** [comment]
Did you mean to run `wc` on `egs/fisher_english` instead of `egs/aspire`?

```bash
wc egs/aspire/s5/data/train/wav.scp
```

>   23302  209718 3844560 egs/aspire/s5/data/train/wav.scp

```bash
head -n 5 egs/aspire/s5/data/train/wav.scp
```

> fe_03_00047-A /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 1 /export/corpora3/LDC/LDC2004S13/fisher_eng_tr_sp_d1/audio/000/fe_03_00047.sph |
> fe_03_00047-B /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 2 /export/corpora3/LDC/LDC2004S13/fisher_eng_tr_sp_d1/audio/000/fe_03_00047.sph |
> fe_03_00048-A /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 1 /export/corpora3/LDC/LDC2004S13/fisher_eng_tr_sp_d1/audio/000/fe_03_00048.sph |
> fe_03_00048-B /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 2 /export/corpora3/LDC/LDC2004S13/fisher_eng_tr_sp_d1/audio/000/fe_03_00048.sph |
> fe_03_00049-A /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 1 /export/corpora3/LDC/LDC2004S13/fisher_eng_tr_sp_d1/audio/000/fe_03_00049.sph |

```bash
tail -n 5 egs/aspire/s5/data/train/wav.scp
```

> 
> fe_03_11697-B /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 2 /export/corpora3/LDC/LDC2005S13/fe_03_p2_sph7/audio/116/fe_03_11697.sph |
> fe_03_11698-A /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 1 /export/corpora3/LDC/LDC2005S13/fe_03_p2_sph7/audio/116/fe_03_11698.sph |
> fe_03_11698-B /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 2 /export/corpora3/LDC/LDC2005S13/fe_03_p2_sph7/audio/116/fe_03_11698.sph |
> fe_03_11699-A /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 1 /export/corpora3/LDC/LDC2005S13/fe_03_p2_sph7/audio/116/fe_03_11699.sph |
> fe_03_11699-B /kaldi/egs/aspire/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 2 /export/corpora3/LDC/LDC2005S13/fe_03_p2_sph7/audio/116/fe_03_11699.sph |

**Comment by danpovey** [comment]
This code exists in many locations, so can you please update all of them?
```
ls ../../*/s*/local/fisher_data_prep.sh
../../aspire/s5/local/fisher_data_prep.sh
../../fisher_english/s5/local/fisher_data_prep.sh
../../fisher_swbd/s5/local/fisher_data_prep.sh
../../multi_en/s5/local/fisher_data_prep.sh
```
In our setup we actually have fewer lines in wav.scp:
```
wc /home/dpovey/*/egs/aspire/s5/data/train/wav.scp
   21502   193518  3934866 /home/dpovey/kaldi-trunk/egs/aspire/s5/data/train/wav.scp

vs. your 23302.  But I guess that's because you have a newer copy of the data distribution.

**Comment by aevernon** [comment]
I've updated the remaining copies of `fisher_data_prep.sh` in 7b47ebe to use `fe_03_p1_sph`.

**Pull request merged**
