### PR TITLE
WIP : Added changes to ensure that the correct left/right contexts are used…

### PR DESCRIPTION
**Pull request by vijayaditya**
… for computation in nnet3 setup. For more details see Issue #1190 

Testing in progress.

### CODE REVIEW

**Comment by danpovey** [comment]
OK, @vijayaditya, merge when you think it's tested.
@vimalmanohar, please notice this, it might require changes in your PR where you refactor the training libraries [and BTW, I'd like to know where we are with that.]

**Comment by vijayaditya** [comment]
@freewym Could you please review this PR. I will merge after your signoff.

**Comment by freewym** [comment]
Looks fine to me.

**Comment by danpovey** [comment]
Vijay, are you still awake?  This PR was problematic, it is causing a crash for me.  I think it has to do with frame-shifting, more context is needed.  Or the limitation of context should be done after the frame shift.

**Comment by danpovey** [comment]
OK, I have fixed this with commit ac1f932.   It changes nnet3-chain-copy-egs so that it applies the frame shift before limiting context.  
Note: the crash was with TDNNs.  With BLSTMs you wouldn't have seen a crash because of the extra context.

**Pull request merged**
