### PR TITLE
Changes from pegah for tensormultiply in matrix/cudamatrix

### PR DESCRIPTION
**Pull request by vijayaditya**
This is the tensor multiply operation implemented by @pegahgh . This will be used for some new components in nnet3.

### CODE REVIEW

**Comment by danpovey** [comment]
I don't want to merge this until i'm convinced that we need it.  What
exactly do you want to do with this, and are you sure that AddMatMatBatched
is not the more suitable solution?

**Comment by vijayaditya** [comment]
Using an AddMatMatBatched call would be easier, but it would require a permutation of the columns as this component will be used on spliced output (i.e., output of Append descriptor).

**Comment by danpovey** [comment]
You could use a temporary inside the propagate/backprop code.  I'd rather
rely on the CUBLAS internals than custom ones, as they'll improve them in
future.  You should at least compare the speed, before we add all that code
to the repo.
Dan

**Comment by vijayaditya** [comment]
OK.

**Pull request closed without merging**
