### PR TITLE
make codes in src/util/ comply with Google style

### PR DESCRIPTION
**Pull request by keli78**
make codes in src/util comply with google C++ style

### CODE REVIEW

**Comment by danpovey** [comment]
Ke,
It says 'this branch has conflicts that must be resolved'.
You should ask someone who knows git to help you.. it will probably involve something like
fetch upstream
git rebase upstream/master
[then edit files and 'git add' things that you edited]
but you may not have put kaldi-asr/kaldi.git as 'upstream'- so better to ask an expert.

**Comment by keli78** [comment]
Hi Dan, 
I just resolved the previous conflicts with Vimal's help. What I did were:
git fetch golden
git rebase golden/master
[edited files]
git rebase --continue
git push -f origin branchName

**Comment by danpovey** [comment]
Thanks!  Committing.

**Comment by keli78** [comment]
Do I need to continue doing these modifications for other folders?

**Comment by danpovey** [comment]
Not right now.

**Pull request merged**
