### PR TITLE
nnet3-am-copy option to convert RepeatedAffine components to BlockAffine components.

### PR DESCRIPTION
**Pull request by galv**
Addresses #440.

In addition to the unit tests provided, I ran nnet3-am-copy --repeated-to-block on one of my own models, and check all the components were successfully converted.

### CODE REVIEW

**Comment by galv** [comment]
Something's wrong with the commit history. I might have misused git cherry pick wrong. Closing this for now.

**Comment by vijayaditya** [comment]
You might have created a pull request for the master, instead of chain
branch.

**Comment by galv** [comment]
Ooops. Thanks.

**Comment by galv** [comment]
Opened a new pull reuqest here: #451

Thanks, Vijay.

**Pull request closed without merging**
