### PR TITLE
Add support for context independent phones in gmm-init-biphone (for e2e)

### PR DESCRIPTION
**Pull request by hhadian**
This PR adds a feature to gmm-init-biphone so it can treat some phones (e.g. silence phones) as context independent. 
@aarora8 and @ChunChiehChang, if you have time, it would be good to test this using some of the OCR recipes. Please let me know if you will have time for this.

### CODE REVIEW

**Comment by aarora8** [comment]
Thank, i will test it with rimes dataset. Should compare it with a baseline or something similar.

**Comment by aarora8** [comment]
ok, thank you, i will do it.

**Comment by ChunChiehChang** [comment]
I'll probably run this on the iam egs as well.

**Comment by hhadian** [comment]
Based on Jonathan's and Ashish's results, this does not give WER improvements but the objf is improved. I saw similar results on ASR tasks. 
But I think it might be useful to have this feature, anyway.

**Comment by danpovey** [comment]
OK, merging.

**Pull request merged**
