### PR TITLE
Fix matrix data offset for large matrices

### PR DESCRIPTION
**Pull request by nshmyrev**
Funny enough it wasn't noticed before.

If we create a big matrix say 2 000 000 x 1280 (10Gb in size), RowData doesn't work properly and causes a segfault. It just overflows int32 while calculating offset.

### CODE REVIEW

**Comment by nshmyrev** [comment]
Hold on merging this, cudamatrix also needs fix

**Comment by jtrmal** [comment]
LGTM

**Comment by jtrmal** [comment]
Merging, thanks!

**Comment by nshmyrev** [comment]
Thank you!

**Pull request merged**
