### PR TITLE
accel convolutional component in nnet

### PR DESCRIPTION
**Pull request by naxingyu**
Accelerate the Convolutional propagate, backpropagate and update functions by using a column map. Reducing the calling of CopyCols and AddCols for acceleration.

### CODE REVIEW

**Comment by danpovey** [comment]
I notice there some lines with >80 characters.  They should be split up. e.g
      vectorized_feature_patches_.Resize(num_frames, filter_dim * num_patches, kUndefined);
fix nearby existing code if you see issues, too.
@vesis84, can you please approve this once he is done?
It should be fairly straightforward.

**Comment by naxingyu** [comment]
Done.

**Comment by danpovey** [comment]
@vesis84, if you don't get back to us within the next few days I'll probably go ahead and merge it myself.

**Comment by danpovey** [comment]
I just noticed that this PR has conflicts.  Xingyu, could you please update the PR by merging the latest changes?
Dan

**Comment by naxingyu** [comment]
The conflict is caused by the new CopyCols interface. It is resolved now.

**Comment by danpovey** [comment]
Thanks.
If Karel doesn't reply after a day or two, I'll merge it.
Dan

**Pull request merged**
