### PR TITLE
Change Travis compiler to clang++-3.9.

### PR DESCRIPTION
**Pull request by dogancan**
Increase the number of parallel make jobs to 6.

Remove -rdynamic flag from CXXFLAGS. It is already in LDFLAGS.

### CODE REVIEW

**Comment by dogancan** [comment]
@danpovey @jtrmal This is ready for merge. Note that in addition to changing the compiler, I also removed the `-rdynamic` flag from `CXXFLAGS` on all platforms since it is a linker flag and we are already adding it to `LDFLAGS`. clang++ was printing a warning whenever we used this flag while compiling the object files.

**Comment by dogancan** [comment]
@jtrmal Also see #1423 for build time averages with clang (vs gcc).

**Comment by jtrmal** [comment]
I'm ok with merging this. My experience about the times is about the same.
y.

**Comment by jtrmal** [comment]
BTW, another option how to speed things up  (after making kaldi 5.1
default) would be either download the stock openfst (hopefully it will be
available) or have a package already precompiled somewhere and just
download it (as a kinda desperate measure).
But I think Dogan or someone else has been already mentioning this.
y.

**Comment by danpovey** [comment]
It seems to me that we have had more build failures since the switchover to clang; for some reason the build time seems more variable.
I am wondering whether we could revert this.
Any comments?

**Comment by jtrmal** [comment]
I don't care too much about if it will be reverted or not. I checked the
two last failures and both were because of the timeout. So I guess we will
never know if it's really clang or something else unless we revert at least
for some time...
y.

**Comment by danpovey** [comment]
Looks like that commit had other changes which were fixes, and should not
be reverted.  I'll wait till Dogan has time to make a PR which will change
it back to g++.

**Pull request merged**
