### PR TITLE
Cf/fix get ctm empty transcripts

### PR DESCRIPTION
**Pull request by christophfeinauer**
check if there are empty transcripts before running segment_long_utterances.sh

### CODE REVIEW

**Comment by danpovey** [comment]
I believe we are supposed to have fixed the problem that happens if there
are empty transcripts.
If not (i.e. if they still cause a problem) let us know.

**Comment by christophfeinauer** [comment]
Sorry, the pull-request was intended for my own fork.
I had problems with 1) empty transcripts and 2) silence-only audio files with non-empty transcripts. I am not sure which one is the necessary condition, I will check and open an issue in case.

**Comment by danpovey** [comment]
Well let us know what the error message is-- but first make sure your own
branch is up to date, because a bug like that was fixed previously.

**Comment by christophfeinauer** [comment]
On 32310017859cea31f167c70b7926fadde0761c36 on master the error on a silence-only audio file (with non-empty transcript) is:

```steps/cleanup/segment_long_utterances.sh: using default values of non-scored words...
2017-10-30 18:51:36,124 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:72 - read_segments - INFO ] Read 105 lines from segments file local/temp2/train_all_noempty_100_uniform_seg/segments
2017-10-30 18:51:36,129 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:120 - read_ctm_edits - INFO ] Read 1928 lines from CTM local/temp2/lats/score_10/ctm_edits
2017-10-30 18:51:36,133 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:314 - run - ERROR ] Failed to process CTM edits for recording anonymous-20100108-vhh_de11-092
2017-10-30 18:51:36,133 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:326 - main - ERROR ] Failed to resolve overlaps
Traceback (most recent call last):
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 324, in main
    run(args)
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 310, in run
    ctm_edits_for_reco = resolve_overlaps(ctm_edits_for_reco, segments)
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 179, in resolve_overlaps
    raise RuntimeError('CTMs for recording is empty. '
RuntimeError: CTMs for recording is empty. Something wrong with the input ctms
Traceback (most recent call last):
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 342, in <module>
    main()
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 327, in main
    raise RuntimeError
RuntimeError
```

**Pull request closed without merging**
