### PR TITLE
Cuda 8.0 compatibility fix

### PR DESCRIPTION
**Pull request by fgghjjkll**
Compilation was broken for Ubuntu 14.04 with Nvidia CUDA toolkit 8.0GA2. These changes will allow Kaldi to be compiled again.

### CODE REVIEW

**Comment by danpovey** [comment]
I'm a little confused because we have the CUDA 8.0 toolkit installed, it compiles fine.
I'm sure the changes are harmless and can be merged, but i'd like to understand what went wrong.

For us:
```
/usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

```
grep ZERO_PIVOT /usr/local/cuda/include/*.h
/usr/local/cuda/include/cusolver_common.h:    CUSOLVER_STATUS_ZERO_PIVOT=10,
/usr/local/cuda/include/cusparse.h:    CUSPARSE_STATUS_ZERO_PIVOT=9
```

**Comment by fgghjjkll** [comment]
I'm not to sure why it failed for me then :(
I've attached the [compilation output](https://github.com/kaldi-asr/kaldi/files/1687071/make.log), and my configure options are: 
./configure --shared --use-cuda --mathlib=MKL --threaded-math --mkl-root=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl --mkl-threading=tbb --omp-libdir=/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.7

**Comment by jtrmal** [comment]
I did a brief google search and it could be those constant are present from
CUDA 9.0 (you might have two SDKs installed). That seems consistent with
the test if CUDART_VERSION >= 9000
But I wasn't very methodical, so I might be mistaken.

**Comment by jtrmal** [comment]
I take that back -- the patch is to be applied the other way, sorry.
y.

**Comment by fgghjjkll** [comment]
I definitely only have 8.0 installed. Nvidia stopped supporting 14.04 since Cuda 9.0.
```
/usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

**Comment by danpovey** [comment]
It's odd that your compilation says

 -DHAVE_CUDA -I/usr//include

It's almost as if CUDATKDIR was empty.  Did 'configure' complain?

**Comment by danpovey** [comment]
I think I see what happened.  It searches /usr/ after  /usr/local/cuda for
the CUDATKDIR, and the later one takes precedence.  You have probably an
older version of CUDA installed in /usr/bin.

**Comment by fgghjjkll** [comment]
Oh, you're right! It was a problem on my end. The configure didn't complain, but after setting cudatk-dir=/usr/local/cuda, it is compiling fine again!
Thanks for all your help!

**Pull request closed without merging**
