### PR TITLE
For compatibility with MS Visual Studio.

### PR DESCRIPTION
**Pull request by tal1974**
In the case of "1.0 / 0.0" compiler generates an error:
1>  kaldi-vector.cc
1>..\..\..\src\matrix\kaldi-vector.cc(523): error C2124: divide or mod by zero

If the constant 0.0 is replaced by a variable, then there is no error.

### CODE REVIEW

**Comment by jtrmal** [comment]
I believe the "nice" way is to compare the number with
std::numeric_limits<Real>::infinity()
which is more self-explanatory.
y.

**Comment by danpovey** [comment]
Yes- it looks like the intention in that code was to compare with infinity
(although I'm wondering whether that division 1.0 / 0.0 actually generates
NaN in reality).  So please modify the PR to use Yenda's solution.

**Comment by tal1974** [comment]
I absolutely agree with you. Just could not find this variable by myself.

**Comment by danpovey** [comment]
Can you please rebase so there is just one commit?
git rebase HEAD~2
and change the second "pick" to "squash".
you'll have to push with --force to your github repo.

**Comment by danpovey** [comment]
No need to close the PR, you just have to modify the branch it points to.
 (you need to push --force since it's a non-fast-forward update).

**Comment by tal1974** [comment]
Sorry. I don't use git on my PC. I edit file on github.com. Now everything is done as before. Apparently, something went wrong.

**Comment by tal1974** [comment]
It seems to be fixed.

**Comment by danpovey** [comment]
There are still 3 commits :-(

**Pull request closed without merging**
