### PR TITLE
updated nnet2 natural gradient codes according to nnet3 natural gradi…

### PR DESCRIPTION
**Pull request by xiaohui-zhang**
…ent codes.

### CODE REVIEW

**Comment by jtrmal** [comment]
Samuel, could you change back the Exp instead of exp?
It was there to fix some issues  with glibc and Windows build.
Y

**Comment by xiaohui-zhang** [comment]
done

**Comment by xiaohui-zhang** [comment]
@jtrmal

**Comment by danpovey** [comment]
Samuel, I had not merged into master my changes to the nnet3 natural-gradient code in my own branch.  My intention was for you to create a pull request that included my nnet3 changes also, as well as the nnet2 version of them.
Dan

**Comment by xiaohui-zhang** [comment]
ok~

On Mon, Nov 30, 2015 at 12:56 PM, Daniel Povey <notifications@github.com>
wrote:

> Samuel, I had not merged into master my changes to the nnet3
> natural-gradient code in my own branch. My intention was for you to create
> a pull request that included my nnet3 changes also, as well as the nnet2
> version of them.
> Dan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/368#issuecomment-160706044>.
>



-- 
Xiao-hui

**Pull request closed without merging**
