### PR TITLE
Lstm noprojection

### PR DESCRIPTION
**Pull request by naxingyu**
Add LSTM component without projection.

### CODE REVIEW

**Comment by danpovey** [comment]
Why are you putting the LSTM component stuff in the same pull request as your Maxout test code?  For sure this will delay the merging of the code.  Can we do this one issue at a time?

**Comment by naxingyu** [comment]
Thanks Dan. Sorry for that. I thought github could distinguish pull requests from different commits... I close this request now.

**Comment by jtrmal** [comment]
It will... Buf you have to create the PRs from different branches. Then it
will work as expected.
y.

**Comment by naxingyu** [comment]
Yes, I created a new branch, but the old commits are also in this new branch... I must have done something wrong, will figure it out.

**Comment by jtrmal** [comment]
I see... no, the unrelated commits have to be in separate branch :)
you can use git cherry-pick to pick the individual commits
http://stackoverflow.com/questions/25955822/git-cherry-pick-a-single-commit-for-pull-request

**Comment by danpovey** [comment]
or just wait till the first thing is committed.

**Pull request closed without merging**
