### PR TITLE
Set PYTHONUNBUFFERED=1 in all recipes

### PR DESCRIPTION
**Pull request by ma08**
To force stdout, stderr to be unbuffered for python scripts.
Without this setting, parts of the stream might be lost in a few cases.
Relevant mainly for python versions <3.7.

Discussion regarding this PR in `kaldi-developers` Google Group : [https://groups.google.com/g/kaldi-developers/c/YEJugk2J9Xw](https://groups.google.com/g/kaldi-developers/c/YEJugk2J9Xw)

### CODE REVIEW

**Comment by jtrmal** [comment]
could we just do 
```
PYTHONUNBUFFERED=1
```
please? Uppercased TRUE is not nice and doesn't mesh well with neither python nor bash

**Comment by ma08** [comment]
@jtrmal Oops. Sure!

Shall I create a new PR or make changes to the existing one with a new commit?

**Comment by ma08** [comment]
@jtrmal let me know if any other issues.

It's a single line change in all the files (addition of the line). Number of files changed is 139 which matches the number of path.sh file in `egs`

`sourya4@IWeighHar:~/pro/columbia/spring22/fund_sp_rec/kaldi_fork$ find egs/ -name "path.sh" | wc -l
139
`

**Comment by jtrmal** [comment]
looks good, thanks!

**Pull request merged**
