### PR TITLE
Fast LSTM

### PR DESCRIPTION
**Pull request by danpovey**
I am creating this PR to document the changes that we hope to merge soon, regarding the fast LSTM implementation but also Vimal's refactoring of the scripts.  I'll delete the other PRs that are for this issue; this one replaces them.

People can also use this branch as a starting point for their work; this will help test this setup, and ensure that people's work is applicable after we merge this PR.

### CODE REVIEW

**Comment by vdp** [comment]
Dan, is this PR somehow related, or is it mostly orthogonal, to your "looped computation" branch? I'm asking because I'm planning to have a look at the nnet3 code and figured I should probably use the newest version of it. I'm mostly interested in the decoding-related parts.

**Comment by danpovey** [comment]
It's orthogonal, except that the LSTM would be a good candidate to use with
th e 'looped computation'.  I'm waiting for Tom Ko to finish checking in
some bug fixes.
Dan

**Comment by vdp** [comment]
OK, good to know. Thank you!

**Comment by danpovey** [comment]
OK, I am pressing the button and merging the fast_lstm changes.
This also merges Vimal's python script refactoring.

**Pull request merged**
