### PR TITLE
openSUSE

### PR DESCRIPTION
**Pull request by keli78**
Updated the installation script for installing Kaldi on openSUSE.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.
Part of this problem was pre-existing, but all invocations of add_packages should have the same number of command line arguments (now 3).  These are the package names used for those utilities on the 3 OS variants.  This will involve a little research.  You can ask the others to help you, e.g. @vimalmanohar .  Each package manager has its own syntax and its own way of figuring out the package names.
Dan

**Comment by keli78** [comment]
Thanks for your reply. I'm wondering whether you could explain a little bit
of "this problem".
Ke

On Fri, Sep 4, 2015 at 4:39 PM, Daniel Povey <notifications@github.com>
wrote:

> Thanks.
> Part of this problem was pre-existing, but all invocations of add_packages
> should have the same number of command line arguments (now 3). These are
> the package names used for those utilities on the 3 OS variants. This will
> involve a little research. You can ask the others to help you, e.g.
> @vimalmanohar <https://github.com/vimalmanohar> . Each package manager
> has its own syntax and its own way of figuring out the package names.
> Dan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/125#issuecomment-137847113>.
>



-- 
Ke Li
Research Assistant
Dept. of Biomedical Engineering
Johns Hopkins University
Phone: 410-934-9802
Email: kli26@jhu.edu

**Comment by danpovey** [comment]
What I mean is that previous to your changes, all invocations should have
had 2 arguments, but some had only 1 argument.

Now all should have 3.  Fixing this may involve some research on either
Debian or Red Hat.
BTW, please don't leave either of your OpenSuse instances running when you
are not using them.  You can 'stop' them using the interface.  My Google
cloud credits seem to have run out, so I am now paying for this.
Dan

**Comment by danpovey** [comment]
I already merged this from a different pull request -> deleting.

**Pull request closed without merging**
