### PR TITLE
Csj egs

### PR DESCRIPTION
**Pull request by sw005320**
In the CSJ recipe
- Fixed minor bugs
- Tuned some parameters, and updated the results
- Fixed "#!/usr/bin/env perl" issues

### CODE REVIEW

**Comment by danpovey** [comment]
@jtrmal, I don't have time to check this right now, so I'll wait for you to merge this.

**Comment by jtrmal** [comment]
Thanks for the update. I'm ok with merge.
BTW -- it's generally suggested (in the google style guide) to avoid spaces
at the end of the lines -- such as you have in the path.sh on line
+#export LC_ALL=C

y.

**Comment by danpovey** [comment]
To fix spaces at the ends of lines, you can put in your .emacs
(add-hook 'write-file-hooks 'delete-trailing-whitespace)

**Comment by sw005320** [comment]
OK
I will do it!
(Maybe I could not do all of them)

**Comment by jtrmal** [comment]
OK, merging. It still would be great if you could fix the white spaces.
Thanks for maintaining the recipe!
y.

**Pull request merged**
