### PR TITLE
add default args for arpa sampling test

### PR DESCRIPTION
**Pull request by keli78**
The two args are 1) a small ARPA file and 2) a history file which is in directory rnnlm/test/

### CODE REVIEW

**Comment by danpovey** [comment]
Please don't do it this way, it will be confusing for people who are
looking at that makefile.  Instead, if no args are supplied, act as if the
args have those default values.

**Comment by keli78** [comment]
@danpovey  I fixed it.

**Comment by jtrmal** [comment]
I don't think this is right...   Your change will cause each test binary to be called with the given arguments.
I'd suggest modifying the default rule so that it looks for a variable called
binary_name_ARGS (for example rnnlmtest_ARGS) and if it does exist, it runs the binary with the given arguments.
y.

**Comment by danpovey** [comment]
Ke, I think you misunderstood what I was asking for.
I meant to change the C++ code of the binary.
It's almost never a good idea to change something global just to fix
something local.

**Comment by keli78** [comment]
Oh, got it.

**Pull request merged**
