### PR TITLE
Further reductions on Docker image size

### PR DESCRIPTION
**Pull request by kir4h**
Signed-off-by: Andres Alvarez <kir4h.gh@gmail.com>

Following the suggestions by @kkm000  in https://github.com/kaldi-asr/kaldi/issues/4228#issuecomment-678452211, some extra deletions for further reduction on the image size. 

We are going down from `5.26GB` to `3.88GB` on the regular one and from `8.21GB` to `6.83GB` on the gpu version

```
kir4h/kaldi                                             gpuv2                           8be3bd9043ff        4 minutes ago       6.83GB
kir4h/kaldi                                             v2                              9ae588678bac        46 minutes ago      3.88GB
kir4h/kaldi                                             gpu                             d2fe407ffe3b        4 days ago          8.21GB
kir4h/kaldi                                             latest                          141039043d6f        4 days ago          5.26GB
kaldiasr/kaldi                                          gpu-latest                      0b92c53f2ef1        3 months ago        14.9GB
kaldiasr/kaldi                                          latest                          b44678467882        3 months ago        11.6GB
```

### CODE REVIEW

**Comment by daanzu** [comment]
Regarding not including support for pre-AVX CPUs (as discussed in the above referenced comment), let me throw in one vote for instead maintaining support for pre-AVX CPUs, unless it saves a lot of space. (An old server in a lab with a bunch of pre-AVX cores and RAM is great for running some big non-critical Kaldi jobs.) I figure the Docker images are meant to be easy to pull and run on whatever hardware you have, and anyone very particular about the size of the image would presumably already want to modify it to only include the parts of Kaldi that they are actually using.

**Comment by kir4h** [comment]
> Regarding not including support for pre-AVX CPUs (as discussed in the above referenced comment), let me throw in one vote for instead maintaining support for pre-AVX CPUs, unless it saves a lot of space. 

It´s around 357MB according to the comment. Lots for a regular Docker image, but not so much for a 4GB image

> I figure the Docker images are meant to be easy to pull and run on whatever hardware you have, and anyone very particular about the size of the image would presumably already want to modify it to only include the parts of Kaldi that they are actually using.

I'm pretty new to Kaldi so I'm not yet even aware of the different parts. I guess if we manage to improve the way we are building Kaldi Docker image (and we can build different images we can then combine into different final images) we could even have several Docker images for different scenarios (not currently doable because building the image is extremely heavy)

@daanzu @kkm000 should I leave the pre-AVX part then for the time being?

**Comment by jtrmal** [comment]
IMO  AVX is a minimum reasonable HW capability
y.

**Comment by daanzu** [comment]
> It´s around 357MB according to the comment. Lots for a regular Docker image, but not so much for a 4GB image

I think that 350MB figure also includes the savings from removing the MIC/threading/iLP64 stuff as well (which all seem eminently worthless to keep), in addition to just the pre-AVX support. Assuming the `_mc.?` files are the pre-AVX, that is only ~130MB, but I don't know how `_mc`/`_mc2`/`_mc3` differ (maybe some level of SSE? the user manual isn't clear).

```
45M     /opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64_lin/libmkl_mc.so
11M     /opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64_lin/libmkl_vml_mc2.so
11M     /opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64_lin/libmkl_vml_mc3.so
47M     /opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64_lin/libmkl_mc3.so
11M     /opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64_lin/libmkl_vml_mc.so
```

**Comment by kkm000** [comment]
@kir4h, @daanzu, yes, different sets of SSE instructions, and I estimated 350M all together with that stuff. And 130MB is still130 MB more than nothing. Given that releases are frequent, that may be a factor. As for an "old lab full of Pentium 4s", everyone can build their own image, or, even better, their own Kaldi, as we always did before Docker was a fad. I would not inconvenience the absolute majority of users with an extra size. I agree with @jtrmal, a non-AVX CPU is hard to come by these days.

**Comment by danpovey** [comment]
@kkm please take care of merging this when appropriate...

**Comment by kkm000** [comment]
@dpovey, sure, I'm not missing it—just usually do not do code reviews right after I wake up and just before crashing :)

**Comment by kkm000** [comment]
Merging, thanks.

**Pull request merged**
