### PR TITLE
sequitur: try to work out the correct  compilation flags

### PR DESCRIPTION
**Pull request by jtrmal**
should be resolving #1107

### CODE REVIEW

**Comment by jtrmal** [comment]
@danpovey  I didn't head from that guy, but I think this is a safe change w.r.t. linux, sounless you object, please merge. Or we can drop it, as we didn't have any more reports on issues about this.

**Comment by danpovey** [comment]
Can you see why the check failed?  It looks like it's not finding src/base/version.h.  Could it be a problem with the recent changes to the travis setup?

**Comment by jtrmal** [comment]
@kkm000  added some code that prints additional info after a run (and the version is one of those info) but the file won't get created when there was only a change outside src/ (when we were starting with travis, we decided not to compile everything if there was only a change in egs and/or tools)

**Comment by danpovey** [comment]
Hm, OK.  I guess that needs to be fixed somehow?  Because it caused the
build to fail.

**Comment by jtrmal** [comment]
Hopefully will be addressed by #1827 (I'll restart build of this if/when the fix gets merged).

**Pull request merged**
