### PR TITLE
Avoid segfault in wav-reverberate

### PR DESCRIPTION
**Pull request by jfainberg**
Using --additive-signals without also setting --snrs and --start-times
produces a segmentation fault when calling AddNoise (snr_vector and
start_time_vector empty). Will check that these arguments are set and
that their length matches the number of added signals. Not sure 
whether the check for empty arguments is superfluous when we have 
the assertions later on.

Alternatively, could set more sensible default values for snrs and
start_times, e.g. 0 for all additive signals in both snrs and
start_times?

### CODE REVIEW

**Comment by vijayaditya** [comment]
Looks good, I will merge when the checks pass. Please check the reasons for failure.

**Comment by jfainberg** [comment]
Great! Though I'm confused by the build fail. If I'm understanding the travis build correctly, it looks like it failed building openfst, or didn't succeed downloading it? This commit hasn't touched the tools directory... Is there a way to re-run the build?

**Comment by vijayaditya** [comment]
@jfainberg  I am unable to find the option to restart the build. So

**Comment by vijayaditya** [comment]
@jfainberg I restarted the tests, lets wait and see.

**Comment by jfainberg** [comment]
Thanks! Unfortunately it failed at the same place... Bit confusing why it would fail, but I'll try to debug...

**Comment by jtrmal** [comment]
The issue was caused by one of our previous commits, where we added checks
for "which" into check_dependencies.sh
Investigating fix
y.

**Comment by jtrmal** [comment]
Fingers crossed, will be fixed by #1043 (lets wait until the build finishes)

**Comment by jtrmal** [comment]
Just re-opened the PR to restart travis checks.

**Comment by jfainberg** [comment]
@jtrmal Thank you!

**Pull request merged**
