### PR TITLE
get_ctm_edits.py parses the transcriptions containing semicolon

### PR DESCRIPTION
**Pull request by sih4sing5hong5**
https://groups.google.com/d/msg/kaldi-help/BaXSEJGFip4/_DqTrv34CAAJ

* moved `get_ctm_edits.py`,	`segment_ctm_edits.py`, `get_non_scored_words.py`, `modify_ctm_edits.py`,	`taint_ctm_edits.py` into `interval/`
* fixed filenames in error messages

### CODE REVIEW

**Comment by danpovey** [comment]
Please check carefully that those scripts whose locations you moved are not
called from other scripts elsewhere.

**Comment by sih4sing5hong5** [comment]
I checked by `grep` and github search.

**Comment by sih4sing5hong5** [comment]
I rerun cleanup with this version now.

**Comment by sih4sing5hong5** [comment]
I had run without any error.

**Comment by danpovey** [comment]
Thanks!  Merging.

**Pull request merged**
