### PR TITLE
Hi mia

### PR DESCRIPTION
**Pull request by nwpuaslp**
Fix some bug in hi_mia

### CODE REVIEW

**Comment by nwpuaslp** [comment]
There are some code update to hi_mia and add the Result for posterior kws

**Comment by danpovey** [comment]
Can you please fix the conflicts?

**Comment by nwpuaslp** [comment]
[egs]change the k1 name to w1

**Comment by kkm000** [comment]
LGTM, thanks, merging. I did not go through every detail, assuming it runs.

**Pull request merged**
