### PR TITLE
[build] enable compilers gcc 10 and 11 when cuda>=11.4

### PR DESCRIPTION
**Pull request by jtrmal**
@kkm000 if you care...

### CODE REVIEW

**Comment by jtrmal** [comment]
I took your changes, fixed up two little detail and resolved conflicts. Wanna compile on linux also (probably during the evening) before I commit. FOr now, tested out on macos

**Comment by jtrmal** [comment]
seems like now even Travis is happy. I'll merge

**Comment by kkm000** [comment]
Sure, LGTM. I was looking at the travis script, which always installs portaudio even for the job that won't use it, but this part needs a bigger rework anyway.

**Comment by kkm000** [comment]
If Travis is happy, and you tested on a Mac, I'm happy, too! Thanks, really! I'm sorry for dragging on with my Kaldi stuff.

I am fighting with my computer problems, on top of other things: three dead notebooks this year. Two of the late were brand new, one DOA, another in 6 weeks, and I just got a call from HP that they'll ship a new one not in 1 week, as said the standard "we received your untimely passed one" notification, and not in mid-July, as another SMS next day said, but in 3-4, but they're "working" on ASAP. My desktop is past due for an upgrade by 5 years or so, I guess... But if all else fails, I have a Raspberry Pi! :-)

**Comment by jtrmal** [comment]
I thank _you_. I didn't do much. You did the work.
y.

**Pull request merged**
