### PR TITLE
Removed bug introduced due to commit 25904766b473ef8609b077ec52eb9854…

### PR DESCRIPTION
**Pull request by vijayaditya**
…cf5d993c

### CODE REVIEW

**Comment by danpovey** [comment]
branch has conflicts!  please update.

**Comment by vijayaditya** [comment]
Done.

**Comment by vijayaditya** [comment]
This PR is looking very strange, something messed up. I am resubmitting.

**Comment by danpovey** [comment]
you haven't resubmitted yet- surely it can't be that complicated?

**Pull request closed without merging**
