### PR TITLE
Documentation changes related to Git migration

### PR DESCRIPTION
**Pull request by kkm000**
Added Git tutorial, removed Subversion tutorial and updated multiple references from Subversion to Git and from SourceForge to Kaldi's own web site or GitHub as appropriate.

Please comment on particular issues in-line on GitHub page as the change list is large.

**EDIT**: Many whitespace changes here because of my emacs setup. Add `?w=0` to the end of the URL to show only non-whitespace changes, e. g.

https://github.com/kaldi-asr/kaldi/pull/50/files?w=0

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.. couple of points;
regarding dependencies, we still depend on svn being installed to install
some other stuff.

Regarding this, "
We still intend to maintain a+ read-only Subversion mirror of the GitHub
parent, located at SourceForge and mirrored+ by us."
this is no longer the plan, because Sourceforge lost our latest svn commits
and if we attempt to keep the SF up to date, existing SF users would likely
get corrupted copies of Kaldi.
There is a todo in your commit:
+\todo This paragraph is full of lies!
it would be good if you can find time to fix this before we merge the pull
request.
Dan

**Comment by jtrmal** [comment]
BTW, one more comment (of low importance, probably shouldn't be an an
obstacle in merging this PR): I think we can say nicer things about the
windows built now.
I wouldn't claim it's actively supported but the sentence there (woefully
old, or something like that) is too grim :)
y.

**Comment by kkm000** [comment]
@jtrmal:
> probably shouldn't be an an obstacle in merging this PR

I think it should :-) As a sidekick thought, a PR might well represent a completed unit of work, since it is merged into the master branch as a functional feature. It makes perfect sense to discuss the changes and iteratively modify the change until it is logically complete. Git much better suited for this than svn, as it is much easier with it to have multiple branches and multiple PRs going at a time. So...

> we can say nicer things about the windows built now.

...I'll change this later today, do not merge.

**Comment by kkm000** [comment]
@danpovey, @jtrmal, out of curiosity, are you getting a notification from GitHub when I push a commit to the existing PR? In the tutorial, I assumed not.

**Comment by jtrmal** [comment]
No, I didn't get informed about the last commit.
y.

**Comment by kkm000** [comment]
Aha, and Dan was, although that was an out-of-thread e-mail message with a new subject! NB the commit message did literally contain  `@danpovey`, and this one did not mention you. Interesting. Looks like GitHub would not notify the owner of the target repo of a push to the existing PR.

I have a line mentioning to respond with something like "Done" in the thread--looks like it makes total sense. Thanks for checking!

**Comment by jtrmal** [comment]
OK, I guess it's ready to merge?

**Comment by danpovey** [comment]
I guess.
Won't hurt to merge it in any case.  After you merge, I'll compile.
Dan

**Comment by danpovey** [comment]
Thanks.  Compiling now. Yenda, in a few minutes the docs will appear
online, could you please make sure there are no gross formatting errors?
Dan

**Comment by jtrmal** [comment]
yep, will do. y.

**Comment by jtrmal** [comment]
everything seems fine.
y.

**Comment by kkm000** [comment]
@jtrmal Thanks for checking.

**Pull request merged**
