### PR TITLE
Tedlium chain pr 3

### PR DESCRIPTION
**Pull request by galv**
Rebased version of #644

### CODE REVIEW

**Comment by vijayaditya** [comment]
As these scripts are from #644, which was well reviewed, I just performed a cursory check. Changes are OK. Assuming the RESULTS have been updated I am performing the merge.

**Comment by galv** [comment]
Alas, I never actually put these into the RESULTS file.

By the way, I don't think you should have squashed these two commits together. The first commit fixes a bug affecting all TEDLIUM recipes.

**Comment by vijayaditya** [comment]
The commit message reports both the changes I think it is OK to squash.

Don't worry about the RESULTS file you can fix that in your next commit, it
is fine as you have the results in the individual scripts.

--Vijay

**Comment by galv** [comment]
But now someone will have to dig through through a rather big commit to find the first change. Anyway, it's done.

**Pull request merged**
