### PR TITLE
Digits data

### PR DESCRIPTION
**Pull request by abhisheksethi**

### CODE REVIEW

**Comment by jtrmal** [comment]
Thanks.
Can you please remove the data from the PR and prepare a separate submission to openslr.org? Please read http://openslr.org/contributions.html how to do it.

There is a couple of other things that will have to be changed, but we can talk about it afterwards.

**Comment by jtrmal** [comment]
BTW, I'm slightly concerned about you using (probably) copyrighted material to cut out the audio, but perhaps using these small chunks falls into a fair-use?

**Comment by danpovey** [comment]
perhaps you could think of a more specific name for this setup?

**Comment by rain1024** [comment]
@johnaegard Firstly, thank for create an useful dataset for newbies like me get in touch with Kaldi more quickly.

Secondly, I have a question, I am following [tutorial's Exemplary Project](http://kaldi-asr.org/doc/kaldi_for_dummies.html#kaldi_for_dummies_tools), use your dataset.

I've already add `sample-frequency` in `mfcc.conf` file

```
--use-energy=false   # only non-default option.
--sample-frequency=44100
```

But when I run `run.sh` script, it yield error in `TRI1 TRAINING` (MONO TRAINING works well)

Here is the error log

```
===== TRI1 (first triphone pass) TRAINING =====
 
steps/train_deltas.sh --cmd run.pl 2000 11000 data/train data/lang exp/mono_ali exp/tri1
steps/train_deltas.sh: accumulating tree stats
steps/train_deltas.sh: getting questions for tree-building, via clustering
steps/train_deltas.sh: building the tree
bash: line 1: 30295 Aborted                 (core dumped) ( build-tree --verbose=1 --max-leaves=2000 --cluster-thresh=-1 exp/tri1/treeacc data/lang/phones/roots.int exp/tri1/questions.qst data/lang/topo exp/tri1/tree ) 2>> exp/tri1/log/build_tree.log >> exp/tri1/log/build_tree.log
run.pl: job failed, log is in exp/tri1/log/build_tree.log
```

You can view [full log here](https://pastebin.com/FTubRHPb)

Did you train `TRI1 TRAINING` successfully?

**Comment by danpovey** [comment]
this kind of question should go to kaldi-help, not here.  you should read what's on the screen more carefully.  It says "log is in exp/tri1/log/build_tree.log".  the actual error message will be in that file.

**Pull request closed without merging**
