### PR TITLE
aspire : added blstm+chain recipe and blstm+xent recipe

### PR DESCRIPTION
**Pull request by vijayaditya**
I will add the results when the experiments are complete. This BLSTM recipe has self-repair in ClipGradient component which makes the training very stable. The plot below shows the training/CV likelihood plots for BLSTMs and TDNNs using the xent objfn. 

There are some modifications necessary in the decoding script, as there is no reduction in WER compared to TDNNs.

image

### CODE REVIEW

**Comment by vijayaditya** [comment]
The BLSTM+Chain recipe is giving good improvements over TDNN+chain recipe.

Below results are at iteration 500/1596

```bash
%WER 27.7 | 2120 27223 | 79.2 13.0 7.8 6.9 27.7 77.4 | -0.811 | exp/chain/blstm_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v7_iter500_pp_fg/score_9/penalty_0.25/ctm.filt.filt.sys
%WER 28.7 | 2120 27218 | 77.1 13.8 9.1 5.8 28.7 77.0 | -0.566 | exp/chain/tdnn_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iter500_pp_fg/score_9/penalty_0.0/ctm.filt.filt.sys
```

I continue to have larger WERs when decoding with BLSTMs trained with xent objective function.

**Comment by vijayaditya** [comment]
BLSTM vs TDNN log-probability plots when trained with chain objective function.

image


[report.pdf](https://github.com/kaldi-asr/kaldi/files/400477/report.pdf)

**Comment by vijayaditya** [comment]
```bash
# Intermediate results at iteration 800/1600
#BLSTM
%WER 26.8 | 2120 27219 | 80.2 12.4 7.4 7.0 26.8 76.0 | -0.796 | exp/chain/blstm_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v7_iter800_pp_fg/score_9/penalty_0.25/ctm.filt.filt.sys

#TDNN
%WER 28.4 | 2120 27218 | 77.6 13.6 8.8 6.0 28.4 76.3 | -0.607 | exp/chain/tdnn_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iter800_pp_fg/score_9/penalty_0.0/ctm.filt.filt.sys

#TDNN final result
%WER 27.8 | 2120 27217 | 78.2 13.6 8.2 6.0 27.8 75.9 | -0.613 | exp/chain/tdnn_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iterfinal_pp_fg/score_9/penalty_0.0/ctm.filt.filt.sys

```

**Comment by vijayaditya** [comment]
I tried reducing the parameters in the chain model, however there was an increase in WER and no significant increase in speed (~25% faster).
```bash
#TDNN+chain with ~17 million parameters
%WER 28.2 | 2120 27218 | 77.3 12.5 10.2 5.6 28.2 75.6 | -0.544 | exp/chain/tdnn_asp_1/decode_dev_aspire_whole_uniformsegmented_win10_over5_v7_iterfinal_pp_fg/score_10/penalty_0.0/ctm.filt.filt.sys

#TDNN+chain with ~27 million parameters
%WER 27.8 | 2120 27217 | 78.2 13.6 8.2 6.0 27.8 75.9 | -0.613 | exp/chain/tdnn_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iterfinal_pp_fg/score_9/penalty_0.0/ctm.filt.filt.sys

# TDNN+xent with ~24 million parameters
%WER 31.0 | 2120 27217 | 74.8 16.1 9.1 5.9 31.0 77.9 | -0.707 | exp/nnet3/tdnn/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iterfinal_pp_fg/score_14/penalty_0.0/ctm.filt.filt.sys
```

**Comment by vijayaditya** [comment]
Overall 7.5% rel. improvement when using BLSTM+chain compared to TDNN+chain systems.

TDNN-27 million params
BLSTM-37 million params

Any attempt to reduce parameters in either of these systems led to WER increase. We might even be able to further increase the parameters in both these systems. However these experiments are too expensive.

```bash
#Total training time is 4 days, 4:17:26
#%WER 27.8 | 2120 27217 | 78.2 13.6 8.2 6.0 27.8 75.9 | -0.613 | exp/chain/tdnn_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iterfinal_pp_fg/score_9/penalty_0.0/ctm.filt.filt.sys

# Total training time is 10 days, 13:40:32
#%WER 25.7 | 2120 27216 | 81.1 11.2 7.8 6.8 25.7 76.1 | -0.906 | exp/chain/blstm_7b/decode_dev_aspire_whole_uniformsegmented_win10_over5_v7_iterfinal_pp_fg/score_9/penalty_0.25/ctm.filt.filt.sys
```

blstm_7b : 37 million param
blstm_asp_1 : 20 million param
tdnn_7b : 27 million param
tdnn_asp_1 : 17 million param
screen shot 2016-08-12 at 8 33 09 am

**Comment by vijayaditya** [comment]
```bash 
#blstm iteration 1700/2100  (~20 million parameters)
%WER 30.0 | 2120 27212 | 76.0 15.4 8.6 6.1 30.0 79.4 | -1.193 | exp/nnet3/lstm_bidirectional_sf/decode_dev_aspire_whole_uniformsegmented_win10_over5_v7_iter1700_pp_fg/score_13/pe

# TDNN+xent with ~24 million parameters
%WER 31.0 | 2120 27217 | 74.8 16.1 9.1 5.9 31.0 77.9 | -0.707 | exp/nnet3/tdnn/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iterfinal_pp_fg/score_14/penalty_0.0/ctm.filt.filt.sys
```

BLSTM+Xent finally crossed TDNN+xent model in WER.

screen shot 2016-08-16 at 9 35 30 pm

**Comment by vijayaditya** [comment]
BLSTM+xent training is done. However the frame level accuracies/log-likelihoods don't seem to have converged. I will continue the training for few more epochs, but this might take a week or two as we do not have sufficient GPU time. 

```bash 
#blstm+xent  (~20 million parameters)
%WER 29.4 | 2120 27210 | 77.0 14.7 8.3 6.4 29.4 77.9 | -1.227 | exp/nnet3/lstm_bidirectional_sf/decode_dev_aspire_whole_uniformsegmented_win10_over5_v7_iterfinal_pp_fg/score_13/penalty_0.25/ctm.filt.filt.sys

# TDNN+xent with ~24 million parameters
%WER 31.0 | 2120 27217 | 74.8 16.1 9.1 5.9 31.0 77.9 | -0.707 | exp/nnet3/tdnn/decode_dev_aspire_whole_uniformsegmented_win10_over5_v6_200jobs_iterfinal_pp_fg/score_14/penalty_0.0/ctm.filt.filt.sys
```
screen shot 2016-08-22 at 11 41 38 pm
screen shot 2016-08-22 at 11 44 12 pm

**Comment by vijayaditya** [comment]
We could further tune the xent models to have larger number of parameters, as even chain models with larger number of parameters do not seem to overfit. But this is not of interest as we would anyway not be using xent models.

**Comment by vijayaditya** [comment]
@danpovey The PR is ready for review and merge. I will be cleaning up these scripts a lot in the next 2 weeks 
1.  to include the latest cleanup_segmentation stage from tedlium.
2. to have cleaner chain recipes

However I would like to do these in a separate PR, which will be submitted after correcting the issue #966 .

**Comment by danpovey** [comment]
OK, I'll merge.
It would be interesting to try the data-cleanup script when you get a chance.
It's impressive how much the chain models have reduced the WER-- Mary would probably be interested to hear about this.

**Pull request merged**
