### PR TITLE
Create lattice-lmrescore-cuedrnnlm

### PR DESCRIPTION
**Pull request by rickychanhoyin**

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks-- do you have any example of using this?  Like example scripts for
some setup?

Dan

**Comment by danpovey** [comment]
@hainan-xv, I think you have some setup where you were trying to do
rescoring with this.. perhaps you could try out his binary?

**Comment by rickychanhoyin** [comment]
The scripts for rescoring is in #879

**Comment by hainan-xv** [comment]
Sure.

I am working on a MT paper deadline on the 11th. I probably do not have
much time before then for this...

On Sun, Jul 3, 2016 at 12:35 AM, Daniel Povey <notifications@github.com>
wrote:

> @hainan-xv, I think you have some setup where you were trying to do
> rescoring with this.. perhaps you could try out his binary?
>
>
> On Sat, Jul 2, 2016 at 9:30 PM, Daniel Povey <dpovey@gmail.com> wrote:
>
> > Thanks-- do you have any example of using this? Like example scripts for
> > some setup?
> >
> > Dan
> >
> >
> > On Sat, Jul 2, 2016 at 9:22 PM, rickychanhoyin <notifications@github.com
> >
> > wrote:
> >
> >> Reopened #877 <https://github.com/kaldi-asr/kaldi/pull/877>.
> >>
> >> —
> >> You are receiving this because you are subscribed to this thread.
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/kaldi-asr/kaldi/pull/877#event-711323118>, or mute
> >> the thread
> >> <
> https://github.com/notifications/unsubscribe/ADJVu24hsjeatMIgYYcsMTFQl6RKGrMrks5qRzkbgaJpZM4JDzMQ
> >
> >> .
> >>
> >
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/877#issuecomment-230135007>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMCDpkdHleNAvG8AWUc1mc9Y2gGzcmIks5qRzwDgaJpZM4JDzMQ>
> .
>



-- 
- Hainan

**Pull request closed without merging**
