### PR TITLE
configure, refactored selection of GPU architectures

### PR DESCRIPTION
**Pull request by vesis84**
- moved from src/cudamatrix/Makefile to src/configure
- also fixes bug from xie7132524@gmail.com

### CODE REVIEW

**Comment by danpovey** [comment]
This seems like an improvement but I'd like to test it out to-morrow so not merging right away.

**Comment by danpovey** [comment]
@hainan-xv, could you please test this out that it works for us?  Obviously run configure on a GPU machine.

**Comment by hainan-xv** [comment]
Sure. I will do it by tonight.

On Wed, Mar 30, 2016 at 1:56 PM, Daniel Povey <notifications@github.com>
wrote:

> @hainan-xv <https://github.com/hainan-xv>, could you please test this out
> that it works for us? Obviously run configure on a GPU machine.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/630#issuecomment-203552645>
>



-- 
- Hainan

**Comment by hainan-xv** [comment]
Should I test the compilation and make test only, or should I also test it for some real data, like RM?

**Comment by danpovey** [comment]
Just test compilation and make test

**Comment by hainan-xv** [comment]
All tests passed on t01.

On Wed, Mar 30, 2016 at 5:22 PM, Daniel Povey <notifications@github.com>
wrote:

> Just test compilation and make test
>
> On Wed, Mar 30, 2016 at 5:20 PM, hainan-xv <notifications@github.com>
> wrote:
>
> > Should I test the compilation and make test only, or should I also test
> it
> > for some real data, like RM?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kaldi-asr/kaldi/pull/630#issuecomment-203640321>
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/630#issuecomment-203640821>
>



-- 
- Hainan

**Comment by danpovey** [comment]
Karel, have you tested that it works as intended when you update an existing repository to have this without re-running configure?
I think it would be better if you change the error:
 $(error CUDA_ARCH is undefined, run 'src/configure')
to be a little clearer this resulted from a script change, unless people are confused why a previously working setup would now stop working.
How about:
 $(error The mechanism for configuring CUDA has changed, please re-run 'src/configure')

**Comment by jtrmal** [comment]
To me, incrementing the value would be a simpler solution without introducing any new complexity in the scripts. I think people running in sync with github recognize the fact they might have to reconfigure and recompile. Reconfiguration is as easy as taking the second line from kaldi.mk and run it again.
But I don't care too much.
y.

**Comment by vesis84** [comment]
Yes, increasing the value is a good solution. I suppose most of the researches use kaldi with CUDA extensions anyway, while for others the reconfigure is not needed, but causes no harm if done.
I'll update the constant in 'configure'.
K.

**Comment by danpovey** [comment]
Karel, I just realized that we have another directory where we compile GPU stuff-- the chain directory.  Would you mind changing that also?

**Comment by vesis84** [comment]
Okay, src/chain/Makefile is now updated.

**Comment by danpovey** [comment]
OK, thanks.  Merging.

**Pull request merged**
