### PR TITLE
modify test code to guarantee loop only run once if no GPU

### PR DESCRIPTION
**Pull request by keli78**
have tested both with and without GPUs and the results are what we expect.

### CODE REVIEW

**Comment by keli78** [comment]
@danpovey The travis CI build failed but there was no problem on my local branch. Not sure what's the reason for this.

**Comment by danpovey** [comment]
Looks like a problem with travis itself.
Make a small change (e.g. add a newline) and push it, it will cause it to
re-build.

**Comment by keli78** [comment]
Hi @danpovey the checks have passed.

**Comment by danpovey** [comment]
ok thanks, merging.

**Pull request merged**
