### PR TITLE
Initial version of Docker images for (CPU and GPU versions)

### PR DESCRIPTION
**Pull request by mdoulaty**
(I'll updated the README file to point to the Kaldi repo on DockerHub before merging)

### CODE REVIEW

**Comment by galv** [comment]
@danpovey Yep, this looks fine. Again, though, I'd like to see how this can integrate with a continuous integration system. That way, the Dockerfiles don't become abandoned.

**Comment by mdoulaty** [comment]
re the CI integration, I'll try DockerHub first (for CPU only images)
for the GPU-based images I think we need a VM with GPU to build the image there. Probably have to write some scripts that create a VM somewhere, build, tag and push the image and then tear down the env. Then all we need to do on the CI side is to call this script whenever something's merged
(at icassp this week, probably will setup dockerhub next week)

**Comment by danpovey** [comment]
OK, since @galv says this is fine I will merge.  Since I don't fully understand all the issues around this, I hope @mdoulaty  will continue to be available to help with it.

**Comment by mdoulaty** [comment]
yes, I'll be available to continue working on this
will work with @galv for the automation of builds

**Pull request merged**
