### PR TITLE
WIP: Cluster nonsilence phones for aishell

### PR DESCRIPTION
**Pull request by naxingyu**
to share the roots of the different tones of each phone.
This will change the results.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.  But would you mind testing it- seeing how it affects the results?

**Comment by naxingyu** [comment]
Yes, I'm running the test. That's why I put WIP in the title. It's a
placeholder.

**Comment by naxingyu** [comment]
@danpovey Here are the GMM results.

test CER% | non-cluster | cluster
---------|------------|--------
mono   | 33.82 | 36.41
tri1 (delta) | 19.39 | 18.76
tri2  (larger delta) | 19.23 | 18.64
tri3a (lda+mllt) | 17.14 | 17.04
tri4a (sat) | 13.64 | 13.82
tri5a  (larger sat) | 12.23 | 12.12

One thing worth noticing, after using clustered non-silence-phones, the `number of transition-ids` is increased from 6306 to 10160 and `number of transition-states` is increased from 3149 to 5076, while `number of pdfs` barely changes. This result in an larger graph in the tri5a experiment, 205M, compared with 175M in the non-clustered setting.

**Comment by danpovey** [comment]
Thanks.   Let's wait to see the effect on the chain system.

**Comment by naxingyu** [comment]
Comparing chain models trained using online pitch with right context 25.

test CER% | non-cluster | cluster
-- | -- | --
chain | 7.53 | 7.45
+online decoding | 7.55 | 7.43
+per-utt | 8.03 | 7.92

The size of decoding graph of the chain models barely change.

**Comment by danpovey** [comment]
Oh, OK.  That's great.  Would you mind changing  the RESULTS file and the results in the chain script that you ran?  You can compare the two things in a comment there and explain what you were comparing.

**Comment by naxingyu** [comment]
I'm thinking of running a non-online recipe as well. Because the recommended chain recipe of aishell is run_tdnn_1a(offline pitch), not run_tdnn_2a(online pitch). I have both offline and online results in the general RESULTS file.
Regarding the results in the chain script, do you mean comparison w/ or w/o clustered phones?

**Comment by danpovey** [comment]
OK.
and yes.

**Comment by danpovey** [comment]
Great, thanks.  I think those changes may mostly be random noise.    Merging, as it's the right way to set this up.

**Pull request merged**
