### PR TITLE
Add Wit Zieliński tutorial

### PR DESCRIPTION
**Pull request by akreal**
As discussed in #802, it is formatted as regular doxygen.

### CODE REVIEW

**Comment by danpovey** [comment]
I'm going to merge this as-is and compile it and put it up at kaldi-asr.org-- please look over the result to see if there are any problems!

**Comment by akreal** [comment]
It looks good on kaldi-asr.org.

**Comment by wantee** [comment]
There is some problems with the tree view in the left frame on kaldi-asr.org. The subpages in mainpage are messed up with the modules in a single root.
I am not sure since when this problem appeared, it seems not related with the codes. Maybe you use a different version of doxygen, @danpovey?

**Comment by danpovey** [comment]
Yes, I think our version of Doxygen increased when we upgraded our grid to
a new Debian version recently.  We have 1.8.8 now.  I have never fully
understood how to control the left frame of the tree view.  If you can
figure it out it would be nice.
Dan

**Pull request merged**
