### PR TITLE
upgrade the sox calls to use more compatible options

### PR DESCRIPTION
**Pull request by jtrmal**
@vijayaditya @pswietojanski 
I did a run on the s5b recipe until mono-training and it seemed to work fine as far as I can tell.
do you wanna do more careful checks?

### CODE REVIEW

**Comment by vijayaditya** [comment]
Could you just confirm that the dynamic range of the sox output is the same as before ?

Only concern I have is that the nnet3 models which do not have mean variance normalization might be affected if there is any change in the dynamic range of the waveforms.

**Comment by vijayaditya** [comment]
otherwise LGTM.

**Comment by danpovey** [comment]
i think it should be safe, I've found online refs to an error message
saying:
Error: /usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-
integer' instead

**Comment by vijayaditya** [comment]
OK merging.

**Pull request merged**
