### PR TITLE
Enhancing confidences,

### PR DESCRIPTION
**Pull request by vesis84**
Hi, during the MGB evals I have updated the way how confidecnes are computed inside 'lattice-to-ctm-conf'. The idea is to be able to score the 'reference transcripts', to calculate its confidence by using a lattice 'unioned' with the aligned transcripts. To make it work, we need to properly initialize the 'sausage bins' both with the word-sequence as well as begin/end times of bins...

Could you please look at the code? I also added a class `MinimumBayesRiskOptions` and added the support to print the CTM even with the epsiolon bins, some of them have zero duration... But other <eps> bins will have non-zero duration and a low confidence here will indicate that there's a word missing from 'reference transcript' ...

Best, Karel.

### CODE REVIEW

**Comment by vesis84** [comment]
Hmm, it says that we run out of time for the Travis test :(
`The job exceeded the maximum time limit for jobs, and has been terminated.`

Is it possible to configure it somehow?

**Comment by jtrmal** [comment]
no, but we can restart that test again.
y.

**Comment by jtrmal** [comment]
(which I did just now).
y.

**Comment by vesis84** [comment]
Perfect! Now it passed ;)

**Comment by vesis84** [comment]
@danpovey Can you please take a look ?

**Comment by danpovey** [comment]
Sorry I didn't get to it yesterday, will try to get to it today.

**Comment by danpovey** [comment]
This looks straightforward-- merging.

**Pull request merged**
