### PR TITLE
Change KALDI_LOG to KALDI_VLOG(1) in ComputeDerivedVars()

### PR DESCRIPTION
**Pull request by davidavdav**
In our production system, this logging is the only verbose part in normal operation, and it appears 
to be a bit spurious, it would be nicer to have this level of verbosity reduced.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks for the PR, but I don't think I'll merge-- that message is useful in explaining a delay to the user when run directly from the command line (else they'd think the decoding was inherently slow).

**Comment by davidavdav** [comment]
Mmm okay, sure, in our perception this takes hardly any time compared to
regular posterior computations, but I can't vouch for others.

Cheers,

---david ( 大卫)

Op 4 aug. 2017 20:54 schreef "Daniel Povey" <notifications@github.com>:

Closed #1794 <https://github.com/kaldi-asr/kaldi/pull/1794>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kaldi-asr/kaldi/pull/1794#event-1193643682>, or mute
the thread

**Comment by danpovey** [comment]
For a normal-size ivector extractor it takes many seconds, and it also uses
multiple threads by default I think.  If you have set up your production
system in such a way that this message is printed other than at startup,
then you are wasting a lot of CPU cycles.

**Comment by davidavdav** [comment]
Yes, sure, for a proper speaker recognition setup this probably takes quite some time, but in our ASR setups, with i-vector dimensions of 100, it is fairly fast. Anyway, it is only two lines at the start up, so we can probably deal with it.  Or we will just rebase this patch for ourselves every time we sync with upstream Kaldi.

**Pull request closed without merging**
