### PR TITLE
Update cu-device.cc

### PR DESCRIPTION
**Pull request by tal1974**
windows VS2013 CUDA 7.0 or 7.5 function cuMemGetInfo has 2 argumets

### CODE REVIEW

**Comment by jtrmal** [comment]
THanks -- while we are at it, can you please have a look at line 450, where the call is made again and fix it? Actuall, if I read the code correctly, that statement will never get active -- in that case you can remove it.

**Comment by tal1974** [comment]
Yes, 450 line is dead. I remove it, but can check this code on my mashine.

**Comment by tal1974** [comment]
I mean I checked for case _MSC_VER. Maybe someone else can check code for case  "not _MSC_VER"?

**Comment by danpovey** [comment]
I'm pretty sure if there is any problem with the code it's with _MSC_VER,
since things are used frequently on UNIX.

Dan

**Comment by jtrmal** [comment]
Thanks, merging!

**Pull request merged**
