### PR TITLE
Low-rank affine component in the xent branch of chain models

### PR DESCRIPTION
**Pull request by GaofengCheng**
adding a low-rank module pre xent branch, training is running, results will be updated later

### CODE REVIEW

**Comment by vijayaditya** [comment]
you might want to update your branch before submitting this PR.

**Comment by vijayaditya** [comment]
Addresses #957

**Comment by GaofengCheng** [comment]
tdnn_7l (based on 7h),time consuming 48.18s(one iter),time reduction 10.1% relative to 7h:
```
%WER 12.88 [ 6240 / 48460, 797 ins, 1507 del, 3936 sub ] exp/chain/tdnn_7l_sp/decode_train_dev_sw1_fsh_fg/wer_9_0.0
%WER 14.7 | 4459 42989 | 87.0 8.6 4.3 1.7 14.7 50.3 | exp/chain/tdnn_7l_sp/decode_eval2000_sw1_fsh_fg/score_10_0.0/eval2000_hires.ctm.filt.sys
%WER 9.7 | 1831 21395 | 91.4 5.8 2.8 1.1 9.7 43.9 | exp/chain/tdnn_7l_sp/decode_eval2000_sw1_fsh_fg/score_10_0.0/eval2000_hires.ctm.swbd.filt.sys
xent:train/valid[173,261,final]=(-1.46,-1.37,-1.38/-1.55,-1.48,-1.48) logprob:train/valid[173,261,final]=(-0.099,-0.090,-0.090/-0.120,-0.116,-0.116)
```
tdnn_7h (my results),time consuming 53.56s(one iter):
```
%WER 12.65 [ 6129 / 48460, 723 ins, 1625 del, 3781 sub ] exp/chain/tdnn_7h_sp/decode_train_dev_sw1_fsh_fg/wer_10_0.0
%WER 14.7 | 4459 42989 | 87.0 8.6 4.4 1.7 14.7 50.0 | exp/chain/tdnn_7h_sp/decode_eval2000_sw1_fsh_fg/score_10_0.0/eval2000_hires.ctm.filt.sys
%WER 9.9 | 1831 21395 | 91.3 5.8 2.9 1.2 9.9 43.8 | exp/chain/tdnn_7h_sp/decode_eval2000_sw1_fsh_fg/score_10_0.0/eval2000_hires.ctm.swbd.filt.sys
xent:train/valid[173,261,final]=(-1.29,-1.21,-1.22/-1.39,-1.35,-1.35) logprob:train/valid[173,261,final]=(-0.099,-0.090,-0.090/-0.121,-0.118,-0.118)
```
tdnn_7h results from 7h scripts:
```
#WER on train_dev(fg)      12.84
#WER on eval2000(fg)       14.8
```
new 7l should be better than 7h @vijayaditya @danpovey 
@vijayaditya another problem ,I have update from kaldi/master before PR(done on the windows desktop), but there still remain many earlier commits, any advice?.....

**Comment by danpovey** [comment]
Great!
Vijay, merge if you think it's OK.  The 'squash and merge' button should work-- edit the commit message to remove the garbage commits.
Gaofeng, rebasing might fix the commit log, e.g. "git rebase upstream/master" (assuming 'upstream' is a remote that points to the official Kaldi repo).  But we don't need that.
Vijay, I notice the tnn 7j script does not have a comment at the top saying what it's about... please fix when you can.

**Comment by GaofengCheng** [comment]
@vijayaditya I will update the 7l results in the scripts, merge it later please

**Comment by GaofengCheng** [comment]
@vijayaditya I haven't solved the garbage commits problem, bother you to delete them when merging

**Comment by GaofengCheng** [comment]
redirected to #1213

**Pull request closed without merging**
