### PR TITLE
Chime4 egs

### PR DESCRIPTION
**Pull request by sw005320**
Simplify codes by using utils/validate_lang.pl, as suggested by the previous PR   #730 .

### CODE REVIEW

**Comment by jtrmal** [comment]
Looks much better now. Did you give it a test run?

**Comment by sw005320** [comment]
Yes, we tested it, and provided the same results.

**Comment by danpovey** [comment]
Could you please rebase this against master?  Merging patches that themselves contain merges of the master makes the history hard to view.

**Comment by sw005320** [comment]
Let me confirm the command.
git checkout chime4-egs
git rebase master
git checkout master
git merge chime4-egs

and finally push? (git push)

**Comment by danpovey** [comment]
No, it's

git checkout chime4-egs
git rebase master

and then git push

**Comment by sw005320** [comment]
Thanks!
I pushed it.

**Comment by danpovey** [comment]
I don't think you pushed it- at least, not to the correct place.

**Comment by danpovey** [comment]
Doing it myself, as a separate pull request.

**Comment by sw005320** [comment]
Sorry about that.

**Comment by danpovey** [comment]
In future it's best to rebase your local changes against master as you work
on your code, instead of merging master.  At least, if no-one else in your
team is working on the same repo.

**Comment by sw005320** [comment]
Thanks.
I will do that.

**Pull request closed without merging**
