### PR TITLE
Fast repeated affine component

### PR DESCRIPTION
**Pull request by galv**
For #441

Natural Gradient is not implemented. Tell me if that is needed; I'll have to take some time to understand the method.

The name "fast-mode" is a little optimistic. I did not test the relative speed of this yet. I've been distracted from building the chain model for TEDLIUM, and figured you (Dan) would want this ASAP.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks a lot!  Will review later today or to-morrow.  I'll do the natural
gradient stuff if needed.
Dan

**Comment by danpovey** [comment]
I think you forgot to add the fast_mode_ to Read() and Write().  Also make sure they are copied in the copy-constructor (needed in Copy()).

**Comment by galv** [comment]
The copy constructor does in fact copy fast_mode_. See: [this line](https://github.com/galv/kaldi/commit/71ac1300b285a7a7fb484a6ec3b02e5972ab3232#diff-9dce7a91d342f07a96b9d469c8f075b1R941).

You're right on Read() and Write(), though. Sorry I let this slip by.

**Comment by galv** [comment]
Also: WriteUpdatableCommon() and ReadUpdatableCommon() both handle serializing is_gradient_, but you can see all the simple components' serialization methods reading and writing is_gradient_ themselves. Eck. Is it like this for backwards compatibility with previously serialized models?

**Comment by danpovey** [comment]
Thanks- you'll need back-compatibility code for Read().  Please make
fast-mode default to true; this will make my life easier in testing the
speed.
Dan

**Comment by danpovey** [comment]
BTW,  the function ReadToken will be used in the back-compatibility code.

**Comment by galv** [comment]
Great, thanks. I was about to say that ExpectToken would always print an error message even i the accompanying exception was caught.

**Comment by galv** [comment]
I've pushed a commit for Read and Write. The current test code makes it nontrivial to add a test for the backwards compatibility mode (which *does* set fast_mode_ to true), but I have thought about it for a while and am fairly positive it works.

**Comment by danpovey** [comment]
OK thanks.  I'll test the speed before I merge.

**Comment by danpovey** [comment]
@galv, it may be a while before I merge this, if at all... testing revealed that it was very flow.  I changed the order of the x, y and z indexes in CopyTensor3d and this helped, but it was still slower than the baseline, with too much time being taken in CopyTensor3d.  This is going to have to wait until I can look at it again.  I'll leave it up though, until I decide what to do about it.

**Comment by galv** [comment]
Unfortunately, I doubt anything else can be done at this point. CUBLAS
really can't be optimized further obviously, and Copy3dTensor must exist
because of the existence of padding in CuMatrix objects.

On Tue, Jan 12, 2016 at 11:00 PM, Daniel Povey <notifications@github.com>
wrote:

> @galv <https://github.com/galv>, it may be a while before I merge this,
> if at all... testing revealed that it was very flow. I changed the order of
> the x, y and z indexes in CopyTensor3d and this helped, but it was still
> slower than the baseline, with too much time being taken in CopyTensor3d.
> This is going to have to wait until I can look at it again. I'll leave it
> up though, until I decide what to do about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/443#issuecomment-171156141>.
>



-- 
Daniel Galvez
danieltgalvez.com

**Comment by danpovey** [comment]
BTW, just for the record, it looks like AddMat took about 35% less time in my configuration than AddMatMatBatched- or maybe even a bit faster than that.  I'm considering adding a flag that says that a component prefers its input and output matrices to be allocated stride == dim.  I have to think about this.

**Comment by danpovey** [comment]
@galv -- I have a new plan, and if you want to help with this, you can:
The new plan is to modify that component to detect when the input and output matrices' stride is equal to the num-rows, and if so to activate a different, faster code path.  Note that this is not hard to do also in the natural gradient update-- the actual natural gradient part of the update is segregated (see the block that says if (!is_gradient_))...  
Other code would have to be written to set and interpret flags to make sure the stride has no gaps, and I would do that.

**Comment by galv** [comment]
I believe you mean "stride is equal to the **num-cols**".

Anyway, I am aware that this has some complications, but I can certainly redo this as you suggest. However, I can't work on it until after the weekend.

I took the time to read about striding issues in CUDA, and I think what you propose will in fact finally allow us to get a speed up. My understanding is that accessing un-aligned memory is not an issue on modern nvidia GPUs. See the figure under "Misaligned Data Accesses" [here](http://devblogs.nvidia.com/parallelforall/how-access-global-memory-efficiently-cuda-c-kernels/).

**Comment by galv** [comment]
Are you still interested in this speedup? I can plan out what needs to be done, but I would have to ask a few questions. e.g., what the best way to allocate a CuMatrix without padding would be (e.g., new constructor, or optional boolean argument to existing constructor).

**Comment by danpovey** [comment]
@dgalvez, if you are going to add the option to  initialize  matrix with
stride==num-cols, please do so ASAP as a separate commit.  I need this for
something else.

**Comment by galv** [comment]
I haven't worked on this because I was of the impression that allocating the matrix with stride==num-cols would require modifying the CuMatrix code (in order to expose a new constructor which uses cudaMalloc instead of cudaMallocPitch). I'm not familiar with the code; it'll be a few days.

If you know of an easier way to implement this, then let me know.

**Comment by danpovey** [comment]
It's OK, I'll do it myself, it will be quick for me.  (to add the
constructor)

**Comment by galv** [comment]
okay. Thank you.

**Comment by danpovey** [comment]
I'm closing this pull request as I've done it myself (i'm testing it, it is a little faster; it's mixed in with some other stuff and I'll merge it soon).

**Comment by galv** [comment]
+1

On Sat, Feb 6, 2016 at 12:05 AM, Daniel Povey <notifications@github.com>
wrote:

> Closed #443 <https://github.com/kaldi-asr/kaldi/pull/443>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/443#event-541577417>.
>



-- 
Daniel Galvez
danieltgalvez.com

**Pull request closed without merging**
