### PR TITLE
added simple TDNN comparison run_tdnn_6v.sh for jesus models run_tdnn…

### PR DESCRIPTION
**Pull request by vijayaditya**
…_6h.sp

### CODE REVIEW

**Comment by vijayaditya** [comment]
this model has 9.8M parameters in chain part of network i.e., not counting parameters in xent only part of the nnet.

**Comment by danpovey** [comment]
Thanks- can you show me where you ran this?

**Comment by vijayaditya** [comment]
It is running in /export/a11/vpeddinti/tdnn_pool/egs/swbd/s5c/exp/chain/tdnn_v7_sp

Please note that I restarted the training from scratch due to some bugs in the config, and the restarted training is at iteration 33. So only logs till that iteration are valid.

**Comment by danpovey** [comment]
OK.
BTW, I see this: 'denominator_scale': 1.0,
I think this config is no longer needed, it was for CTC.

**Pull request merged**
