### PR TITLE
changed naming convention in natural gradient codes, in order to be consistent with the paper.

### PR DESCRIPTION
**Pull request by xiaohui-zhang**

### CODE REVIEW

**Comment by danpovey** [comment]
@xiaohui-zhang, please look into why the check failed for this PR.

**Comment by xiaohui-zhang** [comment]
fixed the type issue and improved comments

**Comment by danpovey** [comment]
I'll merge this once you confirm that changing the delta value doesn't make much difference.

**Comment by xiaohui-zhang** [comment]
sure

On Tue, Oct 6, 2015 at 12:44 AM, Daniel Povey <notifications@github.com>
wrote:

> I'll merge this once you confirm that changing the delta value doesn't
> make much difference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/209#issuecomment-145740245>.
>



-- 
Xiao-hui

**Pull request merged**
