### PR TITLE
Rnnlm scripts

### PR DESCRIPTION
**Pull request by Malkovsky**
Added 
1) Binary rnnlm-generate-text for rnnlm-based text generation.
2) Python script for introduce new texts into already generated G.fst. The main feature of that script compared to traditional interpolation of n-gram LMs is that structure of the G.fst stays the same.

The idea of using 1) as additional text comes from 
https://arxiv.org/abs/1907.06407
but with 2) in place of lm interpolation. This approach guarantees the same size of lm/G.fst used in decoding and thus almost the same RTF.

### CODE REVIEW

**Comment by danpovey** [comment]
I think the text-generation part is a good idea.
I am very skeptical that the part about keeping the G.fst structure the same is necessary. I think it would make more sense just to add the generated text as an extra data-source.  E.g. you could do it with pocolm which would pick the weight automatically.  (Pocolm doesn't scale well to big data, but if you had a large amount of training data you probablly wouldn't need to generate extra data anyway).  Or do normal interpolation with srilm, and then prune.
Also I don't think I would want to merge this without some kind of example script showing its utility on some task.  I hope you might be able to do that?

**Comment by Malkovsky** [comment]
Sure i can, will take some though. I got some improvement of LM based on these scripts but they were not on a well-known benchmark. Can you recommend me a recipe with the working rnnlm rescoring i can build my example upon?

**Comment by danpovey** [comment]
I'd try egs/tedlium/s5_r2 (or s5_r3, but that has more data so may be less
convenient to run.)

**Comment by Malkovsky** [comment]
I checked these scripts on tedlium and didn't find any improvements. These are roughly the results of nnet3-based decoding on dev
%WER 7.6 | 507 17783 | 93.6 4.9 1.6 1.2 7.6 74.2 | -0.028 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev/score_9_0.0/ctm.filt.filt.sys
%WER 7.3 | 507 17783 | 93.8 4.4 1.7 1.2 7.3 70.8 | 0.017 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_base_to_rnnlm_rescored/score_10_0.0/ctm.filt.filt.sys
%WER 7.2 | 507 17783 | 93.9 4.4 1.7 1.1 7.2 71.0 | 0.013 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rescore/score_10_0.0/ctm.filt.filt.sys
%WER 7.0 | 507 17783 | 94.1 4.2 1.7 1.1 7.0 70.2 | -0.372 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rescored_rnnlm_nascell/score_10_0.0/ctm.filt.filt.sys
%WER 7.6 | 507 17783 | 93.6 4.9 1.6 1.2 7.6 74.2 | -0.028 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm/score_9_0.0/ctm.filt.filt.sys
%WER 7.6 | 507 17783 | 93.5 4.9 1.7 1.1 7.6 75.0 | -0.010 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.1/score_9_0.0/ctm.filt.filt.sys
%WER 7.6 | 507 17783 | 93.5 4.9 1.7 1.1 7.6 75.0 | -0.007 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.2/score_9_0.0/ctm.filt.filt.sys
%WER 7.6 | 507 17783 | 93.5 4.9 1.7 1.1 7.6 75.1 | -0.015 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.3/score_9_0.0/ctm.filt.filt.sys
%WER 7.6 | 507 17783 | 93.5 4.8 1.7 1.1 7.6 75.1 | -0.023 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.4/score_9_0.0/ctm.filt.filt.sys
%WER 7.7 | 507 17783 | 93.3 4.9 1.8 1.1 7.7 75.1 | 0.050 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.5/score_10_0.0/ctm.filt.filt.sys
%WER 7.8 | 507 17783 | 93.3 4.8 1.9 1.1 7.8 75.5 | 0.060 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.6/score_10_0.0/ctm.filt.filt.sys
%WER 7.8 | 507 17783 | 93.4 5.0 1.7 1.1 7.8 75.9 | -0.008 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.7/score_9_0.0/ctm.filt.filt.sys
%WER 7.9 | 507 17783 | 93.3 5.0 1.7 1.2 7.9 75.5 | 0.000 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.8/score_9_0.0/ctm.filt.filt.sys
%WER 8.3 | 507 17783 | 92.9 5.2 2.0 1.2 8.3 75.9 | 0.078 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_0.9/score_10_0.0/ctm.filt.filt.sys
%WER 7.3 | 507 17783 | 93.9 4.6 1.6 1.2 7.3 71.6 | -0.033 | exp/chain_cleaned/tdnn1g_sp_bi/decode_dev_rnnlm_rescored/score_9_0.0/ctm.filt.filt.sys

decode_dev (7.6) and decode_dev_rescore (7.2) are from the baseline run.sh, decode_dev_rescored_rnnlm_nascell (7.0) is a lattice rnnlm rescoring, used just to check that rnnlm is properly build. decode_dev_rnnlm is and decode_dev rnnlm_rescored are the same as baseline but with ARPA LM build upon original plus generated texts, the prunning is the same as in local/ted_train_lm.sh. decode_dev_base_to_rnnlm_rescored is baseline decode rescored by the big LM based upon original plus generated texts. decode_dev_rnnlm_* is decode based on the suggested G post-training scripts.

**Comment by danpovey** [comment]
Since this didn't seem to help, I'll mark the PR as closed for now, but please leave that branch up, because we may want to return to this in future for some reason.

**Pull request closed without merging**
