### PR TITLE
Fix the problem that Smith-Waterman alignment might miss (1, 1) in align_ctm_ref.py (#4227)

### PR DESCRIPTION
**Pull request by DongjiGao**
Fix the problem that the Smith-Waterman alignment might miss (1, 1) during backtracing if they match

### CODE REVIEW

**Comment by wangsiw1** [comment]
@DongjiGao everything works fine except line 290, where it is possible to have negative score in the algorithm, and in my test case it raised exception at assertion on line 293 for an alignment with a word and a eps symbol. No problem other than that.
https://github.com/kaldi-asr/kaldi/blob/55e98edf82368177cfc5daeb596e891845a6225c/egs/wsj/s5/steps/cleanup/internal/align_ctm_ref.py#L290-L293

```
# Output log
2020-08-24 03:24:48,586 [./align_ctm_ref_new.py:329 - smith_waterman_alignment - ERROR ] Unexpected entry (0,0) -> (0,1), word_1, <eps>
2020-08-24 03:24:48,586 [./align_ctm_ref_new.py:599 - run - ERROR ] Alignment failed for recording 022-00018122-00000000-00000225 with ref = word_1 word_2 word_3 word_4 and hyp = <eps> word_1 word_2 word_3 word_4 <eps>
2020-08-24 03:24:48,586 [./align_ctm_ref_new.py:615 - main - ERROR ] Failed to align ref and hypotheses; got exception 
Traceback (most recent call last):
  File "./align_ctm_ref_new.py", line 291, in smith_waterman_alignment
    assert ref_word != eps_symbol and hyp_word != eps_symbol
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./align_ctm_ref_new.py", line 612, in main
    run(args)
  File "./align_ctm_ref_new.py", line 579, in run
    align_full_hyp=args.align_full_hyp)
  File "./align_ctm_ref_new.py", line 330, in smith_waterman_alignment
    raise RuntimeError("Unexpected result: Bug in code!!")
RuntimeError: Unexpected result: Bug in code!!
```

**Comment by DongjiGao** [comment]
> @DongjiGao everything works fine except line 290, where it is possible to have negative score in the algorithm
Thanks. I will fix that.
> and in my test case it raised exception at assertion on line 293 for an alignment with a word and a eps symbol. 
The eps_symbol only indicates there's empty in the alignment. It's a bit weird to have that symbol in your text. I think it might cause confusion. @danpovey what do you think?

**Comment by wangsiw1** [comment]
Those symbols are from decoding result(hyp) rather than our text input(ref). There is some silence in our audio input and I guess those eps_symbols were used to indicate the silent parts?

**Comment by DongjiGao** [comment]
> Those symbols are from decoding result(hyp) rather than our text input(ref). There is some silence in our audio input and those eps_symbols were used to indicate the silent parts, which should be fine I guess? Please correct me if I'm wrong.

I am talking about the eps_symobl ("-" by default) in align_ctm_ref.py. It is different from "<eps>" (which is silence) in your result. You might have set --eps-symbol="<eps>"?

**Comment by danpovey** [comment]
Dongji, are you sure that eps aren't expected in the hyp?  I thought we
might map silence to that?  But not sure about this.

**Comment by wangsiw1** [comment]
We are using steps/cleanup/segment_long_utterances_nnet3.sh in our pipeline where --eps-symbol is set to "<eps>" by default.

**Comment by DongjiGao** [comment]
> We are using steps/cleanup/segment_long_utterances_nnet3.sh in our pipeline where --eps-symbol is set to "" by default.

Oh, I see. I was wrong. I will fix that. Thanks!

**Comment by wangsiw1** [comment]
No problem, thanks for help!

**Comment by DongjiGao** [comment]
> Dongji, are you sure that eps aren't expected in the hyp? I thought we might map silence to that? But not sure about this.

You are right. The eps is allowed in hyp.

**Pull request merged**
