### PR TITLE
fix a bug, avoiding ambiguous reference

### PR DESCRIPTION
**Pull request by tzyll**
ambiguous reference "int64" between base/kaldi-types.h and ../tools/openfst/include/fst/types.h

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks.  Merging, but be aware that I don't have plans to do much with this branch in future.  The 'chain' models are performing better than the CTC models, and are simpler and easier to motivate, so that's what I intend to use going forward.  (Of course, it wouldn't be hard to just merge all this to master, but that would mean that we have to support it, which I don't want to do).

**Comment by tzyll** [comment]
Our experiments showed that with larger data (e.g.1400h), CTC does well, even better than DNN baseline without MPE, So we want to put MPE on CTC to see its potential.

**Comment by danpovey** [comment]
Makes sense.  BTW, you might get less gains with MPE from this version of
CTC than Google did.  The reason would take a while to explain- basically,
certain  mismatches due the use of context-dependent labels in Google's
setup don't exist in the setup I implemented because of the way we
normalize the probabilities.

What would be interesting for me is if you would test the 'chain' models
(chain branch; and see egs/swbd/s5/local/chain/run_tdnn_2y.sh for the
top-level example script) on your larger setup.  I haven't had a chance to
do this yet.  I'm confident the results will be even better than those CTC
numbers.
Dan

**Comment by tzyll** [comment]
Thanks a lot. I will test 'chain', then share the results on at least 1400h Chinese speech.

Yours,
Yuan

----- 原始邮件 -----
发件人: "Daniel Povey" <notifications@github.com>
收件人: "kaldi-asr/kaldi" <kaldi@noreply.github.com>
抄送: "Zhiyuan Tang" <tangzy@cslt.riit.tsinghua.edu.cn>
发送时间: 星期五, 2015年 12 月 25日 上午 5:25:40
主题: Re: [kaldi] fix a bug, avoiding ambiguous reference (#412)

Makes sense. BTW, you might get less gains with MPE from this version of 
CTC than Google did. The reason would take a while to explain- basically, 
certain mismatches due the use of context-dependent labels in Google's 
setup don't exist in the setup I implemented because of the way we 
normalize the probabilities. 

What would be interesting for me is if you would test the 'chain' models 
(chain branch; and see egs/swbd/s5/local/chain/run_tdnn_2y.sh for the 
top-level example script) on your larger setup. I haven't had a chance to 
do this yet. I'm confident the results will be even better than those CTC 
numbers. 
Dan

**Pull request merged**
