### PR TITLE
Turkish lexicon and phoneset

### PR DESCRIPTION
**Pull request by SnowWhitesStepMom**
Hello,
I prepared a phonetic lexicon, corrsponding phoneset and  a small LM for Turkish.
There was nothing about Turkish, I wanted to add at least phonetic stuff.

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks for the pull request-- some of this is potentially useful but I
notice you say there is no training set... I'm at a conference, will
respond in more detail later.

Dan


On Mon, Dec 14, 2015 at 1:01 AM, SnowWhitesStepMom <notifications@github.com

**Comment by SnowWhitesStepMom** [comment]
Hello Dan,
Thanks for the answer.
Surely my directory is not suitable for experimenting like this.
There's no open source Turkish speech corpus.
I bought some corpus for a specialized company and I have 2 corpora from
LDC, one is called METU Microphone corpus and second is Turkish News and
Transcriptions. Company I work for bought them, so I can't make them
available as well.
I experimented with this corpus and I believe my lexicon is not bad:)

My directory looks not very useful to me as well without any training set.
Should I add info about LDC corpora to README? Do you have any suggestions
about absence of training set?

Best, Duygu.
14 Ara 2015 21:38 tarihinde "Daniel Povey" <notifications@github.com> yazdı:

**Comment by danpovey** [comment]
Data does not have to be open as long as it is available somehow, so LDC
corpora are 100% OK (e.g. WSJ is like that).
Typically egs/ directories are associated with either particular corpora or
combinations of corpora, e.g. egs/swbd for Switchboard or egs swbd_fisher
(IIRC) for Switchboard + Fisher.
If you want to submit an example script, please decide what data it should
run for.  We don't commit things that have "missing pieces" that are not
available at all-- it has to run from start to finish once you buy the
data.

**Comment by SnowWhitesStepMom** [comment]
Sure, then I'll write a more detailed readme detailed description of
getting the speech corpıea and also include WERs as soon as I have the time.

Kind Regards, D.
14 Ara 2015 23:01 tarihinde "Daniel Povey" <notifications@github.com> yazdı:

> Data does not have to be open as long as it is available somehow, so LDC
> corpora are 100% OK (e.g. WSJ is like that).
> Typically egs/ directories are associated with either particular corpora or
> combinations of corpora, e.g. egs/swbd for Switchboard or egs swbd_fisher
> (IIRC) for Switchboard + Fisher.
> If you want to submit an example script, please decide what data it should
> run for. We don't commit things that have "missing pieces" that are not
> available at all-- it has to run from start to finish once you buy the
> data.
>
>
> On Mon, Dec 14, 2015 at 12:55 PM, SnowWhitesStepMom <

**Comment by danpovey** [comment]
SnowWhitesStepMom-- I'll close this pull request for now; please submit another one tailored to the specific LDC corpora.

**Comment by SnowWhitesStepMom** [comment]
Sure, I'll make another request when everything is ready.

**Pull request closed without merging**
