### PR TITLE
Kaldi 52

### PR DESCRIPTION
**Pull request by YiwenShaoStephen**

### CODE REVIEW

**Comment by YiwenShaoStephen** [comment]
@hhadian It can only support color==3 (rgb) matrix by now. But I think it might be enough for cifar sets.

**Comment by hhadian** [comment]
This is working. Before merging, I need to test it with matrices from nnet egs too.

**Comment by YiwenShaoStephen** [comment]
Good luck with it! As we have a 12 hours gap in time, I couldn't response until 9 or 10 hours later. If there is any other problem, leave it to me. I will try to fix it tomorrow.

**Comment by hhadian** [comment]
It is working fine. I added a script to make it easier to see images in egs. 
Augmentation works fine when only flipping but corrupts the image when shift is enabled.

**Comment by danpovey** [comment]
Hossein, make sure you give the --num-channels=3 option to the augmentation
binary.

**Comment by hhadian** [comment]
I am using that option.
I did more checking now, vertical shift is working fine too. Horizontal shift corrupts the image though.

**Comment by danpovey** [comment]
OK, have a look at the code and fix it; I never reviewed it thoroughly.

**Comment by danpovey** [comment]
I see now that Hossein said this was OK to merge.  Merging it.

**Pull request merged**
