### PR TITLE
WIP: Chime5/6 with Paderborn guided source separation

### PR DESCRIPTION
**Pull request by vimalmanohar**
This is in preparation for a new Chime recipe.

@sw005320

### CODE REVIEW

**Comment by jtrmal** [comment]
@sw005320 @vimalmanohar  it would be a shame to let this die off

**Comment by danpovey** [comment]
We can consider just merging it with any problems it has, assuming it
doesn't break anything else.
Let's get a comment from Shinji about this, at least.

**Comment by jtrmal** [comment]
I don't object, but it should be at least runnable, I think.
y.

**Comment by danpovey** [comment]
We could just rely on users to fix the problems, maybe?  Anyway it's the
kind of task that will only attract experts.

**Comment by aarora8** [comment]
Hi,
Our recent chime6 setup in the kaldi master is the same as this one. This
setup was also for chime6 baseline
Thanks,
Ashish

**Comment by jtrmal** [comment]
ashish, thanks -- are you saying this can be closed as the interesting bits
have been ingested to other recipe?
y.

**Comment by aarora8** [comment]
Yeah, it can be closed as the interesting bits have been ingested to chime6
recipe.

**Comment by jtrmal** [comment]
thanks!
y.

**Pull request closed without merging**
