### PR TITLE
Fix utils/split_scp.pl breakage

### LINKED ISSUE #3306: utils/split_scp.pl broken
After b17fc8447, `utils/split_scp.pl -j 16 3 src-lats.scp` outputs the chunk 4 of 16 to a regular file named `-` instead of STDOUT.

The reason is the "old" 2-argument form `open FH, ">-"` used to open a handle to STDOUT, while the "modern Perl" `open $fh, '>', '-'` creates a real file named `-` instead.

### PR DESCRIPTION
**Pull request by kkm000**
Close #3306

### CODE REVIEW

**Comment by kkm000** [comment]
Hold on, did not cleanly merge

**Comment by kkm000** [comment]
This is ready to go now. I also cleaned up error messages, and fixed the -j M N argument check with and without one-based.

**Comment by danpovey** [comment]
Thanks!  Note: this is a fixed version of #3285 which was reverted in #3307.

**Comment by kkm000** [comment]
Yes, I noticed, I clashed with the revert :)

**Comment by danpovey** [comment]
You sure, right?

**Comment by kkm000** [comment]
I just used this in a practical script, and update my scripts to --one-based between two runs, both went out ok; I have thorough error checks in my scripts to make sure data counts all match after processing, and they do. I do not have a practical utt2spk-based case to test at the moment, though (although the next step, merging alignments and lattices, that we once talked on the list, likely will use it).

**Comment by kkm000** [comment]
> You sure, right?

So pretty much yes, and I am likely to use it more a few times today. I'll be merging a complex dataset, with lattices coming from separate alignments, so if anything comes up, I'll notice.

**Comment by danpovey** [comment]
Remind me to-morrow, I'll merge then.

**Comment by kkm000** [comment]
@danpovey:
> Remind me to-morrow, I'll merge then.

Yup. You did the right thing. :) There is more weirdness, fixing now. I'll push when all modes work, and then let you know.

**Comment by kkm000** [comment]
@danpovey, this flies! (and with the updated combine_ali_dirs, which comes tomorrow).

**Comment by danpovey** [comment]
OK.  @kkm000, FYI I usually prefer to use filter_scp.pl using the appropriate utt2spk file, instead of split_scp.pl.   It probably doesn't make much difference though.

**Comment by kkm000** [comment]
@dpovey, so can we merge it?

**Pull request merged**
